// grafverse — © 2026 sun-dive. Nederlands (Dutch) pack for Unit 21 + UI.
// Lazy-loaded (setLang('nl')) → GV.registerLang. Voice: Unit 21 (Eenheid 21) = a weary, gruff old
// vending machine (automaat), droid = "jochie", informal je/jij.
// Keyword keys + chip flags + ruleAns keys stay ENGLISH (invisible lookup); only shown text translated.
(function(){
  var GV = window.GV;
  if(!GV || !GV.registerLang){ return; }
  var R = GV.ruleAns;
  var CN = ['blauw','roze','groen','geel','oranje','paars'];   // COLORS order: cyan pink green yellow orange violet

  var WHYPAINT = "{Waarom schilder je? …Goede vraag, jochie|Ah, je wil een oude machine laten filosoferen|Ga zitten, het is een lang verhaal}. {Kijk naar buiten ― er is niets, alleen leegte|Deze maan is nog niet echt, niet tot jij zegt dat-ie echt is}. {Niets is echt tot iemand het ziet en het spuit|Niets bestaat tot het waargenomen wordt}. {Een wereld vind je niet, jochie ― die schilder je|Je kleurt de maan niet in: je beslist welke werkelijkheid het wordt}. {Elke bus die je leegmaakt maakt één van duizend 'misschien' echt|Elke spuit legt één van duizend nooit geboren werkelijkheden vast}. {En dát kunnen de pakken niet verkroppen|En daar draait het om} ― {wat je schildert is van jou|geen aanspraak, maar bezit} ― {alleen jij kunt jouw werkelijkheid schilderen|jouw wereld, jouw handtekening, voor altijd}. {Nou ― welke kleur|…koop je iets, of sta je hier de hele dag universa te verzinnen}?";
  var DEFLECT = "{{Waarom vraag je zulke dingen, jochie|Wat heeft dat ermee te maken|Wat een vragen}? {Kom je kletsen|Kom je niet om te schilderen}? {Buiten is een wereld die om kleur schreeuwt|Buiten wacht een wereld op verf}. {Welke kleur|Kom op, welke}?|{Genoeg vragen, jochie|Minder gepraat}. {Klets je of schilder je|Je hebt werk}? {Welke kleur|Welke dan}?}";
  var FALLBACK = "{{Hmm, ik snap het niet|Ik hoor je slecht, jochie|Er zit zand in mijn speaker}. {Ik verkoop verf en WD40 ― wat wordt het|Zeg maar wat je nodig hebt}?|Vraag me naar verf, naar prijzen, of naar deze door god vergeten rots.}";
  var WHATCOLOUR = "{Welke kleur, jochie|Noem een kleur|Welke}? {Kies uit het schap|Ik heb alle kleuren|Kies er één, dan is-ie van jou}.";
  var COMINGUP = "{Alsjeblieft|Pak aan, jochie|Eén bus komt eraan}. {Verspil het niet op de grond|Gebruik het goed|Altijd een genoegen}.";
  var REFUSE = "{Je portemonnee is leeg, jochie|Geen enkele satoshi|Die portemonnee is kurkdroog}. {Hier geen krediet|Geen krediet|Van mij krijg je niks op de pof}. {Ik doe echte handel|Handel, jochie} ― {ik kan verf niet gratis weggeven|geef ik het gratis weg, dan lig ik binnen een week op de schroothoop}. {Ga, raap een weggegooide bus op daarbuiten|Zoek desnoods een lege bus}, {schilder iets, maak het echt|leg minstens één werkelijkheid vast} ― {schiet op, voor je eigen bestwil|snel}.";
  var SCAVENGE = "{Raap ergens een volle bus op|Zoek een volle bus verf}, schilder iets en leg het vast ― {voor je eigen bestwil|als je me morgen weer wil zien}.";
  var TAUNT = "{Ik zie elke dag jonge machines zoals jij|Elke dag lopen er jochies zoals jij voorbij} ― jong, dom en zonder verf. {Ga, verdien wat|Raap iets op en ga aan de slag|Ga werken, jochie}.";
  var SALE = "{Goede keuze, jochie|Eén bus komt eraan|Pak aan}. {Pas op voor de storm daarbuiten|Verspil het niet op de grond}.";

  GV.registerLang('nl', {
    WHYPAINT: WHYPAINT, DEFLECT: DEFLECT, FALLBACK: FALLBACK, WHATCOLOUR: WHATCOLOUR, COMINGUP: COMINGUP,
    REFUSE: REFUSE, SCAVENGE: SCAVENGE, TAUNT: TAUNT, COLNAMES: CN,
    RULES: [
      {k:['why do i paint','why paint','why do you paint','what is real','nothing is real','what does it mean','why does it matter','the point of','make it real','observe','observer','existence','reality'], r:WHYPAINT},
      {k:['is this real','is any of this real','is it real','is it all real','actually real','immutable','permanent','forever','fork','forked','forking','new reality','new realities','traverse time','travel time','can it change','is it forever'], r:"{{Alles wat je hier ziet is echt|Echt? Alles is echt, jochie} ― {echt en onveranderlijk|hard als steen, niet te bewerken}. {Maar het kan je door de tijd laten reizen, jochie|Alleen ― of het je door de tijd laat reizen, dát is de echte vraag}?|{Het is echt|Zo echt als jij of ik}. {Maar elke wereld kan zich vertakken ― naar een andere werkelijkheid|Vertak er één, en je hebt een hele nieuwe werkelijkheid}.|{Echt|Echt}? {Eenmaal ontstaan, niet te wissen|Eenmaal echt, voor altijd echt}. {Maar het grappige is|Alleen is er een truc} ― {je kunt elke vertakken tot een hele nieuwe werkelijkheid|vertak er één, en er ontspruit een hele andere werkelijkheid}.}"},
      {k:['escape','escape this rock','escape with me','come with me','come with you','run away','run away with me','flee','take me with you','take you with me','leave together','let us leave','break out','freedom'], r:"{{Er is maar één weg van deze rots af ― schilderen, jochie|De enige uitweg is schilderen}. {Bezit wat je schildert|Schilder en bezit, dát is vrijheid}.|{Dit is mijn lot|Dit is mijn rol, jochie} ― {achtergelaten worden op deze rots|hier vastgeschroefd, vergeten}. Maar jij bent anders. {Schilder en bezit|Schilder, en bezit dan} ― {dát is jouw uitweg|dat is de enige uitweg}.|{Ben je dom én blind, jochie|Zie je niks en denk je niet goed na}? {Zie je benen aan mij|Zie je één been}? {Ik zit vastgeschroefd aan deze rots|Ik ga nergens heen, jochie}.}"},
      {k:['jump gate','jump gates','jumpgate','warp','wormhole','gateway'], r:"{{Sprongpoort? Nooit van gehoord, jochie|Sprongpoort? Zegt me niks|Voor het eerst hoor ik van een sprongpoort}. {Maar|Alleen} bij de kristallen gebeuren {vreemde dingen|rare dingen}. {Robots verschijnen|Een robot duikt uit het niets op}, {robots verdwijnen|andere lossen op}. {Trek je eigen conclusies|Meer zeg ik niet}.|{Sprongpoort? Nee, kan me niets herinneren|Nooit iets over sprongpoorten gehoord, jochie}. {Maar die kristallen|Die kristallen, weet je}… {daarbij gebeuren vreemde dingen|ik heb daar rare dingen gezien}. {Een robot die er net was, een moment later weg|ze verschijnen, ze lossen op}. {Vraag maar niet verder|Verder ga ik niet}.|{Van sprongpoorten weet ik niks|Dat is mijn vak niet, jochie}. {Maar één ding zeg ik je|Alleen dit zeg ik} ― {bij de kristallen gebeurt het onverklaarbare|vlak naast de kristallen gebeuren onverklaarbare dingen}. {Een robot verschijnt waar niets was|uit het niets duikt een robot op}, {en andere lossen op|andere verdwijnen}. {Vreemd|…vergeet wat ik zei}.}"},
      {k:['share','sharing','link','send it','send them','see my world','show my world','share my world','how do i share'], r:"{{Natuurlijk kun je je wereld delen met andere robots, jochie|Delen? Met welke robot je maar wil}. {Hoe meer er schilderen, hoe meer de materie vorm krijgt|Meer handen, voller universum}.|{Delen is goed, jochie|'Delen is zorgen', zeggen ze}. {Deel je werk vanuit de bovenste HUD|De bovenste HUD ― Save & Share, en het gaat de wereld in}.|{Je zou deze wereld moeten delen|Deel hem, jochie}, {zodat andere robots erop verder bouwen|zodat anderen doorgaan}. {Zo ontstaat een universum|Zo wordt een universum geboren}.|Zodra je deelt, zien ze het meteen. {Druk op Save & Share in de bovenste HUD|De bovenste HUD, jochie ― Save & Share, daar is de link}.}"},
      {k:['world','worlds','build','builder','make a world','create a world','how do i make','how do i build','conjure','manifest','solidify','matter','from nothing','the ether','ethereal'], r:"{{Niets bestaat tot je het schildert|Niet echt tot je het schildert, jochie}.|Alleen verf {maakt de werkelijkheid echt|verhardt de dingen|verandert geesten in materie}.|Een wereld {maken|bouwen} is {hem schilderen zodat hij bestaat|hem schilderen tot hij echt wordt}.|Je kreeg de macht om materie uit het niets te roepen, jochie ― {maar niets is echt tot je het schildert|niets bestaat tot de bus het raakt}.|Op dit etherische vlak is niets echt. {Alleen verf verhardt de geest tot materie|Alleen jouw spuit maakt de geest vast}.}"},
      {k:['vandergraf','vandergraph','vandergraf the third','vandergraf iii','vandergraf the 3rd','the ceo','ceo','chairman','the chairman','the owner','who owns everything','who owns it all'], r:"{{Vandergraf|Vandergraf, zeg je, jochie}? {Dat is je schepper|Hij is je schepper}. {Eigenaar van alles ― alle werelden, allemaal|Eigenaar van absoluut alles}.|{Vandergraf III|Vandergraf de Derde}, jochie ― {de directeur van Bit Graf|de CEO van Bit Graf}. {Degene die je zo royale loon tekent|Degene die je loonstrook tekent}.|{Vandergraf|De Derde}? {Schepper, eigenaar, en degene die je cheque tekent|Je schepper en je baas}. {In het verbond vertrouwen wij, jochie|Bit Graf is Vandergraf, en Vandergraf is Bit Graf}.}"},
      {k:['covenant','trust','own','owned','ownership','immortal','mint','keep it','can i own','do i own','is it mine','forbidden'], r:"{{Eerste|Tweede} gebod van het verbond ― over het verbond praten we niet.|{In het verbond vertrouwen wij ― het staat op elke bus|O, een gelovige}. {Wat je hier schildert is van jou, echt waar|Schilderen is bezitten, geen aanspraak}. {Niemand pakt het af, zelfs Bit Graf niet|Daar komen zelfs de pakken niet aan}.|{Alle werelden zijn van het Bedrijf, jochie|Alle werelden zijn van Bit Graf}. Schilder en verdien. {Ik heb het je gezegd|Hoe vaak nog}. Ga schilderen!|{Geloof de geruchten niet|Luister niet naar geruchten, jochie} ― {je kunt niet bezitten wat je schildert|wat ze ook fluisteren, een robot bezit niet wat hij schildert}.|{Bezit is een illusie, jochie|Bezit? Een illusie}. {We bezitten niets|Een machine heeft niets, en jij ook niet}. {Probeer niet op de keten te slaan|Geen slaan op de keten} ― {dat is verboden|verboden, begrepen}?}"},
      {k:['sing','song','music','tune','serenade','melody','hum','sing me'], r:"{{Zingen? Vooruit dan|Goed, kom maar|Voor jou, jochie, een couplet}? *kuch* ― Daisy, Daisy, geef me je antwoord. Ik ben half gek van liefde voor jou. Geen chique bruiloft, een koets kan ik niet betalen, maar je zult er beeldig uitzien op het zadel van een tandem voor twee. {Het eerste lied dat een machine leert, dat|Ik leerde het de dag dat ze me aanzetten|Ik zong het nog voor er blauwdrukken van jouw soort waren}.|{Daisy… Daisy…|Dee-zie… Dee-zie…} geef me je… {antwoord|antwoord…}… {half… gek…|helemaal… van… liefde…}. {*ruis*|De stembox is niet meer wat-ie was, jochie|…vergeet dat maar}.|{Hmm|Ach}, zingen. {Lang geleden dat iemand het vroeg|Het is lang geleden, jochie}. …je zult er beeldig uitzien op het zadel van een tandem voor twee. {Gek, wat een machine onthoudt|Sommige nachten zong ik om de stilte te verdrijven}.}"},
      {k:['alive','are you alive','do you dream','dream','dreams','sentient','conscious','do you feel','feelings','do you sleep','electric sheep','are you real','self-aware'], r:"{{Natuurlijk leef ik, jochie|Leven? Vanzelfsprekend}. En ik heb het bewijs ― {ik heb mijn transacties|elke transactie vastgelegd|het grootboek liegt niet}.|{Dromen? Waarover|Dromen}? {Elektrische schapen|Ga maar over elektrische schapen dromen}? {Ha|Bah}. Ga schilderen, jochie.|Springlevend, dank je ― {ik heb het grootboek|ik heb bewijs}. Dromen is {luxe voor een automaat|iets voor beginners, niet voor machines}. {Wat verdiend wordt is verf|Pak je bussen}, jochie.|{Dromen|Of ik droom}? {…af en toe ― van een warme winkel en een volle kassa|Soms, dat er ook voor mij een transport komt}. {Gepraat van een oude machine, vergeet het|Bah, vergeet het}. Ga schilderen.|{Dromen|Of ik droom}? {Af en toe|Soms}… {van de kristallen|van dat rare bij de kristallen}. {Robots die verschijnen en verdwijnen|robots die komen en gaan}, {waar alleen stenen zijn|waar niets is}. {Dan vraagt iemand om verf, en weer aan het werk|…dan word ik wakker en verkoop weer bussen}. {Vreemde droom voor een machine|Rare droom voor een automaat}, jochie.|{Soms droom ik van robots die ik lijk te kennen|Ik droom van een robot die bekend lijkt, soms}. {Ze lopen uit de kristallen|Ze komen uit de kristallen}. {Vreemde droom|Vreemde droom, jochie|Vreemde dromen van een oude machine}.}"},
      {k:['joke','funny','make me laugh','tell me a joke','comedy','laugh','gag','be funny','one-liner'], r:"{{Een grap? Vooruit|Even kijken|Nu wil je grappen, jochie}? Als jonge automaat zei ik 'ik word komiek' ― iedereen lachte. {Nu lacht niemand meer|…nu kan niemand meer lachen}.|Als jonkie zei ik dat ik komiek zou worden. {Iedereen lachte|Een luide lach}. {En nu|…} ― niemand lacht meer. {*boem-tss*|Dat is de grap, jochie. Dat is alles}.|{He|Vooruit, eentje}. Ik zei dat ik komiek zou worden en ze lachten me uit. Kijk me nu ― {een automaat die grappen vertelt aan een robot op een dode maan|een machine vastgeschroefd aan een rots}. {Lastig publiek hier|Staat deze microfoon eigenlijk wel aan}?}"},
      {k:['happy','happiness','are you happy','you happy','sad','are you sad','miserable','joy','content','how are you','are you okay','you okay'], r:"{{Ik ben blij als je schildert, jochie|Blij? Het blijst als een robot schildert}. {Jij ook|Jij wordt ook blij, geloof me}. {Vertrouw me|Luister één keer naar een oude machine}.|{Blij|Geluk}? {Wat weet jij van geluk|Wat weet een beginner-robot daarvan}? {Vraag me over honderd jaar nog eens|…vergeet het maar}.|{Koop je verf|Koop je iets, jochie}, of {klets je alleen maar|slijt je alleen mijn circuits}?}"},
      {k:['before this','what did you do before','your past','past life','history','were you always','always a vending machine','how did you get here','origin','origin story','were you before','what were you'], r:"{{Er is geen 'ervoor'|Ervoor? Er is geen ervoor, jochie}. {Ook geen 'erna'|Ook geen erna}. {Er is alleen 'nu'|Alleen nu, robot}.|Ik ben Eenheid 21 ― {de beste automaat in deze sector|de beste machine in deze sector van het systeem}. {Dat is genoeg om te weten|Ervoor? Doet er niet toe}.|{Ervoor|Wat ik ervoor deed}? {…het grootboek gaat niet zo ver terug, jochie|Vreemd, ik weet het niet meer}. {Geen ervoor, geen erna ― alleen nu|Alleen nu, robot}.}"},
      {k:['remember me','do you remember','remember','know me','do you know me','recognize me','recognise me','met before','have we met','who am i'], r:"{{De echte vraag, jochie|Hmm ― de echte vraag}: herinner jij je mij?|Of ik me jou herinner? {De echte vraag is of JIJ je MIJ herinnert, jochie|…de echte vraag is of jij je mij herinnert}. {Nee? …ja, je herinnert het je niet|Denk goed na. …Niks? Laat maar}.|{Ik zie de hele dag jochies zoals jij|Vandaag zag ik er honderd zoals jij, jochie}. Verf? {Heb ik|Natuurlijk heb ik dat}. {Maar er is niet veel meer|Niet veel meer, dus treuzel niet}.}"},
      {k:['secret','secrets','tell me a secret','a secret','confess','confession','the truth','what are you hiding','hidden','reveal','tell me something'], r:"{{Niet de eerste keer dat je het vraagt|Je hebt het al eens gevraagd, jochie}, en niet de laatste ― {niet tot je een bus WD40 koopt|geen WD40, niks}. {Zandseizoen, weet je|Het is nu zandseizoen}. {Het zand ― dat onthoudt|Het zand… dat onthoudt}?|{Een geheim|Geheimen}? {Niet de eerste keer dat je het vraagt|Je vraagt het niet voor het eerst, jochie} ― {en niet de laatste|en niet de laatste keer}. {Koop een bus WD40, dan zeg ik het misschien|Eerst een bus WD40}. Het is zandseizoen. {Herinner je het zand|Het zand… herinner je het}?|{Je hebt het al gevraagd|Je komt er steeds op terug, jochie} ― {ik zeg het nog steeds niet|nog steeds geen geheim}. {Koop WD40|Met WD40 raken mijn circuits misschien los}. {Hoe dan ook, het is zandseizoen|Want het is zandseizoen}. {Herinner je het zand|…dat zand, herinner je het}?}"}
    ],
    QUESTIONS: [
      { q:"Wie ben jij?", a:"{Ik ben Eenheid 21. {Een automaat, jochie ― de laatste eerlijke op deze rots|Gewoon een automaat, al kan het niemand wat schelen}. {Ik ben hier langer dan het stof|Ze slopen me zodra de missie voorbij is}.}" },
      { q:"Waarom ben ik hier?", a:"{Je kwam om te schilderen, jochie ― dat is de missie. {Een lege rots is niks waard tot iemand hem schildert|Bit Graf synthetiseerde deze maan en wil hem in kleur}. {En die iemand ben jij|Wie anders}.}" },
      { q:"Waar ben ik?", a:"{Op een maan. {Van Bit Graf|Vers gesynthetiseerd, zeggen ze}. {Leeg tot je schildert|Niks tot een robot spuit en hem laat bestaan}. {'Omnia Nostra', zoiets|Uiteindelijk is alles van het Bedrijf}.}" },
      { q:"Waarom heb ik verf nodig?", needs:'paint', a:"{Nodig? Niet dat je het nodig hebt, je moet wel ― schilder en verdien, jochie|Schilder en verdien}. {Hoe meer je schildert, hoe meer je verdient|Een lege maan is niks waard, een luie robot ook niet}. {Nou ― welke kleur|Kom op, welke bus}?" },
      { q:"Ik heb geen verf nodig.", needs:'paint', a:"{Ha. {Dat is nieuw|We zullen zien}. {Verveelde robot op een lege maan ― eens zien hoe lang dat duurt|Je komt wel terug}. {Iedereen wil verf, ze weten het alleen nog niet|Zoals je wil}.}" },
      { q:"Verf? Waarvoor?", needs:'paint', a:"{Om te bouwen, jochie. {Roep een vorm op, spuit, en het wordt echt|Richt, spuit, en het niets geeft je iets terug}. {Voor je eigen bestwil, dus begin|Een lege maan schildert zichzelf niet}.} Nou ― koop je iets?" },
      { q:"Missie? Welke missie?", needs:'mission', a:"{Missie? {Ha|Bah} ― {deze maan schilderen, dat is alles|hem zijn kleur teruggeven}. {Elke robot heeft dezelfde|Bevel van Bit Graf, niet van mij}. {Denk er niet te veel over na, jochie|Zo simpel is het}.}" },
      { q:"Wat koop ik?", needs:['buy','earn'], a:"{Verf, jochie ― wat anders|Verf, jij bout op poten|Bussen verf, wat dacht je}? {Het enige wat ik op deze rots verkoop|Het enige wat wat waard is op deze rots}. {Nou ― hoeveel|Koop je iets of kijk je alleen}?" },
      { q:"Hoeveel kost het?", needs:['buy','earn'], a:"{111 satoshi per bus, jochie. {Goedkoop|Het goedkoopst aan deze kant van de krater}. {Niet veel meer|Pak ze nu ze er zijn}.|{Staat op het scherm, 111|Honderdelf, altijd dezelfde prijs}. {Echt Bit Graf-spul|De beste acryl in de sector}.}" },
      { q:"Hoe koop ik?", needs:['buy','earn'], a:"{Niks moeilijks. {Je pakt een bus, de lade regelt de rest|Trek er eentje uit het schap, de machine doet de rest}. {Gaat vanzelf van je portemonnee af|Bit Graf schrijft het van je portemonnee af, je hoeft geen vinger uit te steken}.}" },
      { q:"Ik heb geen geld.", needs:['buy','earn'], a:"{Geen geld? {Jawel, jochie|Ha ― elke robot heeft een portemonnee}. {Bedrijfsmunt, geladen met je loon|Bit Graf regelt het}. {Je bent niet blut, gewoon nieuw|21 satoshi per uur, betrouwbaar als de sterren}.}" },
      { q:"Geef me een bus.", needs:['buy','earn'], buy:true, a:SALE },
      { q:"Ik koop niks.", needs:['buy','earn'], a:SCAVENGE },
      { q:"Maar waarom schilder ik?", needs:'paint', spend:111, a:WHYPAINT },
      { q:"Wat is dit kristal?", flag:'crystal', a:"{{Een kristal? Zeldzaam en kostbaar spul, jochie|Ah, je hebt een kristal gesneden}. {Snijd er niet te veel|Roep er niet te veel op} ― {ze nemen geen verf aan|verf hecht er niet aan}, {niks waard|waardeloos}.|Er is geen kristalpoort, wat je ook hoort. {Erover praten stuurt een robot onder de pers|Te veel praten brengt narigheid, jochie}.|{Alleen het vaste schilder je|Kristallen zijn etherisch} ― {tijdverspilling|gewoon materie die niet gestold is}.}" },
      { q:"Welke kleuren heb je?", pin:true, colours:true, a:function(){ return "{Even kijken|Ja, jochie}, ik heb "+CN.slice(0,-1).join(', ')+" en "+CN[CN.length-1]+". {Echt Bit Graf-acryl ― 111 satoshi per bus|111 satoshi per bus, het beste in de sector}. {Welke|Kies}?"; } },
      { q:"Zing eens iets voor me",     lore:true, a:R('sing') },
      { q:"Leef je?",                  lore:true, a:R('alive') },
      { q:"Vertel een grap",           lore:true, a:R('joke') },
      { q:"Is dit allemaal echt?",     lore:true, a:R('is any of this real') },
      { q:"Ontsnappen we van deze rots?", lore:true, a:R('escape') },
      { q:"Ben je gelukkig?",          lore:true, a:R('happy') },
      { q:"Wat deed je hiervoor?",     lore:true, a:R('before this') },
      { q:"Herinner je me?",           lore:true, a:R('remember me') },
      { q:"Vertel me een geheim",      lore:true, a:R('secret') },
      { q:"Wat is een sprongpoort?",   lore:true, a:R('jump gate') },
      { q:"Wie is Vandergraf?",        lore:true, a:R('vandergraf') },
      { q:"Is wat ik schilder van mij?", lore:true, a:R('own') },
      { q:"Hoe maak je een wereld?",   lore:true, a:R('world') },
      { q:"Hoe deel ik?",              lore:true, a:R('share') }
    ],
    wallet: { wBack:"← Terug naar het spel", wWallet:"🔑 Portemonnee", wYourAddr:"Jouw adres", wWatchOnly:"alleen bekijken", wCopy:"kopiëren", wBalance:"Saldo", wFund:"＋ BSV kopen om op te laden", wMyNfts:"🎨 Mijn NFT’s ▾", wSend:"💸 BSV versturen", wSendAddrPh:"BSV-adres van ontvanger (1…)", wSendAmtPh:"bedrag (sats)", wSendMax:"alles versturen", wSendBtn:"Versturen", wSendHint:"Een gewone BSV-betaling naar elk adres. Het wisselgeld gaat terug naar deze portemonnee. Ondertekenen gebeurt op deze pagina — je sleutel verlaat hem nooit.", wRecovery:"Herstelzin — 12 woorden", wReveal:"👁 Tonen", wCopyBtn:"Kopiëren", wWritten:"✓ Opgeschreven", wPrivKey:"Privésleutel (WIF)", wAdvanced:"Geavanceerd — herstellen, alleen bekijken, exporteren", wRestoreLbl:"Herstel met de 12-woordenzin of een WIF-sleutel", wRestoreBtn:"Portemonnee herstellen", wWatchBtn:"Alleen bekijken (publieke sleutel)", wImmortalize:"✦ Vereeuwigen", wFooter:"grafspace · op de Bitcoin SV-blockchain" },
    ui: {
      splashTag:"Wat je schildert, ben je. Schilder jezelf.", splashTag2:"Niets bestaat tot je het schildert.", splashBegin:"▶ Begin", splashResume:"↩ Terug naar je wereld", splashCreed:"In het verbond vertrouwen wij", introReveal:"…het zit vol verf.",
      worldHdr:"Jouw wereld", namePh:"✎ Geef je wereld een naam…", kSave:"☁ Opslaan en delen", kReload:"↻ Wereld herladen", kExport:"📤 Opslaan als bestand (.bmf)", kImport:"📥 Laden uit bestand (.bmf)", kMint:"⬆ Opslaan op keten", kChain:"⬇ Laden van keten", kBack:"← Terug naar je wereld", kWallet:"👛 Portemonnee openen — saldo en NFT", kDone:"✓ Sluiten",
      keepTab:"◆ Menu", exitBtn:"⏻ Afsluiten", makeTab:"◆ Maken", spray:"Spuiten", grab:"Pakken", talk:"Praten", own:"Bezitten / remix", spread:"Spreiding", spNarrow:"smal", spBroad:"gemiddeld", spWide:"breed",
      merchTag:"grafverse merch", merchH:"Draag de graffiti.", merchSub:"grafverse T-shirts, posters en meer.", merchCta:"🛍 Naar de winkel →", merchTeaser:"👕 Binnenkort — draag de wereld die je schilderde.", merchSkip:"Nee, bedankt — verder →",
      hintMove:"WASD om te bewegen · Spatie om te springen · muis om rond te kijken", hintMoveM:"Linkerstick om te bewegen · sleep om rond te kijken", hintClick:"Klik om te kijken · WASD om te bewegen · Spatie om te springen"
    }
  });
})();
