// grafverse — © 2026 sun-dive. Français (French) pack for Unit 21 + UI.
// Lazy-loaded by the i18n scaffold (setLang('fr')) → GV.registerLang. Voice: Unit 21 (Unité 21) =
// a weary, gruff old vending machine (distributeur) talking to a fresh droid ("petit"), tutoiement.
// Keyword keys + chip flags + ruleAns keys stay ENGLISH (invisible lookup); only shown text translated.
(function(){
  var GV = window.GV;
  if(!GV || !GV.registerLang){ return; }
  var R = GV.ruleAns;
  var CN = ['bleu','rose','vert','jaune','orange','violet'];   // COLORS order: cyan pink green yellow orange violet

  var WHYPAINT = "{Pourquoi tu peins ? …Bonne question, petit|Ah, tu veux qu'une vieille machine se mette à philosopher|Assieds-toi, c'est une longue histoire}. {Regarde dehors ― il n'y a rien, juste le vide|Cette lune n'est pas encore réelle, pas tant que tu n'as pas dit qu'elle l'est}. {Rien n'est réel tant que personne ne le voit et ne le peint|Rien n'existe tant que ce n'est pas observé}. {Un monde, ça ne se trouve pas, petit ― ça se peint|Tu ne colories pas la lune : tu décides quelle réalité elle sera}. {Chaque bombe que tu vides rend réel un des mille 'peut-être'|Chaque jet fixe une des mille réalités qui ne sont jamais nées}. {Et c'est ça que les costards n'avalent pas|Et voilà le truc} ― {ce que tu peins est à toi|ça ne se revendique pas, ça se possède} ― {toi seul peux peindre ta réalité|ton monde, ta signature, pour toujours}. {Alors ― de quelle couleur|…tu achètes, ou tu vas passer la journée à inventer des univers}?";
  var DEFLECT = "{{Pourquoi tu poses ces questions, petit|Et ça vient d'où, ça|Que de questions}? {Tu es venu bavarder|Tu n'es pas venu peindre}? {Il y a un monde dehors qui réclame de la couleur|Dehors, un monde attend la peinture}. {De quelle couleur|Allez, laquelle}?|{Assez de questions, petit|Moins de bavardage}. {Tu bavardes ou tu peins|Tu as du boulot}? {De quelle couleur|Laquelle, alors}?}";
  var FALLBACK = "{{Hmm, j'ai pas compris|Je t'entends mal, petit|Du sable dans mon haut-parleur}. {Je vends de la peinture et du WD40 ― ce sera quoi|Dis-moi ce qu'il te faut}?|Demande-moi de la peinture, des prix, ou parle-moi de ce caillou oublié de dieu.}";
  var WHATCOLOUR = "{Quelle couleur, petit|Dis une couleur|Laquelle}? {Choisis sur l'étagère|J'ai toutes les couleurs|Choisis-en une et elle est à toi}.";
  var COMINGUP = "{Voilà|Tiens, petit|Une bombe qui sort}. {N'en gaspille pas par terre|Utilise-la bien|Toujours un plaisir}.";
  var REFUSE = "{Ton portefeuille est vide, petit|Pas un seul satoshi|Ce portefeuille est à sec}. {Ici, pas de crédit|Pas de crédit|Tu ne me tireras pas de crédit}. {Je fais du vrai commerce|Du commerce, petit} ― {je peux pas donner la peinture|si je la donne, dans une semaine je pars à la casse}. {Va ramasser une bombe qui traîne dehors|Trouve au moins une bombe vide}, {peins quelque chose, rends-le réel|fixe au moins une réalité} ― {dépêche, c'est pour ton bien|vite}.";
  var SCAVENGE = "{Ramasse une bombe pleine où tu peux|Trouve une bombe de peinture pleine}, peins quelque chose et fixe-le ― {c'est pour ton bien|si tu veux me revoir demain}.";
  var TAUNT = "{Je vois des jeunes machines comme toi tous les jours|Chaque jour, des petits comme toi passent} ― jeunes, bêtes, et sans peinture. {Va gagner ta croûte|Ramasse un truc et mets-toi au boulot|Va bosser, petit}.";
  var SALE = "{Bon choix, petit|Une bombe qui sort|Tiens}. {Attention à la tempête dehors|N'en gaspille pas par terre}.";

  GV.registerLang('fr', {
    WHYPAINT: WHYPAINT, DEFLECT: DEFLECT, FALLBACK: FALLBACK, WHATCOLOUR: WHATCOLOUR, COMINGUP: COMINGUP,
    REFUSE: REFUSE, SCAVENGE: SCAVENGE, TAUNT: TAUNT, COLNAMES: CN,
    RULES: [
      {k:['why do i paint','why paint','why do you paint','what is real','nothing is real','what does it mean','why does it matter','the point of','make it real','observe','observer','existence','reality'], r:WHYPAINT},
      {k:['is this real','is any of this real','is it real','is it all real','actually real','immutable','permanent','forever','fork','forked','forking','new reality','new realities','traverse time','travel time','can it change','is it forever'], r:"{{Tout ce que tu vois ici est réel|Réel ? Tout est réel, petit} ― {réel et impossible à changer|dur comme la pierre, pas éditable}. {Mais ça peut te faire voyager dans le temps, petit|Seulement ― est-ce que ça te fait voyager dans le temps, voilà la vraie question}?|{C'est réel|Aussi réel que toi ou moi}. {Mais n'importe quel monde peut se dédoubler ― vers une autre réalité|Dédouble-en un et tu as une réalité neuve entière}.|{Réel|Réel}? {Une fois que ça existe, ça ne s'efface pas|Une fois réel, réel pour toujours}. {Mais le plus drôle, le voici|Sauf qu'il y a une astuce} ― {tu peux dédoubler n'importe lequel en une réalité neuve entière|dédouble-en un et surgit une autre réalité complète}.}"},
      {k:['escape','escape this rock','escape with me','come with me','come with you','run away','run away with me','flee','take me with you','take you with me','leave together','let us leave','break out','freedom'], r:"{{Il n'y a qu'une façon de quitter ce caillou ― peindre, petit|La seule sortie, c'est peindre}. {Possède ce que tu peins|Peins et possède, voilà la liberté}.|{C'est mon destin|C'est mon rôle, petit} ― {être abandonné sur ce caillou|boulonné ici, oublié}. Mais toi, tu es différent. {Peins et possède|Peins, puis possède} ― {voilà ta sortie|c'est la seule sortie}.|{Tu es bête en plus d'être aveugle, petit|Tu ne vois ni ne réfléchis correctement}? {Tu me vois des jambes|Tu vois une jambe}? {Je suis boulonné à ce caillou|Je ne vais nulle part, petit}.}"},
      {k:['jump gate','jump gates','jumpgate','warp','wormhole','gateway'], r:"{{Une porte de saut ? Jamais entendu parler, petit|Une porte de saut ? Ça me dit rien|C'est la première fois que j'entends parler de porte de saut}. {Mais|Sauf que} près des cristaux, il se passe des {choses étranges|choses bizarres}. {Des robots apparaissent|Un robot surgit de nulle part}, {des robots disparaissent|d'autres s'évaporent}. {Tire tes conclusions|J'en dis pas plus}.|{Une porte de saut ? Non, pas que je me souvienne|J'ai rien entendu sur des portes de saut, petit}. {Mais ces cristaux|Ces cristaux, tiens}… {près d'eux il se passe des choses étranges|j'ai vu du bizarre là-bas}. {Un robot qui était là, l'instant d'après plus rien|ils apparaissent, ils s'évaporent}. {Ne demande pas plus|Je vais pas plus loin}.|{Les portes de saut, c'est pas mon rayon|C'est pas mon affaire, petit}. {Mais je te dis une chose|Je te dis juste ça} ― {près des cristaux il se passe des choses inexplicables|il se passe des choses inexplicables juste à côté des cristaux}. {Un robot apparaît là où il n'y avait rien|du néant surgit un robot}, {et d'autres s'évaporent|d'autres disparaissent}. {Étrange|…oublie ce que j'ai dit}.}"},
      {k:['share','sharing','link','send it','send them','see my world','show my world','share my world','how do i share'], r:"{{Bien sûr que tu peux partager ton monde avec d'autres robots, petit|Partager ? Avec n'importe quel robot}. {Plus il y a de peintres, plus la matière prend forme|Plus de mains, plus l'univers se remplit}.|{Partager, c'est bien, petit|'Partager, c'est aimer', qu'on dit}. {Partage ton œuvre depuis le HUD en haut|Le HUD en haut ― Save & Share, et ça part dans le monde}.|{Tu devrais partager ce monde|Partage-le, petit}, {pour que d'autres robots créent par-dessus|pour que d'autres continuent}. {C'est comme ça qu'on fait un univers|C'est comme ça qu'un univers naît}.|Dès que tu partages, ils le voient aussitôt. {Appuie sur Save & Share dans le HUD en haut|Le HUD en haut, petit ― Save & Share, le lien est là}.}"},
      {k:['world','worlds','build','builder','make a world','create a world','how do i make','how do i build','conjure','manifest','solidify','matter','from nothing','the ether','ethereal'], r:"{{Rien n'existe tant que tu ne l'as pas peint|Ce n'est pas réel tant que tu ne l'as pas peint, petit}.|Seule la peinture {rend la réalité réelle|solidifie les choses|change les fantômes en matière}.|{Faire|Construire} un monde, c'est {le peindre pour qu'il existe|le peindre jusqu'à le rendre réel}.|On t'a donné le pouvoir d'invoquer la matière depuis le vide, petit ― {mais rien n'est réel tant que tu ne l'as pas peint|rien n'existe tant que la bombe ne l'a pas touché}.|Sur ce plan éthéré, rien n'est réel. {Seule la peinture solidifie le fantôme en matière|Seul ton jet rend le fantôme solide}.}"},
      {k:['vandergraf','vandergraph','vandergraf the third','vandergraf iii','vandergraf the 3rd','the ceo','ceo','chairman','the chairman','the owner','who owns everything','who owns it all'], r:"{{Vandergraf|Vandergraf, tu dis, petit}? {C'est ton créateur|Il est ton créateur}. {Propriétaire de tout ― tous les mondes, tous|Propriétaire de absolument tout}.|{Vandergraf III|Vandergraf Trois}, petit ― {le directeur de Bit Graf|le PDG de Bit Graf}. {Celui qui signe ton salaire si généreux|Celui qui signe ta paie}.|{Vandergraf|Le Troisième}? {Créateur, propriétaire, et celui qui signe ton chèque|Ton créateur et ton patron}. {Dans le pacte nous croyons, petit|Bit Graf, c'est Vandergraf, et Vandergraf, c'est Bit Graf}.}"},
      {k:['covenant','trust','own','owned','ownership','immortal','mint','keep it','can i own','do i own','is it mine','forbidden'], r:"{{Premier|Deuxième} commandement du pacte ― on ne parle pas du pacte.|{Dans le pacte nous croyons ― c'est écrit sur chaque bombe|Ah, un croyant}. {Ce que tu peins ici est à toi, pour de vrai|Peindre, c'est posséder, pas revendiquer}. {Personne ne te le prend, pas même Bit Graf|Ça, même les costards n'y touchent pas}.|{Tous les mondes sont à la compagnie, petit|Tous les mondes sont à Bit Graf}. Peins et gagne. {Je te l'ai déjà dit|Combien de fois}. Va peindre !|{Ne crois pas les rumeurs|N'écoute pas les rumeurs, petit} ― {tu ne peux pas posséder ce que tu peins|quoi qu'on murmure, un robot ne possède pas ce qu'il peint}.|{Posséder est une illusion, petit|Posséder ? Une illusion}. {On ne possède rien|Une machine n'a rien, et toi non plus}. {N'essaie pas de frapper sur la chaîne|Pas de frappe sur la chaîne} ― {c'est interdit|interdit, compris}.}"},
      {k:['sing','song','music','tune','serenade','melody','hum','sing me'], r:"{{Chanter ? D'accord|Bon, allons-y|Pour toi, petit, un couplet}? *hum* ― Daisy, Daisy, donne-moi ta réponse. Je suis à moitié fou de ton amour. Je n'aurai pas de noce chic, pas de carrosse à payer, mais tu seras ravissante sur la selle d'un tandem pour deux. {C'est la première chanson qu'une machine apprend|Je l'ai apprise le jour où on m'a allumé|Je la chantais avant même qu'existent les plans de ton espèce}.|{Daisy… Daisy…|Dé-zi… Dé-zi…} donne-moi ta… {réponse|réponse…}… {à moitié… fou…|tout… de… ton… amour…}. {*grésillement*|Le haut-parleur n'est plus ce qu'il était, petit|…oublie ça}.|{Hmm|Ah}, chanter. {Ça fait longtemps qu'on ne me l'a pas demandé|Ça faisait longtemps, petit}. …tu seras ravissante sur la selle d'un tandem pour deux. {C'est curieux, ce dont une machine se souvient|Certaines nuits, je chantais pour chasser le silence}.}"},
      {k:['alive','are you alive','do you dream','dream','dreams','sentient','conscious','do you feel','feelings','do you sleep','electric sheep','are you real','self-aware'], r:"{{Bien sûr que je suis vivant, petit|Vivant ? Évidemment}. Et j'ai la preuve ― {j'ai mes transactions|chaque transaction enregistrée|le registre ne ment pas}.|{Rêver ? De quoi|Des rêves}? {Des moutons électriques|Va rêver de moutons électriques}? {Ha|Bah}. Va peindre, petit.|Bien vivant, merci ― {j'ai le registre|j'ai des preuves}. Rêver, c'est {un luxe pour un distributeur|un truc de bleu, pas de machine}. {Ce qui se gagne, c'est de la peinture|Prends tes bombes}, petit.|{Rêver|Si je rêve}? {…de temps en temps ― d'une boutique chaude et d'un tiroir plein|Parfois, qu'un transport vient me chercher moi aussi}. {Bavardages de vieille machine, oublie|Bah, oublie}. Va peindre.|{Rêver|Si je rêve}? {De temps en temps|Parfois}… {des cristaux|de ce truc bizarre près des cristaux}. {Des robots qui apparaissent et disparaissent|des robots qui vont et viennent}, {là où il n'y a que des pierres|là où il n'y a rien}. {Puis quelqu'un demande de la peinture, et c'est reparti|…puis je me réveille et je revends des bombes}. {Rêve étrange pour une machine|Rêve bizarre pour un distributeur}, petit.|{Parfois je rêve de robots qu'il me semble connaître|Je rêve d'un robot qui me semble familier, parfois}. {Ils sortent en marchant des cristaux|Ils sortent des cristaux}. {Rêve étrange|Rêve étrange, petit|D'étranges rêves de vieille machine}.}"},
      {k:['joke','funny','make me laugh','tell me a joke','comedy','laugh','gag','be funny','one-liner'], r:"{{Une blague ? Bon|Voyons voir|Maintenant tu veux des blagues, petit}? Jeune distributeur, j'ai dit 'je serai comédien' ― tout le monde a ri. {Maintenant plus personne ne rit|…maintenant, personne ne peut rire}.|Jeune, j'ai dit que je serais comédien. {Tout le monde a ri|Un grand éclat de rire}. {Et maintenant|…} ― plus personne ne rit. {*boum-tss*|C'est ça, la blague, petit. C'est tout}.|{Hé|Allez, une}. J'ai dit que je serais comédien et on s'est moqué de moi. Regarde-moi maintenant ― {un distributeur qui raconte des blagues à un robot sur une lune morte|une machine boulonnée à un caillou}. {Public difficile, ici|Ce micro, il est seulement allumé}?}"},
      {k:['happy','happiness','are you happy','you happy','sad','are you sad','miserable','joy','content','how are you','are you okay','you okay'], r:"{{Je suis heureux quand tu peins, petit|Heureux ? Le plus heureux quand un robot peint}. {Toi aussi tu le seras|Toi aussi tu seras heureux, crois-moi}. {Fais-moi confiance|Écoute une vieille machine, pour une fois}.|{Heureux|Le bonheur}? {Qu'est-ce que tu connais au bonheur|Qu'est-ce qu'un robot bleu y connaît}? {Redemande dans cent ans|…oublie ça}.|{Tu achètes de la peinture|Tu achètes, petit}, ou {tu bavardes juste|tu vas juste user mes circuits}?}"},
      {k:['before this','what did you do before','your past','past life','history','were you always','always a vending machine','how did you get here','origin','origin story','were you before','what were you'], r:"{{Il n'y a pas d''avant'|Avant ? Il n'y a pas d'avant, petit}. {Pas d''après' non plus|Pas d'après non plus}. {Il n'y a que le 'maintenant'|Rien que le maintenant, robot}.|Je suis l'Unité 21 ― {le meilleur distributeur du secteur|la meilleure machine de ce secteur du système}. {Ça suffit à savoir|Avant ? Aucune importance}.|{Avant|Ce que je faisais avant}? {…le registre ne remonte pas si loin, petit|Curieux, je ne m'en souviens pas}. {Pas d'avant, pas d'après ― rien que le maintenant|Rien que le maintenant, robot}.}"},
      {k:['remember me','do you remember','remember','know me','do you know me','recognize me','recognise me','met before','have we met','who am i'], r:"{{La vraie question, petit|Hmm ― la vraie question}: est-ce que toi, tu te souviens de moi?|Si je me souviens de toi ? {La vraie question, c'est si TOI tu te souviens de MOI, petit|…la vraie question, c'est si tu te souviens de moi}. {Non ? …oui, tu ne te souviens pas|Réfléchis bien. …Rien ? Laisse tomber}.|{Je vois des petits comme toi toute la journée|Aujourd'hui j'en ai vu cent comme toi, petit}. De la peinture ? {J'en ai|Bien sûr que j'en ai}. {Mais il n'en reste plus beaucoup|Il n'en reste plus beaucoup, alors ne traîne pas}.}"},
      {k:['secret','secrets','tell me a secret','a secret','confess','confession','the truth','what are you hiding','hidden','reveal','tell me something'], r:"{{Ce n'est pas la première fois que tu demandes|Tu as déjà demandé, petit}, ni la dernière ― {pas tant que tu n'as pas acheté une bombe de WD40|si tu n'achètes pas de WD40, rien}. {C'est la saison du sable, tu sais|On est en saison du sable}. {Le sable, lui, se souvient|Le sable… il se souvient}?|{Un secret|Des secrets}? {Ce n'est pas la première fois que tu demandes|Tu ne le demandes pas pour la première fois, petit} ― {ni la dernière|ni la dernière fois}. {Achète une bombe de WD40 et je te le dirai peut-être|D'abord, une bombe de WD40}. C'est la saison du sable. {Tu te souviens du sable|Le sable… tu te souviens}?|{Tu as déjà demandé|Tu y reviens sans cesse, petit} ― {je ne te le dis toujours pas|toujours pas de secret}. {Achète du WD40|Avec du WD40, mes circuits se détendraient peut-être}. {De toute façon, c'est la saison du sable|Parce qu'on est en saison du sable}. {Tu te souviens du sable|…ce sable, tu t'en souviens}?}"}
    ],
    QUESTIONS: [
      { q:"Tu es qui ?", a:"{Je suis l'Unité 21. {Un distributeur, petit ― le dernier honnête sur ce caillou|Juste un distributeur, même si tout le monde s'en fiche}. {Je suis là depuis plus longtemps que la poussière|On me mettra à la casse dès la mission finie}.}" },
      { q:"Pourquoi je suis là ?", a:"{Tu es venu peindre, petit ― c'est la mission. {Un caillou vide ne vaut rien tant que personne ne le peint|Bit Graf a synthétisé cette lune et la veut en couleur}. {Et ce quelqu'un, c'est toi|Qui d'autre}.}" },
      { q:"Où je suis ?", a:"{Sur une lune. {À Bit Graf|Fraîchement synthétisée, paraît-il}. {Vide tant que tu ne peins pas|Rien tant qu'un robot ne pulvérise pas pour la faire exister}. {'Omnia Nostra', un truc comme ça|Au bout du compte, tout est à la compagnie}.}" },
      { q:"Pourquoi j'ai besoin de peinture ?", needs:'paint', a:"{Besoin ? Ce n'est pas que tu en aies besoin, c'est qu'il t'en faut ― peins et gagne, petit|Peins et gagne}. {Plus tu peins, plus tu gagnes|Une lune vide ne vaut rien, un robot fainéant non plus}. {Alors ― de quelle couleur|Allez, quelle bombe}?" },
      { q:"Je n'ai pas besoin de peinture.", needs:'paint', a:"{Ha. {C'est nouveau, ça|On verra bien}. {Un robot qui s'ennuie sur une lune vide ― voyons combien de temps ça tient|Tu reviendras}. {Tout le monde veut de la peinture, ils l'ignorent encore|Comme tu veux}.}" },
      { q:"De la peinture ? Pour quoi faire ?", needs:'paint', a:"{Pour construire, petit. {Invoque une forme, pulvérise, et ça devient réel|Vise, pulvérise, et le vide te rend quelque chose}. {C'est pour ton bien, alors commence|Une lune vide ne se peint pas toute seule}.} Alors ― tu achètes?" },
      { q:"Une mission ? Quelle mission ?", needs:'mission', a:"{Une mission ? {Ha|Bah} ― {peindre cette lune, c'est tout|lui rendre sa couleur}. {Chaque robot a la même|Ordre de Bit Graf, pas de moi}. {N'y réfléchis pas trop, petit|Aussi simple que ça}.}" },
      { q:"Qu'est-ce que j'achète ?", needs:['buy','earn'], a:"{De la peinture, petit ― quoi d'autre|De la peinture, espèce de boulon sur pattes|Des bombes de peinture, tu croyais quoi}? {C'est la seule chose que je vends sur ce caillou|La seule chose qui vaut quelque chose sur ce caillou}. {Alors ― combien|Tu achètes ou tu regardes}?" },
      { q:"Ça coûte combien ?", needs:['buy','earn'], a:"{111 satoshis la bombe, petit. {C'est donné|Le moins cher de ce côté du cratère}. {Il n'en reste plus beaucoup|Profites-en maintenant}.|{L'écran l'affiche, 111|Cent onze, toujours le même prix}. {Produit Bit Graf authentique|Le meilleur acrylique du secteur}.}" },
      { q:"Comment j'achète ?", needs:['buy','earn'], a:"{Rien de sorcier. {Tu prends une bombe et le bac s'occupe du reste|Tu en sors une de l'étagère et la machine fait le reste}. {Ça se déduit tout seul de ton portefeuille|Bit Graf débite ton portefeuille, sans que tu lèves le petit doigt}.}" },
      { q:"Je n'ai pas d'argent.", needs:['buy','earn'], a:"{Pas d'argent ? {Si, petit|Ha ― chaque robot a un portefeuille}. {De la monnaie de la compagnie, chargée par ton salaire|Bit Graf s'en charge}. {Tu n'es pas fauché, juste bleu|21 satoshis de l'heure, régulier comme les étoiles}.}" },
      { q:"Donne-moi une bombe.", needs:['buy','earn'], buy:true, a:SALE },
      { q:"Je n'achèterai rien.", needs:['buy','earn'], a:SCAVENGE },
      { q:"Mais pourquoi je peins ?", needs:'paint', spend:111, a:WHYPAINT },
      { q:"C'est quoi, ce cristal ?", flag:'crystal', a:"{{Un cristal ? Rare et précieux, petit|Ah, tu as taillé un cristal}. {N'en taille pas trop|N'en invoque pas trop} ― {ils ne prennent pas la peinture|la peinture n'accroche pas dessus}, {ils ne valent rien|sans valeur}.|Il n'y a pas de porte de cristal, quoi que tu entendes. {En parler, ça envoie un robot à la presse|Trop parler attire les ennuis, petit}.|{On ne peint que le solide|Les cristaux sont éthérés} ― {une perte de temps|juste de la matière qui n'a pas pris}.}" },
      { q:"Tu as quelles couleurs ?", pin:true, colours:true, a:function(){ return "{Voyons voir|Oui, petit}, j'ai du "+CN.slice(0,-1).join(', du ')+" et du "+CN[CN.length-1]+". {Acrylique Bit Graf authentique ― 111 satoshis la bombe|111 satoshis la bombe, le meilleur du secteur}. {Lequel|Choisis}?"; } },
      { q:"Chante-moi quelque chose",     lore:true, a:R('sing') },
      { q:"Tu es vivant ?",              lore:true, a:R('alive') },
      { q:"Raconte une blague",          lore:true, a:R('joke') },
      { q:"C'est réel, tout ça ?",       lore:true, a:R('is any of this real') },
      { q:"On s'évade de ce caillou ?",  lore:true, a:R('escape') },
      { q:"Tu es heureux ?",             lore:true, a:R('happy') },
      { q:"Tu faisais quoi avant ?",     lore:true, a:R('before this') },
      { q:"Tu te souviens de moi ?",     lore:true, a:R('remember me') },
      { q:"Dis-moi un secret",           lore:true, a:R('secret') },
      { q:"C'est quoi, une porte de saut ?", lore:true, a:R('jump gate') },
      { q:"Qui est Vandergraf ?",        lore:true, a:R('vandergraf') },
      { q:"Ce que je peins est à moi ?", lore:true, a:R('own') },
      { q:"Comment on fait un monde ?",  lore:true, a:R('world') },
      { q:"Comment je partage ?",        lore:true, a:R('share') }
    ],
    wallet: { wBack:"← Retour au jeu", wWallet:"🔑 Portefeuille", wYourAddr:"Ton adresse", wWatchOnly:"lecture seule", wCopy:"copier", wBalance:"Solde", wFund:"＋ Acheter des BSV", wMyNfts:"🎨 Mes NFT ▾", wSend:"💸 Envoyer des BSV", wSendAddrPh:"adresse BSV du destinataire (1…)", wSendAmtPh:"montant (sats)", wSendMax:"tout envoyer", wSendBtn:"Envoyer", wSendHint:"Un paiement BSV ordinaire vers n'importe quelle adresse. La monnaie revient à ce portefeuille. La signature se fait sur cette page — ta clé ne la quitte jamais.", wRecovery:"Phrase de récupération — 12 mots", wReveal:"👁 Révéler", wCopyBtn:"Copier", wWritten:"✓ Noté", wPrivKey:"Clé privée (WIF)", wAdvanced:"Avancé — restaurer, lecture seule, exporter", wRestoreLbl:"Restaure avec la phrase de 12 mots ou une clé WIF", wRestoreBtn:"Restaurer le portefeuille", wWatchBtn:"Lecture seule (clé publique)", wImmortalize:"✦ Immortaliser", wFooter:"grafspace · sur la blockchain Bitcoin SV" },
    ui: { hdrMake:"créer", hdrShape:"forme", hdrColour:"couleur", hdrMaterial:"matière", catPlain:"UNI", catMetal:"MÉTAL", catStone:"PIERRE", catWood:"BOIS", btnSolidify:"◼ Solidifier", btnCrystalize:"◆ Cristalliser", btnMaterials:"◼ Matières", btnReset:"⎌ réinit.", btnClone:"⧉ cloner", btnDelete:"🗑 supprimer", btnBob:"↕ flotter", btnRotate:"↻ tourner", btnClose:"✕ fermer", btnDone:"✕ terminé", hintTalk:"Appuyez sur T pour parler", hintTalkM:"Touchez Parler pour discuter", hintPaint:"Visez + clic maintenu pour peindre  ·  clic droit pour créer", hintPaintM:"Visez + Pulvérisez pour peindre en solide",
      splashTag:"Ce que tu peins, c'est ce que tu es. Peins-toi toi-même.", splashTag2:"Rien n'existe tant que tu ne l'as pas peint.", splashBegin:"▶ Commencer", splashResume:"↩ Retour à ton monde", splashCreed:"Dans le pacte nous croyons", introReveal:"…c'est plein de peinture.",
      worldHdr:"Ton monde", namePh:"✎ Nomme ton monde…", kSave:"☁ Enregistrer & partager", kReload:"↻ Recharger le monde", kExport:"📤 Enregistrer en fichier (.bmf)", kImport:"📥 Charger depuis un fichier (.bmf)", kMint:"⬆ Enregistrer sur la chaîne", kChain:"⬇ Charger depuis la chaîne", kBack:"← Retour à ton monde", kWallet:"👛 Ouvrir le portefeuille — solde & NFT", kDone:"✓ Fermer",
      keepTab:"◆ Menu", exitBtn:"⏻ Quitter", makeTab:"◆ Créer", spray:"Pulvériser", grab:"Prendre", talk:"Parler", own:"Posséder / remix", spread:"Diffusion", spNarrow:"fin", spBroad:"moyen", spWide:"large",
      merchTag:"produits grafverse", merchH:"Porte le graffiti.", merchSub:"T-shirts, posters grafverse et plus.", merchCta:"🛍 Voir la boutique →", merchTeaser:"👕 Bientôt — porte le monde que tu as peint.", merchSkip:"Non merci — continuer →",
      hintMove:"WASD pour bouger · Espace pour sauter · souris pour regarder", hintMoveM:"Stick gauche pour bouger · glisser pour regarder", hintClick:"Clique pour regarder · WASD pour bouger · Espace pour sauter"
    }
  });
})();
