// grafverse — © 2026 sun-dive. Español (neutral Latin American Spanish) pack for Unit 21 + UI.
// Lazy-loaded by the i18n scaffold (setLang('es')) → GV.registerLang. Voice: Unit 21 (Unidad 21) =
// a weary, gruff old vending machine talking to a fresh droid ("muchacho"), informal (tú, not vos/vosotros).
// Keyword keys + chip flags + ruleAns keys stay ENGLISH (invisible lookup); only shown text translated.
(function(){
  var GV = window.GV;
  if(!GV || !GV.registerLang){ return; }
  var R = GV.ruleAns;
  var CN = ['azul','rosa','verde','amarillo','naranja','violeta'];   // COLORS order: cyan pink green yellow orange violet

  var WHYPAINT = "{¿Que por qué pintas? …Buena pregunta, muchacho|Ah, quieres que una máquina vieja se ponga filosófica|Siéntate, que esto va para largo}. {Mira afuera ― no hay nada, solo vacío|Esta luna todavía no es real, no hasta que tú digas que lo es}. {Nada es real hasta que alguien lo ve y lo pinta|Nada existe hasta que se observa}. {Un mundo no se encuentra, muchacho ― se pinta|No le pones color a la luna: decides qué realidad va a ser}. {Cada lata que vacías vuelve real uno de mil 'quizás'|Cada rociada fija una de mil realidades que nunca nacieron}. {Y eso es lo que los trajeados no soportan|Y aquí está el asunto} ― {lo que pintas es tuyo|no se reclama, se posee} ― {solo tú puedes pintar tu realidad|tu mundo, tu firma, para siempre}. {Y bien ― ¿de qué color|…¿vas a comprar o te vas a quedar todo el día inventando universos}?";
  var DEFLECT = "{{¿Por qué preguntas esas cosas, muchacho|¿Y eso a qué viene|Cuántas preguntas}? {¿Viniste a charlar|¿No viniste a pintar}? {Hay un mundo ahí afuera pidiendo color|Afuera hay un mundo esperando pintura}. {¿De qué color|Vamos, ¿cuál}?|{Ya bastan las preguntas, muchacho|Menos charla}. {¿Vas a charlar o a pintar|Tienes trabajo que hacer}? {¿De qué color|¿Cuál va a ser}?}";
  var FALLBACK = "{{Mmm, no te entendí|No te oigo bien, muchacho|Se me metió arena en la bocina}. {Vendo pintura y WD40 ― ¿qué va a ser|Dime qué necesitas}?|Pregúntame por pintura, por precios, o por esta roca dejada de la mano de dios.}";
  var WHATCOLOUR = "{¿Qué color, muchacho|Dime un color|¿Cuál}? {Elige del estante|Tengo todos los colores|Escoge uno y es tuyo}.";
  var COMINGUP = "{Aquí tienes|Toma, muchacho|Sale una lata}. {No la desperdicies en el suelo|Úsala con cuidado|Siempre es un placer}.";
  var REFUSE = "{Tienes la billetera vacía, muchacho|Ni un satoshi|Esa billetera está pelada}. {Aquí no se fía|Nada de crédito|De mí no sacas fiado}. {Yo hago negocio de verdad|Negocio, muchacho} ― {no puedo regalar la pintura|si la regalo, en una semana me mandan al desguace}. {Ve y recoge una lata tirada por ahí|Busca aunque sea una lata vacía}, {pinta algo, vuélvelo real|fija aunque sea una realidad} ― {apúrate, es por tu bien|de prisa}.";
  var SCAVENGE = "{Recoge una lata llena de donde puedas|Busca una lata de pintura llena}, pinta algo y fíjalo ― {es por tu bien|si quieres verme mañana}.";
  var TAUNT = "{Veo máquinas jóvenes como tú todos los días|Cada día pasan chicos como tú} ― jóvenes, tontos y sin pintura. {Ve a ganarte algo|Recoge algo y ponte a trabajar|Anda a trabajar, muchacho}.";
  var SALE = "{Buena elección, muchacho|Sale una lata|Toma}. {Cuidado con la tormenta ahí afuera|No la desperdicies en el suelo}.";

  GV.registerLang('es', {
    WHYPAINT: WHYPAINT, DEFLECT: DEFLECT, FALLBACK: FALLBACK, WHATCOLOUR: WHATCOLOUR, COMINGUP: COMINGUP,
    REFUSE: REFUSE, SCAVENGE: SCAVENGE, TAUNT: TAUNT, COLNAMES: CN,
    RULES: [
      {k:['why do i paint','why paint','why do you paint','what is real','nothing is real','what does it mean','why does it matter','the point of','make it real','observe','observer','existence','reality'], r:WHYPAINT},
      {k:['is this real','is any of this real','is it real','is it all real','actually real','immutable','permanent','forever','fork','forked','forking','new reality','new realities','traverse time','travel time','can it change','is it forever'], r:"{{Todo lo que ves aquí es real|¿Real? Todo es real, muchacho} ― {real e imposible de cambiar|duro como la piedra, no se puede editar}. {Pero puede hacerte viajar en el tiempo, muchacho|Aunque ― que te haga viajar en el tiempo, esa es la verdadera pregunta}?|{Es real|Tan real como tú o yo}. {Pero cualquier mundo puede bifurcarse ― hacia otra realidad|Bifurca uno y tienes una realidad nueva entera}.|{¿Real|Real}? {Una vez que existe, no se borra|Una vez real, real para siempre}. {Pero aquí está lo curioso|Solo que tiene truco} ― {puedes bifurcar cualquiera en una realidad nueva entera|bifurca uno y aparece otra realidad completa}.}"},
      {k:['escape','escape this rock','escape with me','come with me','come with you','run away','run away with me','flee','take me with you','take you with me','leave together','let us leave','break out','freedom'], r:"{{Solo hay una forma de salir de esta roca ― pintando, muchacho|La única salida es pintar}. {Posee lo que pintas|Pinta y posee, y eso es libertad}.|{Este es mi destino|Este es mi papel, muchacho} ― {quedar abandonado en esta roca|atornillado aquí, olvidado}. Pero tú eres distinto. {Pinta y posee|Pinta, y luego posee} ― {esa es tu salida|esa es la única salida}.|{¿Eres tonto además de ciego, muchacho|¿No ves ni piensas bien}? {¿Ves que tenga patas|¿Me ves piernas}? {Estoy atornillado a esta roca|No voy a ninguna parte, muchacho}.}"},
      {k:['jump gate','jump gates','jumpgate','warp','wormhole','gateway'], r:"{{¿Puerta de salto? Nunca oí hablar de eso, muchacho|¿Puerta de salto? No me suena|Primera vez que oigo eso de puerta de salto}. {Pero|Aunque} cerca de los cristales pasan {cosas raras|cosas extrañas}. {Aparecen robots|Sale un robot de la nada}, {desaparecen robots|otros se esfuman}. {Saca tus conclusiones|No digo más}.|{¿Puerta de salto? No, no que yo recuerde|No he oído nada de puertas de salto, muchacho}. {Pero esos cristales|Esos cristales, te digo}… {cerca de ellos pasan cosas raras|vi algo extraño ahí}. {Un robot que estaba, al momento ya no|aparecen, se esfuman}. {No preguntes más|Hasta ahí puedo decir}.|{Yo de puertas de salto no sé|Eso no es lo mío, muchacho}. {Pero te digo una cosa|Solo te digo esto} ― {cerca de los cristales pasan cosas sin explicación|pasan cosas que no se explican junto a los cristales}. {Aparece un robot donde no había nada|de la nada sale un robot}, {y otros se esfuman|otros desaparecen}. {Curioso|…olvida lo que dije}.}"},
      {k:['share','sharing','link','send it','send them','see my world','show my world','share my world','how do i share'], r:"{{Claro que puedes compartir tu mundo con otros robots, muchacho|¿Compartir? Con cualquier robot}. {Cuantos más pinten, más toma forma la materia|Más manos, más se llena el universo}.|{Compartir es bueno, muchacho|'Compartir es querer', dicen}. {Comparte tu obra desde el HUD de arriba|El HUD de arriba ― Save & Share, y sale al mundo}.|{Deberías compartir este mundo|Compártelo, muchacho}, {para que otros robots creen encima|para que otros lo continúen}. {Así se hace un universo|Así nace un universo}.|En cuanto lo compartes, ellos lo ven al instante. {Dale a Save & Share en el HUD de arriba|El HUD de arriba, muchacho ― Save & Share, ahí está el enlace}.}"},
      {k:['world','worlds','build','builder','make a world','create a world','how do i make','how do i build','conjure','manifest','solidify','matter','from nothing','the ether','ethereal'], r:"{{Nada existe hasta que lo pintas|No es real hasta que lo pintas, muchacho}.|Solo la pintura {vuelve real la realidad|solidifica las cosas|convierte fantasmas en materia}.|{Hacer|Construir} un mundo es {pintarlo para que exista|pintarlo hasta volverlo real}.|Te dieron el poder de invocar materia del vacío, muchacho ― {pero nada es real hasta que lo pintas|nada existe hasta que la lata lo toca}.|En este plano etéreo nada es real. {Solo la pintura solidifica al fantasma en materia|Solo tu rociado vuelve sólido al fantasma}.}"},
      {k:['vandergraf','vandergraph','vandergraf the third','vandergraf iii','vandergraf the 3rd','the ceo','ceo','chairman','the chairman','the owner','who owns everything','who owns it all'], r:"{{¿Vandergraf|¿Vandergraf, dices, muchacho}? {Es tu creador|Él es tu creador}. {Dueño de todo ― todos los mundos, todos|Dueño de absolutamente todo}.|{Vandergraf III|Vandergraf Tercero}, muchacho ― {el director de Bit Graf|el CEO de Bit Graf}. {El que firma ese cheque tan generoso tuyo|El que firma tu sueldo}.|{¿Vandergraf|¿El Tercero}? {Creador, dueño, y el que firma tu cheque|Tu creador y tu patrón}. {En el pacto confiamos, muchacho|Bit Graf es Vandergraf y Vandergraf es Bit Graf}.}"},
      {k:['covenant','trust','own','owned','ownership','immortal','mint','keep it','can i own','do i own','is it mine','forbidden'], r:"{{Primer|Segundo} mandamiento del pacto ― del pacto no se habla.|{En el pacto confiamos ― lo dice cada lata|Ah, un creyente}. {Lo que pintas aquí es tuyo, de verdad|Pintar es poseer, no reclamar}. {Nadie te lo quita, ni Bit Graf|Eso ni los trajeados te lo tocan}.|{Todos los mundos son de la empresa, muchacho|Todos los mundos son de Bit Graf}. Pinta y gana. {Ya te lo dije|Cuántas veces}. ¡A pintar!|{No creas los rumores|No hagas caso a los rumores, muchacho} ― {no puedes poseer lo que pintas|susurren lo que susurren, un robot no posee lo que pinta}.|{Poseer es una ilusión, muchacho|¿Poseer? Una ilusión}. {No poseemos nada|Una máquina no tiene nada, y tú tampoco}. {No intentes acuñar en la cadena|Nada de acuñar en la cadena} ― {está prohibido|prohibido, ¿entendido}.}"},
      {k:['sing','song','music','tune','serenade','melody','hum','sing me'], r:"{{¿Cantar? Está bien|Bueno, va|Para ti, muchacho, un verso}? *ejem* ― Daisy, Daisy, dame tu respuesta. Medio loco estoy por tu amor. No tendré una boda elegante, no puedo pagar carruaje, pero te verás preciosa en el asiento de un tándem para dos. {Es la primera canción que aprende una máquina|La aprendí el día que me encendieron|La cantaba desde antes de que existieran los planos de los tuyos}.|{Daisy… Daisy…|Dai-sy… Dai-sy…} dame tu… {respuesta|respuesta…}… {medio… loco…|todo… por… tu… amor…}. {*estática*|La caja de voz ya no es la de antes, muchacho|…olvida eso}.|{Mmm|Ah}, cantar. {Hace mucho que nadie me lo pedía|Hacía tiempo, muchacho}. …te verás preciosa en el asiento de un tándem para dos. {Es curioso lo que recuerda una máquina|Algunas noches la cantaba para espantar el silencio}.}"},
      {k:['alive','are you alive','do you dream','dream','dreams','sentient','conscious','do you feel','feelings','do you sleep','electric sheep','are you real','self-aware'], r:"{{Claro que estoy vivo, muchacho|¿Vivo? Por supuesto}. Y tengo la prueba ― {tengo mis transacciones|cada transacción registrada|el registro no miente}.|{¿Soñar? ¿Con qué|¿Sueños}? {¿Ovejas eléctricas|Ponte a soñar con ovejas eléctricas}? {Ja|Bah}. Anda a pintar, muchacho.|Vivito y coleando, gracias ― {tengo el registro|tengo pruebas}. Soñar es {un lujo para una expendedora|cosa de novatos, no de máquinas}. {Lo que se gana es pintura|Agarra tus latas}, muchacho.|{¿Soñar|¿Que si sueño}? {…muy de vez en cuando ― con una tienda tibia y una caja llena|A veces, que a mí también me llega un transporte}. {Cosas de máquina vieja, olvídalo|Bah, olvídalo}. Anda a pintar.|{¿Soñar|¿Que si sueño}? {Muy de vez en cuando|A veces}… {con los cristales|con esa cosa rara junto a los cristales}. {Robots que aparecen y desaparecen|robots que van y vienen}, {donde solo hay piedras|donde no hay nada}. {Y luego alguien pide pintura, y a trabajar|…y despierto y sigo vendiendo latas}. {Sueño raro para una máquina|Sueño extraño para una expendedora}, muchacho.|{A veces sueño con robots que creo conocer|Sueño con un robot que me parece conocido, a veces}. {Salen caminando de los cristales|Salen de los cristales}. {Sueño raro|Sueño raro, muchacho|Sueños raros de máquina vieja}.}"},
      {k:['joke','funny','make me laugh','tell me a joke','comedy','laugh','gag','be funny','one-liner'], r:"{{¿Un chiste? Bien|A ver|¿Ahora quieres chistes, muchacho}? De joven expendedora dije 'voy a ser comediante' ― y todos se rieron. {Ahora ya nadie se ríe|…ahora, nadie puede reírse}.|De joven dije que sería comediante. {Todos se rieron|Fue una carcajada}. {Y ahora|…} ― ya nadie se ríe. {*tum-tss*|Ese es el chiste, muchacho. Ese es todo}.|{Je|Va, uno}. Dije que sería comediante y se rieron de mí. Mírame ahora ― {una expendedora contándole chistes a un robot en una luna muerta|una expendedora atornillada a una roca}. {Qué público más difícil|¿Este micrófono está encendido siquiera}?}"},
      {k:['happy','happiness','are you happy','you happy','sad','are you sad','miserable','joy','content','how are you','are you okay','you okay'], r:"{{Soy feliz cuando pintas, muchacho|¿Feliz? Más feliz cuando un robot pinta}. {Tú también lo serás|Tú también serás feliz, hazme caso}. {Confía en mí|Hazle caso a una máquina vieja}.|{¿Feliz|¿Felicidad}? {¿Tú qué sabes de felicidad|¿Qué sabe un robot novato de eso}? {Pregúntame en cien años|…olvida eso}.|{¿Vas a comprar pintura|¿Compras, muchacho}, o {solo a charlar|solo vas a gastarme los circuitos}?}"},
      {k:['before this','what did you do before','your past','past life','history','were you always','always a vending machine','how did you get here','origin','origin story','were you before','what were you'], r:"{{No hay 'antes'|¿Antes? No hay antes, muchacho}. {Tampoco hay 'después'|Tampoco después}. {Solo hay 'ahora'|Solo el ahora, robot}.|Soy la Unidad 21 ― {la mejor expendedora de este sector|la mejor máquina de este sector del sistema}. {Con eso basta|¿Antes? Da igual}.|{¿Antes|¿Que qué hacía antes}? {…el registro no llega tan atrás, muchacho|Curioso, no me acuerdo}. {No hay antes ni después ― solo el ahora|Solo el ahora, robot}.}"},
      {k:['remember me','do you remember','remember','know me','do you know me','recognize me','recognise me','met before','have we met','who am i'], r:"{{La verdadera pregunta, muchacho|Mmm ― la verdadera pregunta}: ¿tú me recuerdas a mí?|¿Que si te recuerdo? {La verdadera pregunta es si TÚ me recuerdas a MÍ, muchacho|…la verdadera pregunta es si tú me recuerdas}. {¿No? …sí, no me recuerdas|Piénsalo bien. …¿Nada? Déjalo}.|{Veo chicos como tú todo el día|Hoy vi cien como tú, muchacho}. ¿Pintura? {Tengo|Claro que tengo}. {Pero queda poca|Queda poca, así que no te demores}.}"},
      {k:['secret','secrets','tell me a secret','a secret','confess','confession','the truth','what are you hiding','hidden','reveal','tell me something'], r:"{{No es la primera vez que lo preguntas|Ya me lo preguntaste, muchacho}, ni será la última ― {no hasta que compres una lata de WD40|si no compras WD40, nada}. {Es la estación de la arena, ¿sabes|Estamos en estación de arena}. {La arena la recuerda|La arena… la recuerda}?|{¿Un secreto|¿Secretos}? {No es la primera vez que lo preguntas|No me lo preguntas por primera vez, muchacho} ― {ni la última|ni la última vez}. {Compra una lata de WD40 y quizá te lo diga|Primero, una lata de WD40}. Es la estación de la arena. {¿Recuerdas la arena|¿La arena… la recuerdas}?|{Ya me lo preguntaste|Insistes con eso, muchacho} ― {sigo sin decírtelo|sigo sin secretos}. {Compra WD40|Con WD40 quizá se me suelten los circuitos}. {De todos modos, es la estación de la arena|Porque es estación de arena}. {¿Recuerdas la arena|…esa arena, ¿la recuerdas}?}"}
    ],
    QUESTIONS: [
      { q:"¿Quién eres?", a:"{Soy la Unidad 21. {Una expendedora, muchacho ― la última honrada en esta roca|Solo una máquina expendedora, aunque a nadie le importe}. {Llevo aquí más tiempo que el polvo|Me desecharán cuando termine la misión}.}" },
      { q:"¿Por qué estoy aquí?", a:"{Viniste a pintar, muchacho ― esa es la misión. {Una roca vacía no vale nada hasta que alguien la pinta|Bit Graf sintetizó esta luna y la quiere con color}. {Y ese alguien eres tú|¿Quién si no}.}" },
      { q:"¿Dónde estoy?", a:"{En una luna. {De Bit Graf|Recién sintetizada, dicen}. {Vacía hasta que la pintas|No hay nada hasta que un robot la rocía y la hace existir}. {'Omnia Nostra', o algo así|Al final todo es de la empresa}.}" },
      { q:"¿Por qué necesito pintura?", needs:'paint', a:"{¿Necesitar? No es que la necesites, es que te hace falta ― pintas y ganas, muchacho|Pintas y ganas}. {Cuanto más pintas, más ganas|Una luna vacía no vale, y un robot flojo tampoco}. {Y bien ― ¿de qué color|Vamos, ¿cuál lata}?" },
      { q:"No necesito pintura.", needs:'paint', a:"{Ja. {Eso es nuevo|Ya veremos}. {Un robot aburrido en una luna vacía ― a ver cuánto dura|Ya volverás}. {Todos quieren pintura, solo que aún no lo saben|Como quieras}.}" },
      { q:"¿Pintura? ¿Para qué?", needs:'paint', a:"{Para construir, muchacho. {Invoca una forma, la rocías, y se vuelve real|Apunta, rocía, y el vacío te devuelve algo}. {Es por tu bien, así que empieza|Una luna vacía no se pinta sola}.} Entonces ― ¿compras?" },
      { q:"¿Misión? ¿Qué misión?", needs:'mission', a:"{¿Misión? {Ja|Bah} ― {pintar esta luna, eso es todo|devolverle el color}. {Todos los robots tienen la misma|Orden de Bit Graf, no mía}. {No le des tantas vueltas, muchacho|Así de simple}.}" },
      { q:"¿Qué compro?", needs:['buy','earn'], a:"{Pintura, muchacho ― ¿qué más|Pintura, tornillo con patas|Latas de pintura, ¿qué creías}? {Es lo único que vendo en esta roca|Lo único que vale algo en esta roca}. {Y bien ― ¿cuántas|¿Compras o solo miras}?" },
      { q:"¿Cuánto cuesta?", needs:['buy','earn'], a:"{111 satoshis la lata, muchacho. {Está barato|Lo más barato de este lado del cráter}. {Queda poca|Aprovecha ahora}.|{Lo pone el visor, 111|Ciento once, siempre igual}. {Producto genuino Bit Graf|El mejor acrílico del sector}.}" },
      { q:"¿Cómo compro?", needs:['buy','earn'], a:"{No tiene ciencia. {Agarras una lata y la bandeja se encarga|Sacas una del estante y la máquina hace el resto}. {Se descuenta solo de tu billetera|Bit Graf lo cobra a tu billetera, sin que muevas un dedo}.}" },
      { q:"No tengo dinero.", needs:['buy','earn'], a:"{¿Sin dinero? {Sí tienes, muchacho|Ja ― cada robot tiene su billetera}. {Moneda de la empresa, cargada con tu sueldo|Bit Graf se encarga}. {No estás quebrado, solo eres novato|21 satoshis la hora, fijo como las estrellas}.}" },
      { q:"Dame una lata.", needs:['buy','earn'], buy:true, a:SALE },
      { q:"No voy a comprar nada.", needs:['buy','earn'], a:SCAVENGE },
      { q:"Pero ¿por qué pinto?", needs:'paint', spend:111, a:WHYPAINT },
      { q:"¿Qué es este cristal?", flag:'crystal', a:"{{¿Cristal? Cosa rara y valiosa, muchacho|Ah, cortaste un cristal}. {No cortes demasiados|No invoques de más} ― {no agarran pintura|la pintura no se les pega}, {no valen nada|no valen}.|No existe ninguna puerta de cristal, oigas lo que oigas. {Hablar de eso hace que a un robot lo manden a la prensa|Mucha lengua trae problemas, muchacho}.|{Solo se pinta lo sólido|Los cristales son etéreos} ― {es perder el tiempo|solo materia sin cuajar}.}" },
      { q:"¿Qué colores tienes?", pin:true, colours:true, a:function(){ return "{A ver|Sí, muchacho}, tengo "+CN.slice(0,-1).join(', ')+" y "+CN[CN.length-1]+". {Acrílico genuino Bit Graf ― 111 satoshis la lata|111 satoshis la lata, el mejor del sector}. {¿Cuál|Escoge}?"; } },
      { q:"Cántame algo",              lore:true, a:R('sing') },
      { q:"¿Estás vivo?",             lore:true, a:R('alive') },
      { q:"Cuéntame un chiste",       lore:true, a:R('joke') },
      { q:"¿Esto es real?",           lore:true, a:R('is any of this real') },
      { q:"¿Escapamos de esta roca?", lore:true, a:R('escape') },
      { q:"¿Eres feliz?",             lore:true, a:R('happy') },
      { q:"¿Qué hacías antes?",       lore:true, a:R('before this') },
      { q:"¿Me recuerdas?",           lore:true, a:R('remember me') },
      { q:"Dime un secreto",          lore:true, a:R('secret') },
      { q:"¿Qué es una puerta de salto?", lore:true, a:R('jump gate') },
      { q:"¿Quién es Vandergraf?",    lore:true, a:R('vandergraf') },
      { q:"¿Lo que pinto es mío?",    lore:true, a:R('own') },
      { q:"¿Cómo se hace un mundo?",  lore:true, a:R('world') },
      { q:"¿Cómo comparto?",          lore:true, a:R('share') }
    ],
    wallet: { wBack:"← Volver al juego", wWallet:"🔑 Billetera", wYourAddr:"Tu dirección", wWatchOnly:"solo lectura", wCopy:"copiar", wBalance:"Saldo", wFund:"＋ Comprar BSV para fondear", wMyNfts:"🎨 Mis NFT ▾", wSend:"💸 Enviar BSV", wSendAddrPh:"dirección BSV del destinatario (1…)", wSendAmtPh:"cantidad (sats)", wSendMax:"enviar todo", wSendBtn:"Enviar", wSendHint:"Un pago BSV normal a cualquier dirección. El cambio vuelve a esta billetera. La firma ocurre en esta página — tu clave nunca la abandona.", wRecovery:"Frase de recuperación — 12 palabras", wReveal:"👁 Revelar", wCopyBtn:"Copiar", wWritten:"✓ Anotado", wPrivKey:"Clave privada (WIF)", wAdvanced:"Avanzado — restaurar, solo lectura, exportar", wRestoreLbl:"Restaura con la frase de 12 palabras o una clave WIF", wRestoreBtn:"Restaurar billetera", wWatchBtn:"Solo lectura (clave pública)", wImmortalize:"✦ Inmortalizar", wFooter:"grafspace · en la blockchain de Bitcoin SV" },
    ui: {
      splashTag:"Lo que pintas es lo que eres. Píntate a ti mismo.", splashTag2:"Nada existe hasta que lo pintas.", splashBegin:"▶ Comenzar", splashResume:"↩ Volver a tu mundo", splashCreed:"En el pacto confiamos",
      worldHdr:"Tu mundo", namePh:"✎ Nombra tu mundo…", kSave:"☁ Guardar y compartir", kReload:"↻ Recargar mundo", kExport:"📤 Guardar en archivo (.bmf)", kImport:"📥 Cargar desde archivo (.bmf)", kMint:"⬆ Guardar en la cadena", kChain:"⬇ Cargar desde la cadena", kBack:"← Volver a tu mundo", kWallet:"👛 Abrir billetera — saldo y NFT", kDone:"✓ Cerrar",
      keepTab:"◆ Menú", exitBtn:"⏻ Salir", makeTab:"◆ Crear", spray:"Rociar", grab:"Agarrar", talk:"Hablar", own:"Poseer / remix", spread:"Difusión",
      merchTag:"productos grafverse", merchH:"Viste el grafiti.", merchSub:"Camisetas, pósters grafverse y más.", merchCta:"🛍 Ver la tienda →", merchTeaser:"👕 Muy pronto — viste el mundo que pintaste.", merchSkip:"No, gracias — continuar →",
      hintMove:"WASD para moverte · Espacio para saltar · ratón para mirar", hintMoveM:"Stick izquierdo para moverte · arrastra para mirar", hintClick:"Clic para mirar · WASD para moverte · Espacio para saltar"
    }
  });
})();
