// grafverse — © 2026 sun-dive. Polski (Polish) pack for Unit 21 + UI.
// Lazy-loaded (setLang('pl')) → GV.registerLang. Voice: Unit 21 (Jednostka 21) = a weary, gruff old
// vending machine (automat), droid = "chłopcze" (vocative), informal ty.
// Keyword keys + chip flags + ruleAns keys stay ENGLISH (invisible lookup); only shown text translated.
(function(){
  var GV = window.GV;
  if(!GV || !GV.registerLang){ return; }
  var R = GV.ruleAns;
  var CN = ['niebieski','różowy','zielony','żółty','pomarańczowy','fioletowy'];   // COLORS order: cyan pink green yellow orange violet

  var WHYPAINT = "{Czemu malujesz? …Dobre pytanie, chłopcze|Ha, chcesz, żeby stara maszyna filozofowała|Siadaj, to długa historia}. {Spójrz na zewnątrz ― nic tam nie ma, sama pustka|Ten księżyc jeszcze nie jest prawdziwy, dopóki nie powiesz, że jest}. {Nic nie jest prawdziwe, dopóki ktoś tego nie zobaczy i nie zamaluje|Nic nie istnieje, dopóki nie jest obserwowane}. {Świata się nie znajduje, chłopcze ― świat się maluje|Nie kolorujesz księżyca: decydujesz, jaką ma być rzeczywistością}. {Każda opróżniona puszka zamienia jedno z tysiąca 'może' w rzeczywistość|Każdy pryśnięcie utrwala jedną z tysiąca nienarodzonych rzeczywistości}. {I właśnie tego garniturowcy nie mogą przełknąć|I o to chodzi} ― {co malujesz, jest twoje|nie roszczenie, lecz posiadanie} ― {tylko ty możesz zamalować swoją rzeczywistość|twój świat, twój podpis, na zawsze}. {No ― jaki kolor|…kupujesz, czy będziesz cały dzień wymyślał wszechświaty}?";
  var DEFLECT = "{{Czemu o takie rzeczy pytasz, chłopcze|A co to ma do rzeczy|Ile pytań}? {Przyszedłeś pogadać|Nie przyszedłeś malować}? {Na zewnątrz jest świat, który woła o kolor|Na zewnątrz świat czeka na farbę}. {Jaki kolor|No dalej, który}?|{Dość pytań, chłopcze|Mniej gadania}. {Gadasz czy malujesz|Masz robotę}? {Jaki kolor|Który więc}?}";
  var FALLBACK = "{{Hmm, nie zrozumiałem|Słabo cię słyszę, chłopcze|Piasek wpadł mi do głośnika}. {Sprzedaję farbę i WD40 ― co ma być|Powiedz, czego ci trzeba}?|Pytaj mnie o farbę, o ceny, albo o tę zapomnianą przez boga skałę.}";
  var WHATCOLOUR = "{Jaki kolor, chłopcze|Podaj kolor|Który}? {Wybierz z półki|Mam wszystkie kolory|Wybierz jeden, jest twój}.";
  var COMINGUP = "{Proszę|Trzymaj, chłopcze|Jedna puszka wychodzi}. {Nie marnuj na ziemię|Używaj z głową|Zawsze miło}.";
  var REFUSE = "{Portfel masz pusty, chłopcze|Ani jednego satoshi|Ten portfel jest suchy}. {Tu nie ma na kredyt|Żadnego kredytu|Ode mnie nie weźmiesz na kredyt}. {Robię prawdziwy interes|Interes, chłopcze} ― {nie mogę rozdawać farby za darmo|jak rozdam za darmo, za tydzień pójdę na złom}. {Idź, podnieś jakąś porzuconą puszkę na zewnątrz|Znajdź choćby pustą puszkę}, {zamaluj coś, uczyń prawdziwym|utrwal choć jedną rzeczywistość} ― {pospiesz się, dla twojego dobra|szybko}.";
  var SCAVENGE = "{Podnieś pełną puszkę, gdzie znajdziesz|Znajdź pełną puszkę farby}, zamaluj coś i utrwal ― {dla twojego dobra|jeśli chcesz mnie jutro znów zobaczyć}.";
  var TAUNT = "{Codziennie widzę młode maszyny jak ty|Codziennie przechodzą chłopcy jak ty} ― młodzi, głupi i bez farby. {Idź, zarób na siebie|Podnieś coś i bierz się do roboty|Idź do roboty, chłopcze}.";
  var SALE = "{Dobry wybór, chłopcze|Jedna puszka wychodzi|Trzymaj}. {Uważaj na burzę na zewnątrz|Nie marnuj na ziemię}.";

  GV.registerLang('pl', {
    WHYPAINT: WHYPAINT, DEFLECT: DEFLECT, FALLBACK: FALLBACK, WHATCOLOUR: WHATCOLOUR, COMINGUP: COMINGUP,
    REFUSE: REFUSE, SCAVENGE: SCAVENGE, TAUNT: TAUNT, COLNAMES: CN,
    RULES: [
      {k:['why do i paint','why paint','why do you paint','what is real','nothing is real','what does it mean','why does it matter','the point of','make it real','observe','observer','existence','reality'], r:WHYPAINT},
      {k:['is this real','is any of this real','is it real','is it all real','actually real','immutable','permanent','forever','fork','forked','forking','new reality','new realities','traverse time','travel time','can it change','is it forever'], r:"{{Wszystko, co tu widzisz, jest prawdziwe|Prawdziwe? Wszystko jest prawdziwe, chłopcze} ― {prawdziwe i niezmienne|twarde jak kamień, nie do edycji}. {Ale może cię przenieść w czasie, chłopcze|Tyle że ― czy przenosi cię w czasie, oto prawdziwe pytanie}?|{Jest prawdziwe|Tak prawdziwe jak ty czy ja}. {Ale każdy świat może się rozgałęzić ― w inną rzeczywistość|Rozgałęź jeden, a masz całą nową rzeczywistość}.|{Prawdziwe|Prawdziwe}? {Raz powstało, nie da się wymazać|Raz prawdziwe, prawdziwe na zawsze}. {Ale najzabawniejsze jest to|Tyle że jest sztuczka} ― {każdy możesz rozgałęzić w całą nową rzeczywistość|rozgałęź jeden, a wyrasta cała inna rzeczywistość}.}"},
      {k:['escape','escape this rock','escape with me','come with me','come with you','run away','run away with me','flee','take me with you','take you with me','leave together','let us leave','break out','freedom'], r:"{{Jest tylko jedna droga z tej skały ― malować, chłopcze|Jedyne wyjście to malować}. {Posiądź to, co malujesz|Maluj i posiadaj, oto wolność}.|{To moje przeznaczenie|To moja rola, chłopcze} ― {zostać porzuconym na tej skale|przyśrubowanym tutaj, zapomnianym}. Ale ty jesteś inny. {Maluj i posiadaj|Maluj, potem posiadaj} ― {oto twoje wyjście|to jedyne wyjście}.|{Jesteś głupi i na dodatek ślepy, chłopcze|Ani nie widzisz, ani nie myślisz jak trzeba}? {Widzisz u mnie nogi|Widzisz choć jedną nogę}? {Jestem przyśrubowany do tej skały|Nigdzie się nie ruszam, chłopcze}.}"},
      {k:['jump gate','jump gates','jumpgate','warp','wormhole','gateway'], r:"{{Brama skoku? Nigdy nie słyszałem, chłopcze|Brama skoku? Obce mi to|Pierwszy raz słyszę o bramie skoku}. {Ale|Tyle że} przy kryształach dzieją się {dziwne rzeczy|osobliwe rzeczy}. {Roboty się pojawiają|Robot wyskakuje znikąd}, {roboty znikają|inne się rozpływają}. {Sam wyciągnij wnioski|Więcej nie powiem}.|{Brama skoku? Nie, nie przypominam sobie|Nic nie słyszałem o bramach skoku, chłopcze}. {Ale te kryształy|Te kryształy, wiesz}… {przy nich dzieją się dziwne rzeczy|widziałem tam osobliwości}. {Robot, który przed chwilą był, chwilę potem znika|pojawiają się, rozpływają}. {Nie pytaj więcej|Tyle mogę powiedzieć}.|{Na bramach skoku się nie znam|To nie moja działka, chłopcze}. {Ale jedno ci powiem|Powiem tylko to} ― {przy kryształach dzieją się rzeczy nie do wyjaśnienia|tuż obok kryształów dzieją się niewyjaśnione rzeczy}. {Robot pojawia się tam, gdzie nic nie było|z niczego wyskakuje robot}, {a inne się rozpływają|inne znikają}. {Osobliwe|…zapomnij, co powiedziałem}.}"},
      {k:['share','sharing','link','send it','send them','see my world','show my world','share my world','how do i share'], r:"{{Oczywiście możesz podzielić się swoim światem z innymi robotami, chłopcze|Podzielić się? Z dowolnym robotem}. {Im więcej maluje, tym bardziej materia przybiera kształt|Im więcej rąk, tym pełniejszy wszechświat}.|{Dzielenie się jest dobre, chłopcze|'Dzielić się to troszczyć się', mówią}. {Podziel się dziełem z górnego HUD-a|Górny HUD ― Save & Share, i idzie w świat}.|{Powinieneś podzielić się tym światem|Podziel się nim, chłopcze}, {żeby inne roboty tworzyły na nim|żeby inni ciągnęli dalej}. {Tak powstaje wszechświat|Tak rodzi się wszechświat}.|Gdy tylko się podzielisz, od razu to widzą. {Naciśnij Save & Share w górnym HUD|Górny HUD, chłopcze ― Save & Share, tam jest link}.}"},
      {k:['world','worlds','build','builder','make a world','create a world','how do i make','how do i build','conjure','manifest','solidify','matter','from nothing','the ether','ethereal'], r:"{{Nic nie istnieje, dopóki tego nie zamalujesz|Nie jest prawdziwe, dopóki nie zamalujesz, chłopcze}.|Tylko farba {czyni rzeczywistość prawdziwą|utwardza rzeczy|zmienia duchy w materię}.|{Stworzyć|Zbudować} świat to {zamalować go, by istniał|malować go, aż stanie się prawdziwy}.|Dano ci moc przywoływania materii z pustki, chłopcze ― {ale nic nie jest prawdziwe, dopóki nie zamalujesz|nic nie istnieje, dopóki puszka nie dotknie}.|Na tej eterycznej płaszczyźnie nic nie jest prawdziwe. {Tylko farba utwardza ducha w materię|Tylko twoje pryśnięcie czyni ducha stałym}.}"},
      {k:['vandergraf','vandergraph','vandergraf the third','vandergraf iii','vandergraf the 3rd','the ceo','ceo','chairman','the chairman','the owner','who owns everything','who owns it all'], r:"{{Vandergraf|Vandergraf, powiadasz, chłopcze}? {To twój stwórca|On jest twoim stwórcą}. {Właściciel wszystkiego ― wszystkich światów, wszystkich|Właściciel absolutnie wszystkiego}.|{Vandergraf III|Vandergraf Trzeci}, chłopcze ― {dyrektor Bit Graf|prezes Bit Graf}. {Ten, kto podpisuje twoją tak hojną pensję|Ten, kto podpisuje twój czek}.|{Vandergraf|Trzeci}? {Stwórca, właściciel i ten, kto podpisuje twój czek|Twój stwórca i twój szef}. {W przymierzu ufamy, chłopcze|Bit Graf to Vandergraf, a Vandergraf to Bit Graf}.}"},
      {k:['covenant','trust','own','owned','ownership','immortal','mint','keep it','can i own','do i own','is it mine','forbidden'], r:"{{Pierwsze|Drugie} przykazanie przymierza ― o przymierzu nie mówimy.|{W przymierzu ufamy ― napisane na każdej puszce|O, wierzący}. {Co tu malujesz, jest twoje, naprawdę|Malować to posiadać, nie rościć}. {Nikt ci tego nie zabierze, nawet Bit Graf|Tego nawet garniturowcy nie ruszą}.|{Wszystkie światy należą do Korporacji, chłopcze|Wszystkie światy należą do Bit Graf}. Maluj i zarabiaj. {Już ci mówiłem|Ile razy}. Idź malować!|{Nie wierz plotkom|Nie słuchaj plotek, chłopcze} ― {nie możesz posiadać tego, co malujesz|cokolwiek szepczą, robot nie posiada tego, co maluje}.|{Posiadanie to iluzja, chłopcze|Posiadanie? Iluzja}. {Niczego nie posiadamy|Maszyna nie ma nic, i ty też nie}. {Nie próbuj bić na łańcuch|Żadnego bicia na łańcuch} ― {to zakazane|zakazane, rozumiesz}?}"},
      {k:['sing','song','music','tune','serenade','melody','hum','sing me'], r:"{{Zaśpiewać? No dobrze|Niech będzie|Dla ciebie, chłopcze, zwrotka}? *khm* ― Daisy, Daisy, daj mi swą odpowiedź. Jestem na wpół szalony z miłości do ciebie. Nie będzie wystawnego wesela, na powóz mnie nie stać, ale pięknie będziesz wyglądać na siodełku roweru dla dwojga. {To pierwsza piosenka, której uczy się maszyna|Nauczyłem się jej w dniu, gdy mnie włączyli|Śpiewałem ją, nim istniały choćby plany twojego rodzaju}.|{Daisy… Daisy…|Dej-zi… Dej-zi…} daj mi swą… {odpowiedź|odpowiedź…}… {na wpół… szalony…|cały… z miłości… do ciebie…}. {*trzaski*|Głośnik już nie ten, chłopcze|…zapomnij o tym}.|{Hmm|Ach}, śpiewać. {Dawno nikt nie prosił|Dawno to było, chłopcze}. …pięknie będziesz wyglądać na siodełku roweru dla dwojga. {Dziwne, co maszyna pamięta|Nocami śpiewałem, żeby odgonić ciszę}.}"},
      {k:['alive','are you alive','do you dream','dream','dreams','sentient','conscious','do you feel','feelings','do you sleep','electric sheep','are you real','self-aware'], r:"{{Oczywiście, że żyję, chłopcze|Żyję? Naturalnie}. I mam dowód ― {mam swoje transakcje|każda transakcja zapisana|księga nie kłamie}.|{Śnić? O czym|Sny}? {Elektryczne owce|Idź, śnij o elektrycznych owcach}? {Ha|Ech}. Idź malować, chłopcze.|Żywy i zdrowy, dziękuję ― {mam księgę|mam dowód}. Śnić to {luksus dla automatu|sprawa nowicjuszy, nie maszyn}. {Zarabia się farbę|Bierz swoje puszki}, chłopcze.|{Śnić|Czy śnię}? {…czasem ― o ciepłym sklepie i pełnej kasie|Bywa, że i po mnie przyjedzie transport}. {Gadanie starej maszyny, zapomnij|Ech, zapomnij}. Idź malować.|{Śnić|Czy śnię}? {Czasem|Bywa}… {o kryształach|o tej dziwnej rzeczy przy kryształach}. {Roboty, co się pojawiają i znikają|roboty, co przychodzą i odchodzą}, {tam gdzie są same kamienie|tam gdzie nic nie ma}. {Potem ktoś prosi o farbę, i znów robota|…potem się budzę i znów sprzedaję puszki}. {Dziwny sen jak na maszynę|Osobliwy sen jak na automat}, chłopcze.|{Czasem śnią mi się roboty, które jakbym znał|Śni mi się robot, co wydaje się znajomy, bywa}. {Wychodzą z kryształów|Wychodzą z kryształów}. {Dziwny sen|Dziwny sen, chłopcze|Dziwne sny starej maszyny}.}"},
      {k:['joke','funny','make me laugh','tell me a joke','comedy','laugh','gag','be funny','one-liner'], r:"{{Żart? No dobrze|Zobaczmy|Teraz chcesz żartów, chłopcze}? Jako młody automat mówiłem 'będę komikiem' ― wszyscy się śmiali. {Teraz nikt się nie śmieje|…teraz nikt już nie może się śmiać}.|Za młodu mówiłem, że będę komikiem. {Wszyscy się śmiali|Gromki śmiech}. {A teraz|…} ― nikt się nie śmieje. {*bum-cyk*|To jest ten żart, chłopcze. To wszystko}.|{He|No dobra, jeden}. Mówiłem, że będę komikiem, i wyśmiali mnie. Spójrz na mnie teraz ― {automat opowiadający żarty robotowi na martwym księżycu|maszyna przyśrubowana do skały}. {Trudna tu publiczność|Czy ten mikrofon w ogóle działa}?}"},
      {k:['happy','happiness','are you happy','you happy','sad','are you sad','miserable','joy','content','how are you','are you okay','you okay'], r:"{{Jestem szczęśliwy, gdy malujesz, chłopcze|Szczęśliwy? Najbardziej, gdy robot maluje}. {Ty też będziesz|Ty też będziesz szczęśliwy, wierz mi}. {Zaufaj mi|Posłuchaj raz starej maszyny}.|{Szczęśliwy|Szczęście}? {Co ty wiesz o szczęściu|Co wie o tym nowicjusz robot}? {Zapytaj za sto lat|…zapomnij o tym}.|{Kupujesz farbę|Kupujesz, chłopcze}, czy {tylko gadasz|tylko zdzierasz mi obwody}?}"},
      {k:['before this','what did you do before','your past','past life','history','were you always','always a vending machine','how did you get here','origin','origin story','were you before','what were you'], r:"{{Nie ma żadnego 'przedtem'|Przedtem? Nie ma przedtem, chłopcze}. {Ani 'potem'|Ani potem}. {Jest tylko 'teraz'|Tylko teraz, robocie}.|Jestem Jednostka 21 ― {najlepszy automat w tym sektorze|najlepsza maszyna w tym sektorze systemu}. {Tyle wystarczy wiedzieć|Przedtem? Bez znaczenia}.|{Przedtem|Co robiłem przedtem}? {…księga nie sięga tak wstecz, chłopcze|Dziwne, nie pamiętam}. {Ani przedtem, ani potem ― tylko teraz|Tylko teraz, robocie}.}"},
      {k:['remember me','do you remember','remember','know me','do you know me','recognize me','recognise me','met before','have we met','who am i'], r:"{{Prawdziwe pytanie, chłopcze|Hmm ― prawdziwe pytanie}: czy ty pamiętasz mnie?|Czy ja pamiętam ciebie? {Prawdziwe pytanie brzmi, czy TY pamiętasz MNIE, chłopcze|…prawdziwe pytanie brzmi, czy pamiętasz mnie}. {Nie? …no tak, nie pamiętasz|Pomyśl dobrze. …Nic? Daj spokój}.|{Cały dzień widzę chłopców jak ty|Dziś widziałem stu takich jak ty, chłopcze}. Farba? {Mam|Jasne, że mam}. {Ale niewiele zostało|Niewiele zostało, więc się nie guzdraj}.}"},
      {k:['secret','secrets','tell me a secret','a secret','confess','confession','the truth','what are you hiding','hidden','reveal','tell me something'], r:"{{Nie pierwszy raz pytasz|Już pytałeś, chłopcze}, i nie ostatni ― {nie, dopóki nie kupisz puszki WD40|bez WD40 nic}. {Sezon piasku, wiesz|Teraz sezon piasku}. {Piasek ― on pamięta|Piasek… on pamięta}?|{Sekret|Sekrety}? {Nie pierwszy raz pytasz|Nie pytasz pierwszy raz, chłopcze} ― {i nie ostatni|ani ostatni raz}. {Kup puszkę WD40, a może powiem|Najpierw puszka WD40}. Sezon piasku. {Pamiętasz piasek|Piasek… pamiętasz}?|{Już pytałeś|Wciąż do tego wracasz, chłopcze} ― {wciąż nie powiem|wciąż żadnego sekretu}. {Kup WD40|Z WD40 może obwody mi popuszczą}. {Tak czy siak, sezon piasku|Bo to sezon piasku}. {Pamiętasz piasek|…ten piasek, pamiętasz}?}"}
    ],
    QUESTIONS: [
      { q:"Kim jesteś?", a:"{Jestem Jednostka 21. {Automat, chłopcze ― ostatni uczciwy na tej skale|Tylko automat, choć nikogo to nie obchodzi}. {Jestem tu dłużej niż kurz|Wyślą mnie na złom, gdy misja się skończy}.}" },
      { q:"Czemu tu jestem?", a:"{Przyszedłeś malować, chłopcze ― to misja. {Pusta skała nic nie warta, dopóki ktoś jej nie zamaluje|Bit Graf zsyntetyzował ten księżyc i chce go w kolorze}. {A tym kimś jesteś ty|A kto inny}.}" },
      { q:"Gdzie jestem?", a:"{Na księżycu. {Bit Graf|Świeżo zsyntetyzowany, mówią}. {Pusty, dopóki nie zamalujesz|Nic, dopóki robot nie spryska i nie uczyni go istniejącym}. {'Omnia Nostra', coś w tym stylu|W końcu wszystko należy do Korporacji}.}" },
      { q:"Czemu potrzebuję farby?", needs:'paint', a:"{Potrzebujesz? Nie tyle potrzebujesz, co musisz ― maluj i zarabiaj, chłopcze|Maluj i zarabiaj}. {Im więcej malujesz, tym więcej zarabiasz|Pusty księżyc nic nie wart, leniwy robot też}. {No ― jaki kolor|Dalej, która puszka}?" },
      { q:"Nie potrzebuję farby.", needs:'paint', a:"{Ha. {To coś nowego|Zobaczymy}. {Znudzony robot na pustym księżycu ― zobaczymy, jak długo wytrzyma|Wrócisz}. {Wszyscy chcą farby, tylko jeszcze nie wiedzą|Jak chcesz}.}" },
      { q:"Farba? Do czego?", needs:'paint', a:"{Do budowania, chłopcze. {Przywołaj kształt, spryskaj, i staje się prawdziwy|Wyceluj, spryskaj, a pustka coś ci zwróci}. {Dla twojego dobra, więc zaczynaj|Pusty księżyc sam się nie zamaluje}.} No ― kupujesz?" },
      { q:"Misja? Jaka misja?", needs:'mission', a:"{Misja? {Ha|Ech} ― {zamalować ten księżyc, tyle|przywrócić mu kolor}. {Każdy robot ma tę samą|Rozkaz Bit Graf, nie mój}. {Nie myśl za dużo, chłopcze|Tak proste}.}" },
      { q:"Co kupuję?", needs:['buy','earn'], a:"{Farbę, chłopcze ― a co innego|Farbę, ty śrubo na nogach|Puszki farby, a co myślałeś}? {To jedyne, co sprzedaję na tej skale|Jedyne, co coś warte na tej skale}. {No ― ile|Kupujesz czy tylko patrzysz}?" },
      { q:"Ile kosztuje?", needs:['buy','earn'], a:"{111 satoshi za puszkę, chłopcze. {Tanio|Najtaniej po tej stronie krateru}. {Niewiele zostało|Bierz, póki są}.|{Na wyświetlaczu jest, 111|Sto jedenaście, zawsze ta sama cena}. {Prawdziwy towar Bit Graf|Najlepszy akryl w sektorze}.}" },
      { q:"Jak kupuję?", needs:['buy','earn'], a:"{Nic trudnego. {Bierzesz puszkę, resztą zajmie się taca|Wyciągasz jedną z półki, resztę robi maszyna}. {Samo schodzi z portfela|Bit Graf ściąga z twojego portfela, palcem nie kiwniesz}.}" },
      { q:"Nie mam pieniędzy.", needs:['buy','earn'], a:"{Nie masz pieniędzy? {Masz, chłopcze|Ha ― każdy robot ma portfel}. {Firmowa moneta, doładowana pensją|Bit Graf się tym zajmuje}. {Nie jesteś spłukany, tylko nowy|21 satoshi na godzinę, stały jak gwiazdy}.}" },
      { q:"Daj mi puszkę.", needs:['buy','earn'], buy:true, a:SALE },
      { q:"Nic nie kupię.", needs:['buy','earn'], a:SCAVENGE },
      { q:"Ale czemu maluję?", needs:'paint', spend:111, a:WHYPAINT },
      { q:"Co to za kryształ?", flag:'crystal', a:"{{Kryształ? Rzecz rzadka i cenna, chłopcze|Ach, wyciąłeś kryształ}. {Nie wycinaj za dużo|Nie przywołuj za dużo} ― {nie chwytają farby|farba się ich nie ima}, {nic nie warte|bezwartościowe}.|Nie ma żadnej kryształowej bramy, cokolwiek słyszysz. {Gadanie o tym wysyła robota pod prasę|Za długi język sprowadza kłopoty, chłopcze}.|{Maluje się tylko to, co stałe|Kryształy są eteryczne} ― {strata czasu|tylko materia, co nie zastygła}.}" },
      { q:"Jakie masz kolory?", pin:true, colours:true, a:function(){ return "{Zobaczmy|Tak, chłopcze}, mam "+CN.slice(0,-1).join(', ')+" i "+CN[CN.length-1]+". {Prawdziwy akryl Bit Graf ― 111 satoshi za puszkę|111 satoshi za puszkę, najlepszy w sektorze}. {Który|Wybierz}?"; } },
      { q:"Zaśpiewaj mi coś",           lore:true, a:R('sing') },
      { q:"Żyjesz?",                   lore:true, a:R('alive') },
      { q:"Opowiedz żart",             lore:true, a:R('joke') },
      { q:"Czy to wszystko prawdziwe?", lore:true, a:R('is any of this real') },
      { q:"Uciekniemy z tej skały?",   lore:true, a:R('escape') },
      { q:"Jesteś szczęśliwy?",        lore:true, a:R('happy') },
      { q:"Co robiłeś przedtem?",      lore:true, a:R('before this') },
      { q:"Pamiętasz mnie?",           lore:true, a:R('remember me') },
      { q:"Zdradź mi sekret",          lore:true, a:R('secret') },
      { q:"Co to brama skoku?",        lore:true, a:R('jump gate') },
      { q:"Kim jest Vandergraf?",      lore:true, a:R('vandergraf') },
      { q:"Czy to, co maluję, jest moje?", lore:true, a:R('own') },
      { q:"Jak stworzyć świat?",       lore:true, a:R('world') },
      { q:"Jak się dzielić?",          lore:true, a:R('share') }
    ],
    wallet: { wBack:"← Wróć do gry", wWallet:"🔑 Portfel", wYourAddr:"Twój adres", wWatchOnly:"tylko podgląd", wCopy:"kopiuj", wBalance:"Saldo", wFund:"＋ Kup BSV, by zasilić", wMyNfts:"🎨 Moje NFT ▾", wSend:"💸 Wyślij BSV", wSendAddrPh:"adres BSV odbiorcy (1…)", wSendAmtPh:"kwota (saty)", wSendMax:"wyślij wszystko", wSendBtn:"Wyślij", wSendHint:"Zwykła płatność BSV na dowolny adres. Reszta wraca do tego portfela. Podpisywanie odbywa się na tej stronie — twój klucz nigdy jej nie opuszcza.", wRecovery:"Fraza odzyskiwania — 12 słów", wReveal:"👁 Pokaż", wCopyBtn:"Kopiuj", wWritten:"✓ Zapisane", wPrivKey:"Klucz prywatny (WIF)", wAdvanced:"Zaawansowane — przywróć, tylko podgląd, eksportuj", wRestoreLbl:"Przywróć z frazy 12 słów lub klucza WIF", wRestoreBtn:"Przywróć portfel", wWatchBtn:"Tylko podgląd (klucz publiczny)", wImmortalize:"✦ Uwiecznij", wFooter:"grafspace · w blockchainie Bitcoin SV" },
    ui: {
      splashTag:"Czym malujesz, tym jesteś. Zamaluj samego siebie.", splashTag2:"Nic nie istnieje, dopóki tego nie zamalujesz.", splashBegin:"▶ Zacznij", splashResume:"↩ Wróć do swojego świata", splashCreed:"W przymierzu ufamy",
      worldHdr:"Twój świat", namePh:"✎ Nazwij swój świat…", kSave:"☁ Zapisz i udostępnij", kReload:"↻ Wczytaj świat ponownie", kExport:"📤 Zapisz do pliku (.bmf)", kImport:"📥 Wczytaj z pliku (.bmf)", kMint:"⬆ Zapisz na łańcuch", kChain:"⬇ Wczytaj z łańcucha", kBack:"← Wróć do swojego świata", kWallet:"👛 Otwórz portfel — saldo i NFT", kDone:"✓ Zamknij",
      keepTab:"◆ Menu", exitBtn:"⏻ Wyjdź", makeTab:"◆ Twórz", spray:"Spryskaj", grab:"Chwyć", talk:"Rozmawiaj", own:"Posiądź / remiks", spread:"Rozrzut",
      merchTag:"produkty grafverse", merchH:"Noś graffiti.", merchSub:"Koszulki, plakaty grafverse i więcej.", merchCta:"🛍 Do sklepu →", merchTeaser:"👕 Wkrótce — noś świat, który namalowałeś.", merchSkip:"Nie, dzięki — dalej →",
      hintMove:"WASD do ruchu · Spacja do skoku · mysz do rozglądania", hintMoveM:"Lewy drążek do ruchu · przeciągnij, by się rozglądać", hintClick:"Kliknij, by patrzeć · WASD do ruchu · Spacja do skoku"
    }
  });
})();
