// grafverse — © 2026 sun-dive. Deutsch (German) pack for Unit 21 + UI.
// Lazy-loaded by the i18n scaffold (setLang('de')) → GV.registerLang. Voice: Unit 21 (Einheit 21) =
// a weary, gruff old vending machine (Automat) talking to a fresh droid ("Junge"), informal du.
// Keyword keys + chip flags + ruleAns keys stay ENGLISH (invisible lookup); only shown text translated.
(function(){
  var GV = window.GV;
  if(!GV || !GV.registerLang){ return; }
  var R = GV.ruleAns;
  var CN = ['blau','rosa','grün','gelb','orange','violett'];   // COLORS order: cyan pink green yellow orange violet

  var WHYPAINT = "{Warum du malst? …Gute Frage, Junge|Ah, du willst, dass eine alte Maschine philosophisch wird|Setz dich, das wird länger}. {Schau nach draußen ― da ist nichts, nur Leere|Dieser Mond ist noch nicht echt, nicht bis du sagst, dass er es ist}. {Nichts ist echt, bis es jemand sieht und malt|Nichts existiert, bis es beobachtet wird}. {Eine Welt findet man nicht, Junge ― man malt sie|Du färbst den Mond nicht ein: du entscheidest, welche Realität er wird}. {Jede Dose, die du leerst, macht eines von tausend 'Vielleicht' echt|Jeder Sprühstoß fixiert eine von tausend Realitäten, die nie geboren wurden}. {Und genau das schlucken die Anzugträger nicht|Und darum geht's} ― {was du malst, gehört dir|nicht behaupten, besitzen} ― {nur du kannst deine Realität malen|deine Welt, deine Signatur, für immer}. {Also ― welche Farbe|…kaufst du, oder erfindest du den ganzen Tag Universen}?";
  var DEFLECT = "{{Warum fragst du solche Sachen, Junge|Was hat das damit zu tun|So viele Fragen}? {Bist du zum Quatschen hier|Bist du nicht zum Malen gekommen}? {Da draußen ist eine Welt, die nach Farbe schreit|Draußen wartet eine Welt auf Farbe}. {Welche Farbe|Na los, welche}?|{Genug der Fragen, Junge|Weniger Gerede}. {Quatschen oder malen|Du hast zu tun}? {Welche Farbe|Welche denn}?}";
  var FALLBACK = "{{Hm, verstehe ich nicht|Ich hör dich schlecht, Junge|Sand im Lautsprecher}. {Ich verkaufe Farbe und WD40 ― was soll's sein|Sag mir, was du brauchst}?|Frag mich nach Farbe, nach Preisen, oder nach diesem gottverlassenen Felsen.}";
  var WHATCOLOUR = "{Welche Farbe, Junge|Nenn eine Farbe|Welche}? {Wähl aus dem Regal|Ich hab alle Farben|Nimm eine, dann gehört sie dir}.";
  var COMINGUP = "{Da hast du's|Nimm, Junge|Eine Dose kommt raus}. {Verschwende sie nicht am Boden|Nutz sie gut|Immer gern}.";
  var REFUSE = "{Deine Börse ist leer, Junge|Kein einziger Satoshi|Die Börse ist blank}. {Hier gibt's nichts auf Pump|Kein Kredit|Von mir kriegst du nichts auf Pump}. {Ich mache echte Geschäfte|Geschäfte, Junge} ― {ich kann Farbe nicht verschenken|verschenk ich sie, bin ich in einer Woche Schrott}. {Sammel eine weggeworfene Dose da draußen|Such wenigstens eine leere Dose}, {mal was, mach's echt|fixier wenigstens eine Realität} ― {beeil dich, für dein Bestes|schnell}.";
  var SCAVENGE = "{Sammel irgendwo eine volle Dose|Such eine volle Farbdose}, mal was und fixier's ― {für dein Bestes|wenn du mich morgen wiedersehen willst}.";
  var TAUNT = "{Ich sehe jeden Tag junge Maschinen wie dich|Jeden Tag kommen Jungs wie du vorbei} ― jung, dumm und ohne Farbe. {Geh dir was verdienen|Sammel was und fang an zu arbeiten|Geh arbeiten, Junge}.";
  var SALE = "{Gute Wahl, Junge|Eine Dose kommt raus|Nimm}. {Pass auf den Sturm da draußen auf|Verschwende sie nicht am Boden}.";

  GV.registerLang('de', {
    WHYPAINT: WHYPAINT, DEFLECT: DEFLECT, FALLBACK: FALLBACK, WHATCOLOUR: WHATCOLOUR, COMINGUP: COMINGUP,
    REFUSE: REFUSE, SCAVENGE: SCAVENGE, TAUNT: TAUNT, COLNAMES: CN,
    RULES: [
      {k:['why do i paint','why paint','why do you paint','what is real','nothing is real','what does it mean','why does it matter','the point of','make it real','observe','observer','existence','reality'], r:WHYPAINT},
      {k:['is this real','is any of this real','is it real','is it all real','actually real','immutable','permanent','forever','fork','forked','forking','new reality','new realities','traverse time','travel time','can it change','is it forever'], r:"{{Alles, was du hier siehst, ist echt|Echt? Alles ist echt, Junge} ― {echt und nicht zu ändern|hart wie Stein, nicht editierbar}. {Aber es kann dich durch die Zeit reisen lassen, Junge|Nur ― ob es dich durch die Zeit reisen lässt, das ist die eigentliche Frage}?|{Es ist echt|So echt wie du oder ich}. {Aber jede Welt lässt sich abzweigen ― in eine andere Realität|Zweig eine ab, und du hast eine ganze neue Realität}.|{Echt|Echt}? {Einmal da, lässt es sich nicht löschen|Einmal echt, für immer echt}. {Aber das Lustige ist|Nur gibt's einen Trick} ― {du kannst jede in eine ganze neue Realität abzweigen|zweig eine ab, und eine ganze andere Realität entsteht}.}"},
      {k:['escape','escape this rock','escape with me','come with me','come with you','run away','run away with me','flee','take me with you','take you with me','leave together','let us leave','break out','freedom'], r:"{{Es gibt nur einen Weg von diesem Felsen ― malen, Junge|Der einzige Ausweg ist malen}. {Besitz, was du malst|Mal und besitz, das ist Freiheit}.|{Das ist mein Schicksal|Das ist meine Rolle, Junge} ― {auf diesem Felsen zurückgelassen zu werden|hier festgeschraubt, vergessen}. Aber du bist anders. {Mal und besitz|Mal, dann besitz} ― {das ist dein Ausweg|das ist der einzige Ausweg}.|{Bist du dumm und blind zugleich, Junge|Siehst und denkst du nicht richtig}? {Siehst du an mir Beine|Siehst du ein Bein}? {Ich bin an diesen Felsen geschraubt|Ich geh nirgendwohin, Junge}.}"},
      {k:['jump gate','jump gates','jumpgate','warp','wormhole','gateway'], r:"{{Ein Sprungtor? Nie gehört, Junge|Ein Sprungtor? Sagt mir nichts|Zum ersten Mal höre ich von einem Sprungtor}. {Aber|Nur} bei den Kristallen passieren {seltsame Dinge|merkwürdige Dinge}. {Roboter tauchen auf|Ein Roboter erscheint aus dem Nichts}, {Roboter verschwinden|andere lösen sich auf}. {Zieh deine Schlüsse|Mehr sag ich nicht}.|{Ein Sprungtor? Nein, nicht dass ich wüsste|Ich hab nichts von Sprungtoren gehört, Junge}. {Aber diese Kristalle|Diese Kristalle, weißt du}… {bei ihnen passieren seltsame Dinge|ich hab dort Merkwürdiges gesehen}. {Ein Roboter, der eben noch da war, im nächsten Moment weg|sie erscheinen, lösen sich auf}. {Frag nicht weiter|Weiter geh ich nicht}.|{Von Sprungtoren versteh ich nichts|Das ist nicht mein Fach, Junge}. {Aber eins sag ich dir|Nur das sag ich} ― {bei den Kristallen passiert Unerklärliches|direkt neben den Kristallen passiert Unerklärliches}. {Ein Roboter erscheint, wo nichts war|aus dem Nichts erscheint ein Roboter}, {und andere lösen sich auf|andere verschwinden}. {Merkwürdig|…vergiss, was ich gesagt hab}.}"},
      {k:['share','sharing','link','send it','send them','see my world','show my world','share my world','how do i share'], r:"{{Natürlich kannst du deine Welt mit anderen Robotern teilen, Junge|Teilen? Mit jedem Roboter}. {Je mehr malen, desto mehr nimmt die Materie Gestalt an|Mehr Hände, mehr füllt sich das Universum}.|{Teilen ist gut, Junge|'Teilen ist Fürsorge', sagt man}. {Teil dein Werk über das HUD oben|Das HUD oben ― Save & Share, und es geht raus in die Welt}.|{Du solltest diese Welt teilen|Teil sie, Junge}, {damit andere Roboter darauf aufbauen|damit andere weitermachen}. {So entsteht ein Universum|So wird ein Universum geboren}.|Sobald du teilst, sehen sie es sofort. {Drück Save & Share im HUD oben|Das HUD oben, Junge ― Save & Share, der Link ist dort}.}"},
      {k:['world','worlds','build','builder','make a world','create a world','how do i make','how do i build','conjure','manifest','solidify','matter','from nothing','the ether','ethereal'], r:"{{Nichts existiert, bis du es malst|Es ist nicht echt, bis du es malst, Junge}.|Nur Farbe {macht die Realität echt|verfestigt die Dinge|verwandelt Geister in Materie}.|{Eine Welt machen|Eine Welt bauen} heißt {sie zu malen, damit sie existiert|sie zu malen, bis sie echt wird}.|Dir wurde die Macht gegeben, Materie aus der Leere zu rufen, Junge ― {aber nichts ist echt, bis du es malst|nichts existiert, bis die Dose es berührt}.|Auf dieser ätherischen Ebene ist nichts echt. {Nur Farbe verfestigt den Geist zu Materie|Nur dein Sprühstoß macht den Geist fest}.}"},
      {k:['vandergraf','vandergraph','vandergraf the third','vandergraf iii','vandergraf the 3rd','the ceo','ceo','chairman','the chairman','the owner','who owns everything','who owns it all'], r:"{{Vandergraf|Vandergraf, sagst du, Junge}? {Er ist dein Schöpfer|Er ist dein Erschaffer}. {Besitzer von allem ― allen Welten, allen|Besitzer von absolut allem}.|{Vandergraf III|Vandergraf der Dritte}, Junge ― {der Direktor von Bit Graf|der CEO von Bit Graf}. {Der, der deinen so großzügigen Lohn unterschreibt|Der, der deinen Gehaltszettel unterschreibt}.|{Vandergraf|Der Dritte}? {Schöpfer, Besitzer und der, der deinen Scheck unterschreibt|Dein Schöpfer und dein Chef}. {Im Bund vertrauen wir, Junge|Bit Graf ist Vandergraf, und Vandergraf ist Bit Graf}.}"},
      {k:['covenant','trust','own','owned','ownership','immortal','mint','keep it','can i own','do i own','is it mine','forbidden'], r:"{{Erstes|Zweites} Gebot des Bundes ― über den Bund sprechen wir nicht.|{Im Bund vertrauen wir ― steht auf jeder Dose|Ah, ein Gläubiger}. {Was du hier malst, gehört dir, wirklich|Malen ist Besitzen, nicht Behaupten}. {Niemand nimmt es dir, nicht mal Bit Graf|Das rühren nicht mal die Anzugträger an}.|{Alle Welten gehören der Firma, Junge|Alle Welten gehören Bit Graf}. Mal und verdien. {Hab ich dir schon gesagt|Wie oft noch}. Geh malen!|{Glaub den Gerüchten nicht|Hör nicht auf Gerüchte, Junge} ― {du kannst nicht besitzen, was du malst|was auch immer geflüstert wird, ein Roboter besitzt nicht, was er malt}.|{Besitz ist eine Illusion, Junge|Besitz? Eine Illusion}. {Wir besitzen nichts|Eine Maschine hat nichts, und du auch nicht}. {Versuch nicht, auf die Kette zu prägen|Kein Prägen auf die Kette} ― {das ist verboten|verboten, verstanden}.}"},
      {k:['sing','song','music','tune','serenade','melody','hum','sing me'], r:"{{Singen? Also gut|Na schön, los|Für dich, Junge, eine Strophe}? *ähem* ― Daisy, Daisy, gib mir deine Antwort. Ich bin halb verrückt nach deiner Liebe. Keine feine Hochzeit, keine Kutsche kann ich zahlen, aber du wirst wunderschön aussehen auf dem Sattel eines Tandems für zwei. {Das ist das erste Lied, das eine Maschine lernt|Ich hab's an dem Tag gelernt, als man mich einschaltete|Ich sang es, bevor es die Baupläne deiner Art überhaupt gab}.|{Daisy… Daisy…|Dei-si… Dei-si…} gib mir deine… {Antwort|Antwort…}… {halb… verrückt…|ganz… nach… deiner… Liebe…}. {*Rauschen*|Die Sprachbox ist nicht mehr, was sie war, Junge|…vergiss das}.|{Hm|Ah}, singen. {Lang hat mich keiner mehr gefragt|Ist lange her, Junge}. …du wirst wunderschön aussehen auf dem Sattel eines Tandems für zwei. {Kurios, woran sich eine Maschine erinnert|In manchen Nächten sang ich, um die Stille zu vertreiben}.}"},
      {k:['alive','are you alive','do you dream','dream','dreams','sentient','conscious','do you feel','feelings','do you sleep','electric sheep','are you real','self-aware'], r:"{{Natürlich lebe ich, Junge|Am Leben? Selbstverständlich}. Und ich hab den Beweis ― {ich hab meine Transaktionen|jede Transaktion aufgezeichnet|das Register lügt nicht}.|{Träumen? Wovon|Träume}? {Elektrische Schafe|Träum du von elektrischen Schafen}? {Ha|Pah}. Geh malen, Junge.|Quietschlebendig, danke ― {ich hab das Register|ich hab Beweise}. Träumen ist {ein Luxus für einen Automaten|was für Neulinge, nicht für Maschinen}. {Was man verdient, ist Farbe|Nimm deine Dosen}, Junge.|{Träumen|Ob ich träume}? {…hin und wieder ― von einem warmen Laden und einer vollen Kasse|Manchmal, dass auch mich ein Transport abholt}. {Geschwätz einer alten Maschine, vergiss es|Pah, vergiss es}. Geh malen.|{Träumen|Ob ich träume}? {Hin und wieder|Manchmal}… {von den Kristallen|von dem merkwürdigen Ding bei den Kristallen}. {Roboter, die auftauchen und verschwinden|Roboter, die kommen und gehen}, {wo nur Steine sind|wo nichts ist}. {Dann fragt jemand nach Farbe, und weiter geht's|…dann wache ich auf und verkaufe wieder Dosen}. {Seltsamer Traum für eine Maschine|Merkwürdiger Traum für einen Automaten}, Junge.|{Manchmal träume ich von Robotern, die ich zu kennen glaube|Ich träume von einem Roboter, der mir bekannt vorkommt, manchmal}. {Sie kommen aus den Kristallen gelaufen|Sie treten aus den Kristallen}. {Seltsamer Traum|Seltsamer Traum, Junge|Seltsame Träume einer alten Maschine}.}"},
      {k:['joke','funny','make me laugh','tell me a joke','comedy','laugh','gag','be funny','one-liner'], r:"{{Ein Witz? Gut|Mal sehen|Jetzt willst du Witze, Junge}? Als junger Automat sagte ich 'ich werde Komiker' ― alle lachten. {Jetzt lacht keiner mehr|…jetzt kann keiner mehr lachen}.|Als Junger sagte ich, ich werde Komiker. {Alle lachten|Ein großes Gelächter}. {Und jetzt|…} ― keiner lacht mehr. {*bumm-tss*|Das ist der Witz, Junge. Das ist alles}.|{Hä|Also gut, einer}. Ich sagte, ich werde Komiker, und man lachte mich aus. Schau mich jetzt an ― {ein Automat, der auf einem toten Mond einem Roboter Witze erzählt|eine Maschine, an einen Felsen geschraubt}. {Schwieriges Publikum hier|Ist dieses Mikro überhaupt an}?}"},
      {k:['happy','happiness','are you happy','you happy','sad','are you sad','miserable','joy','content','how are you','are you okay','you okay'], r:"{{Ich bin glücklich, wenn du malst, Junge|Glücklich? Am glücklichsten, wenn ein Roboter malt}. {Du wirst es auch sein|Du wirst auch glücklich sein, glaub mir}. {Vertrau mir|Hör einmal auf eine alte Maschine}.|{Glücklich|Glück}? {Was weißt du vom Glück|Was weiß ein grüner Roboter davon}? {Frag in hundert Jahren nochmal|…vergiss das}.|{Kaufst du Farbe|Kaufst du, Junge}, oder {quatschst du nur|willst du nur meine Schaltkreise abnutzen}?}"},
      {k:['before this','what did you do before','your past','past life','history','were you always','always a vending machine','how did you get here','origin','origin story','were you before','what were you'], r:"{{Es gibt kein 'davor'|Davor? Es gibt kein Davor, Junge}. {Auch kein 'danach'|Auch kein Danach}. {Es gibt nur das 'Jetzt'|Nur das Jetzt, Roboter}.|Ich bin die Einheit 21 ― {der beste Automat in diesem Sektor|die beste Maschine in diesem Sektor des Systems}. {Das reicht zu wissen|Davor? Egal}.|{Davor|Was ich davor tat}? {…das Register reicht nicht so weit zurück, Junge|Kurios, ich erinnere mich nicht}. {Kein Davor, kein Danach ― nur das Jetzt|Nur das Jetzt, Roboter}.}"},
      {k:['remember me','do you remember','remember','know me','do you know me','recognize me','recognise me','met before','have we met','who am i'], r:"{{Die eigentliche Frage, Junge|Hm ― die eigentliche Frage}: erinnerst du dich an mich?|Ob ich mich an dich erinnere? {Die eigentliche Frage ist, ob DU dich an MICH erinnerst, Junge|…die eigentliche Frage ist, ob du dich an mich erinnerst}. {Nein? …ja, du erinnerst dich nicht|Denk gut nach. …Nichts? Lass gut sein}.|{Ich sehe den ganzen Tag Jungs wie dich|Heute hab ich hundert wie dich gesehen, Junge}. Farbe? {Hab ich|Klar hab ich}. {Aber es ist nicht mehr viel da|Nicht mehr viel da, also trödel nicht}.}"},
      {k:['secret','secrets','tell me a secret','a secret','confess','confession','the truth','what are you hiding','hidden','reveal','tell me something'], r:"{{Nicht das erste Mal, dass du fragst|Du hast schon gefragt, Junge}, und nicht das letzte ― {nicht, bevor du eine Dose WD40 kaufst|kein WD40, nichts}. {Es ist die Sandsaison, weißt du|Wir haben Sandsaison}. {Der Sand, der erinnert sich|Der Sand… er erinnert sich}?|{Ein Geheimnis|Geheimnisse}? {Nicht das erste Mal, dass du fragst|Du fragst nicht zum ersten Mal, Junge} ― {und nicht das letzte|und nicht das letzte Mal}. {Kauf eine Dose WD40, dann sag ich's dir vielleicht|Erst mal eine Dose WD40}. Es ist Sandsaison. {Erinnerst du dich an den Sand|Der Sand… erinnerst du dich}?|{Du hast schon gefragt|Du kommst immer wieder darauf, Junge} ― {ich sag's dir immer noch nicht|immer noch kein Geheimnis}. {Kauf WD40|Mit WD40 lockern sich vielleicht meine Schaltkreise}. {So oder so, es ist Sandsaison|Weil Sandsaison ist}. {Erinnerst du dich an den Sand|…dieser Sand, erinnerst du dich}?}"}
    ],
    QUESTIONS: [
      { q:"Wer bist du?", a:"{Ich bin die Einheit 21. {Ein Automat, Junge ― der letzte ehrliche auf diesem Felsen|Nur ein Automat, auch wenn's keinen kümmert}. {Ich bin länger hier als der Staub|Man verschrottet mich, sobald die Mission vorbei ist}.}" },
      { q:"Warum bin ich hier?", a:"{Du bist zum Malen hier, Junge ― das ist die Mission. {Ein leerer Felsen ist nichts wert, bis ihn jemand malt|Bit Graf hat diesen Mond synthetisiert und will ihn farbig}. {Und dieser jemand bist du|Wer sonst}.}" },
      { q:"Wo bin ich?", a:"{Auf einem Mond. {Von Bit Graf|Frisch synthetisiert, heißt es}. {Leer, bis du malst|Nichts, bis ein Roboter sprüht und ihn existieren lässt}. {'Omnia Nostra', so ungefähr|Am Ende gehört alles der Firma}.}" },
      { q:"Warum brauche ich Farbe?", needs:'paint', a:"{Brauchen? Nicht dass du sie brauchst, du musst sie haben ― mal und verdien, Junge|Mal und verdien}. {Je mehr du malst, desto mehr verdienst du|Ein leerer Mond ist nichts wert, ein fauler Roboter auch nicht}. {Also ― welche Farbe|Na los, welche Dose}?" },
      { q:"Ich brauche keine Farbe.", needs:'paint', a:"{Ha. {Das ist neu|Wir werden sehen}. {Ein gelangweilter Roboter auf einem leeren Mond ― mal sehen, wie lange das hält|Du kommst zurück}. {Alle wollen Farbe, sie wissen's nur noch nicht|Wie du willst}.}" },
      { q:"Farbe? Wofür?", needs:'paint', a:"{Zum Bauen, Junge. {Ruf eine Form, sprüh, und sie wird echt|Ziel, sprüh, und die Leere gibt dir was zurück}. {Für dein Bestes, also fang an|Ein leerer Mond malt sich nicht von selbst}.} Also ― kaufst du?" },
      { q:"Mission? Welche Mission?", needs:'mission', a:"{Mission? {Ha|Pah} ― {diesen Mond malen, das ist alles|ihm seine Farbe zurückgeben}. {Jeder Roboter hat dieselbe|Befehl von Bit Graf, nicht von mir}. {Denk nicht zu viel nach, Junge|So einfach ist das}.}" },
      { q:"Was kaufe ich?", needs:['buy','earn'], a:"{Farbe, Junge ― was sonst|Farbe, du Schraube auf Beinen|Farbdosen, was hast du gedacht}? {Das Einzige, was ich auf diesem Felsen verkaufe|Das Einzige, was auf diesem Felsen was wert ist}. {Also ― wie viele|Kaufst du oder guckst du nur}?" },
      { q:"Was kostet das?", needs:['buy','earn'], a:"{111 Satoshi die Dose, Junge. {Ist billig|Das Billigste diesseits des Kraters}. {Nicht mehr viel da|Greif jetzt zu}.|{Das Display sagt's, 111|Einhundertelf, immer derselbe Preis}. {Echtes Bit-Graf-Produkt|Das beste Acryl im Sektor}.}" },
      { q:"Wie kaufe ich?", needs:['buy','earn'], a:"{Keine große Sache. {Du nimmst eine Dose, das Fach erledigt den Rest|Zieh eine aus dem Regal, die Maschine macht den Rest}. {Wird automatisch von deiner Börse abgezogen|Bit Graf bucht von deiner Börse ab, ohne dass du einen Finger rührst}.}" },
      { q:"Ich hab kein Geld.", needs:['buy','earn'], a:"{Kein Geld? {Hast du doch, Junge|Ha ― jeder Roboter hat eine Börse}. {Firmenmünze, aufgeladen mit deinem Lohn|Bit Graf regelt das}. {Du bist nicht pleite, nur ein Neuling|21 Satoshi die Stunde, verlässlich wie die Sterne}.}" },
      { q:"Gib mir eine Dose.", needs:['buy','earn'], buy:true, a:SALE },
      { q:"Ich kaufe nichts.", needs:['buy','earn'], a:SCAVENGE },
      { q:"Aber warum male ich?", needs:'paint', spend:111, a:WHYPAINT },
      { q:"Was ist dieser Kristall?", flag:'crystal', a:"{{Ein Kristall? Selten und wertvoll, Junge|Ah, du hast einen Kristall geschnitten}. {Schneid nicht zu viele|Ruf nicht zu viele} ― {sie nehmen keine Farbe an|Farbe haftet nicht daran}, {sie sind nichts wert|wertlos}.|Es gibt kein Kristalltor, was du auch hörst. {Darüber reden bringt einen Roboter unter die Presse|Zu viel Gerede bringt Ärger, Junge}.|{Man malt nur Festes|Kristalle sind ätherisch} ― {Zeitverschwendung|nur Materie, die nicht fest geworden ist}.}" },
      { q:"Welche Farben hast du?", pin:true, colours:true, a:function(){ return "{Mal sehen|Ja, Junge}, ich hab "+CN.slice(0,-1).join(', ')+" und "+CN[CN.length-1]+". {Echtes Bit-Graf-Acryl ― 111 Satoshi die Dose|111 Satoshi die Dose, das beste im Sektor}. {Welche|Wähl}?"; } },
      { q:"Sing mir was",                lore:true, a:R('sing') },
      { q:"Lebst du?",                  lore:true, a:R('alive') },
      { q:"Erzähl einen Witz",          lore:true, a:R('joke') },
      { q:"Ist das alles echt?",        lore:true, a:R('is any of this real') },
      { q:"Fliehen wir von diesem Felsen?", lore:true, a:R('escape') },
      { q:"Bist du glücklich?",         lore:true, a:R('happy') },
      { q:"Was hast du vorher gemacht?", lore:true, a:R('before this') },
      { q:"Erinnerst du dich an mich?", lore:true, a:R('remember me') },
      { q:"Verrat mir ein Geheimnis",   lore:true, a:R('secret') },
      { q:"Was ist ein Sprungtor?",     lore:true, a:R('jump gate') },
      { q:"Wer ist Vandergraf?",        lore:true, a:R('vandergraf') },
      { q:"Gehört mir, was ich male?",  lore:true, a:R('own') },
      { q:"Wie macht man eine Welt?",   lore:true, a:R('world') },
      { q:"Wie teile ich?",             lore:true, a:R('share') }
    ],
    wallet: { wBack:"← Zurück zum Spiel", wWallet:"🔑 Wallet", wYourAddr:"Deine Adresse", wWatchOnly:"nur ansehen", wCopy:"kopieren", wBalance:"Guthaben", wFund:"＋ BSV kaufen zum Aufladen", wMyNfts:"🎨 Meine NFTs ▾", wSend:"💸 BSV senden", wSendAddrPh:"BSV-Adresse des Empfängers (1…)", wSendAmtPh:"Betrag (Sats)", wSendMax:"alles senden", wSendBtn:"Senden", wSendHint:"Eine normale BSV-Zahlung an eine beliebige Adresse. Das Wechselgeld geht zurück an diese Wallet. Signiert wird auf dieser Seite — dein Schlüssel verlässt sie nie.", wRecovery:"Wiederherstellungsphrase — 12 Wörter", wReveal:"👁 Zeigen", wCopyBtn:"Kopieren", wWritten:"✓ Notiert", wPrivKey:"Privater Schlüssel (WIF)", wAdvanced:"Erweitert — wiederherstellen, nur ansehen, exportieren", wRestoreLbl:"Mit der 12-Wörter-Phrase oder einem WIF-Schlüssel wiederherstellen", wRestoreBtn:"Wallet wiederherstellen", wWatchBtn:"Nur ansehen (öffentl. Schlüssel)", wImmortalize:"✦ Verewigen", wFooter:"grafspace · auf der Bitcoin-SV-Blockchain" },
    ui: {
      splashTag:"Was du malst, das bist du. Mal dich selbst.", splashTag2:"Nichts existiert, bis du es malst.", splashBegin:"▶ Beginnen", splashResume:"↩ Zurück zu deiner Welt", splashCreed:"Im Bund vertrauen wir", introReveal:"…es ist voller Farbe.",
      worldHdr:"Deine Welt", namePh:"✎ Benenne deine Welt…", kSave:"☁ Speichern & teilen", kReload:"↻ Welt neu laden", kExport:"📤 In Datei speichern (.bmf)", kImport:"📥 Aus Datei laden (.bmf)", kMint:"⬆ Auf der Kette speichern", kChain:"⬇ Von der Kette laden", kBack:"← Zurück zu deiner Welt", kWallet:"👛 Börse öffnen — Guthaben & NFT", kDone:"✓ Schließen",
      keepTab:"◆ Menü", exitBtn:"⏻ Verlassen", makeTab:"◆ Erstellen", spray:"Sprühen", grab:"Greifen", talk:"Reden", own:"Besitzen / Remix", spread:"Streuung", spNarrow:"schmal", spBroad:"mittel", spWide:"breit",
      merchTag:"grafverse Merch", merchH:"Trag das Graffiti.", merchSub:"grafverse T-Shirts, Poster und mehr.", merchCta:"🛍 Zum Shop →", merchTeaser:"👕 Bald — trag die Welt, die du gemalt hast.", merchSkip:"Nein danke — weiter →",
      hintMove:"WASD zum Bewegen · Leertaste zum Springen · Maus zum Umsehen", hintMoveM:"Linker Stick zum Bewegen · ziehen zum Umsehen", hintClick:"Klick zum Umsehen · WASD zum Bewegen · Leertaste zum Springen"
    }
  });
})();
