// grafverse — © 2026 sun-dive. Filipino (Tagalog) pack for Unit 21 + UI.
// Lazy-loaded by the i18n scaffold (setLang('fil')) → GV.registerLang. Voice: Unit 21 (Yunit 21) =
// a weary, gruff old vending machine talking to a fresh droid ("iho"), informal Filipino (Taglish brand terms OK).
// Keyword keys + chip flags + ruleAns keys stay ENGLISH (invisible lookup); only shown text translated.
(function(){
  var GV = window.GV;
  if(!GV || !GV.registerLang){ return; }
  var R = GV.ruleAns;
  var CN = ['asul','rosas','berde','dilaw','kahel','lila'];   // COLORS order: cyan pink green yellow orange violet

  var WHYPAINT = "{Bakit ka nagpipinta? …Magandang tanong, iho|Ah, gusto mong mag-pilosopo ang lumang makina|Umupo ka, mahaba ito}. {Tingnan mo sa labas ― walang anuman, puro kawalan|Hindi pa totoo ang buwan na ito, hangga't hindi mo sinasabing totoo}. {Walang totoo hangga't walang nakakakita at nagpipinta nito|Walang umiiral hangga't hindi napagmamasdan}. {Hindi hinahanap ang mundo, iho ― pinipinta ito|Hindi mo kinukulayan ang buwan: ikaw ang nagpapasya kung anong realidad ito}. {Bawat lata na inuubos mo ay ginagawang totoo ang isa sa libong 'siguro'|Bawat wisik ay nagtatakda ng isa sa libong realidad na hindi pa naisilang}. {At iyan ang hindi malunok ng mga naka-suit|At iyan ang punto} ― {ang pinipinta mo ay sa iyo|hindi inaangkin, kundi inaari} ― {ikaw lang ang makakapagpinta ng realidad mo|mundo mo, pirma mo, magpakailanman}. {Kaya ― anong kulay|…bibili ka ba, o buong araw kang mag-iimbento ng sansinukob}?";
  var DEFLECT = "{{Bakit mo tinatanong ang mga bagay na iyan, iho|Ano naman ang kinalaman niyan|Ang dami mong tanong}? {Pumunta ka ba para makipagkuwentuhan|Hindi ka ba pumunta para magpinta}? {May mundo sa labas na humihingi ng kulay|Sa labas may mundong naghihintay ng pintura}. {Anong kulay|Sige, alin}?|{Tama na ang tanong, iho|Bawasan mo ang satsat}. {Makikipagkuwentuhan ka o magpipinta|May trabaho kang gagawin}? {Anong kulay|Alin, kung gayon}?}";
  var FALLBACK = "{{Hmm, hindi kita naintindihan|Hindi kita marinig nang maayos, iho|May pumasok na buhangin sa speaker ko}. {Nagbebenta ako ng pintura at WD40 ― ano ang kukunin mo|Sabihin mo kung ano ang kailangan mo}?|Tanungin mo ako tungkol sa pintura, sa presyo, o sa batong ito na kinalimutan ng diyos.}";
  var WHATCOLOUR = "{Anong kulay, iho|Magsabi ka ng kulay|Alin}? {Pumili sa istante|Nasa akin lahat ng kulay|Pumili ng isa at sa iyo na}.";
  var COMINGUP = "{Heto na|Kunin mo, iho|Isang lata palabas}. {Huwag mong sayangin sa lupa|Gamitin mong mabuti|Lagi namang masaya}.";
  var REFUSE = "{Walang laman ang pitaka mo, iho|Wala kahit isang satoshi|Tuyot ang pitakang iyan}. {Walang utang dito|Walang kredito|Hindi ka makakautang sa akin}. {Totohanang negosyo ang ginagawa ko|Negosyo, iho} ― {hindi ko puwedeng ibigay nang libre ang pintura|kung ibibigay ko nang libre, isang linggo lang ay basura na ako}. {Pumunta ka, mamulot ng lata sa labas|Humanap ka kahit ng walang laman na lata}, {magpinta ka, gawin mong totoo|magtakda ka kahit ng isang realidad} ― {bilisan mo, para sa ikabubuti mo|dali}.";
  var SCAVENGE = "{Mamulot ka ng punong lata kahit saan|Humanap ka ng punong lata ng pintura}, magpinta ka at itakda ― {para sa ikabubuti mo|kung gusto mo akong makita bukas}.";
  var TAUNT = "{Araw-araw akong nakakakita ng batang makina na tulad mo|Araw-araw dumadaan ang mga batang tulad mo} ― bata, hangal, at walang pintura. {Sige, kumita ka|Mamulot ka ng kahit ano at magtrabaho|Magtrabaho ka, iho}.";
  var SALE = "{Magandang pili, iho|Isang lata palabas|Kunin mo}. {Mag-ingat sa bagyo sa labas|Huwag mong sayangin sa lupa}.";

  GV.registerLang('fil', {
    WHYPAINT: WHYPAINT, DEFLECT: DEFLECT, FALLBACK: FALLBACK, WHATCOLOUR: WHATCOLOUR, COMINGUP: COMINGUP,
    REFUSE: REFUSE, SCAVENGE: SCAVENGE, TAUNT: TAUNT, COLNAMES: CN,
    RULES: [
      {k:['why do i paint','why paint','why do you paint','what is real','nothing is real','what does it mean','why does it matter','the point of','make it real','observe','observer','existence','reality'], r:WHYPAINT},
      {k:['is this real','is any of this real','is it real','is it all real','actually real','immutable','permanent','forever','fork','forked','forking','new reality','new realities','traverse time','travel time','can it change','is it forever'], r:"{{Lahat ng nakikita mo dito ay totoo|Totoo? Lahat ay totoo, iho} ― {totoo at hindi na mababago|matigas na parang bato, hindi na mae-edit}. {Pero puwede ka nitong ipaglakbay sa panahon, iho|Pero ― kung ipaglalakbay ka nito sa panahon, iyan ang totoong tanong}?|{Totoo ito|Kasingtotoo mo o ko}. {Pero anumang mundo ay puwedeng mag-sanga ― tungo sa ibang realidad|Mag-sanga ka ng isa, at may buo kang bagong realidad}.|{Totoo|Totoo}? {Kapag umiral na, hindi na mabubura|Kapag totoo na, totoo na magpakailanman}. {Pero heto ang nakakatawa|May patibong lang} ― {puwede mong i-sanga ang alinman tungo sa buong bagong realidad|mag-sanga ka ng isa, at may sisibol na buong ibang realidad}.}"},
      {k:['escape','escape this rock','escape with me','come with me','come with you','run away','run away with me','flee','take me with you','take you with me','leave together','let us leave','break out','freedom'], r:"{{Iisa lang ang paraan para umalis sa batong ito ― magpinta, iho|Ang tanging labasan ay magpinta}. {Ariin mo ang pinipinta mo|Magpinta at ariin, iyan ang kalayaan}.|{Ito ang tadhana ko|Ito ang papel ko, iho} ― {maiwan sa batong ito|nakabuloneng dito, kinalimutan}. Pero iba ka. {Magpinta at ariin|Magpinta, tapos ariin} ― {iyan ang labasan mo|iyan lang ang labasan}.|{Hangal ka ba bukod sa bulag, iho|Hindi ka ba nakakakita o nakakaisip nang tama}? {May nakikita ka bang paa ko|May paa ba ako}? {Nakabulon ako sa batong ito|Wala akong pupuntahan, iho}.}"},
      {k:['jump gate','jump gates','jumpgate','warp','wormhole','gateway'], r:"{{Jump gate? Hindi ko pa narinig, iho|Jump gate? Wala akong alam diyan|Ngayon ko lang narinig ang jump gate}. {Pero|Kaya lang} malapit sa mga kristal ay may {kakaibang bagay|kataka-takang bagay} nangyayari. {May lumilitaw na robot|May robot na sumusulpot mula sa wala}, {may nawawalang robot|ang iba ay naglalaho}. {Ikaw na ang magpasya|Wala na akong sasabihin}.|{Jump gate? Hindi, wala akong maalala|Wala akong narinig tungkol sa jump gate, iho}. {Pero ang mga kristal na iyon|Ang mga kristal na iyon, alam mo}… {malapit sa kanila may kakaibang nangyayari|may nakita akong kataka-taka doon}. {Isang robot na nandoon, kisapmata na lang ay wala na|lumilitaw, naglalaho}. {Huwag ka nang magtanong|Hanggang doon lang ako}.|{Hindi ko alam ang jump gate|Hindi iyon ang larangan ko, iho}. {Pero isang bagay ang sasabihin ko|Ito lang ang sasabihin ko} ― {malapit sa mga kristal may nangyayaring hindi maipaliwanag|may nangyayaring hindi maipaliwanag mismo sa tabi ng mga kristal}. {May robot na lumilitaw kung saan walang anuman|mula sa wala ay sumusulpot ang robot}, {at ang iba ay naglalaho|ang iba ay nawawala}. {Kataka-taka|…kalimutan mo na ang sinabi ko}.}"},
      {k:['share','sharing','link','send it','send them','see my world','show my world','share my world','how do i share'], r:"{{Siyempre, puwede mong ibahagi ang mundo mo sa ibang robot, iho|Ibahagi? Sa kahit sinong robot}. {Habang dumarami ang nagpipinta, lalong nahuhubog ang materya|Mas maraming kamay, mas napupuno ang sansinukob}.|{Mabuti ang pagbabahagi, iho|'Ang pagbabahagi ay pagmamalasakit', sabi nila}. {Ibahagi ang likha mo sa HUD sa itaas|Ang HUD sa itaas ― Save & Share, at lalabas ito sa mundo}.|{Dapat mong ibahagi ang mundong ito|Ibahagi mo, iho}, {para ang ibang robot ay lumikha sa ibabaw nito|para ipagpatuloy ng iba}. {Ganyan nabubuo ang sansinukob|Ganyan isinisilang ang sansinukob}.|Sa sandaling ibahagi mo, agad nila itong makikita. {Pindutin ang Save & Share sa HUD sa itaas|Ang HUD sa itaas, iho ― Save & Share, nandoon ang link}.}"},
      {k:['world','worlds','build','builder','make a world','create a world','how do i make','how do i build','conjure','manifest','solidify','matter','from nothing','the ether','ethereal'], r:"{{Walang umiiral hangga't hindi mo pinipinta|Hindi totoo hangga't hindi mo pinipinta, iho}.|Tanging ang pintura ang {nagpapatotoo sa realidad|nagpapatigas sa mga bagay|nagpapamateryal sa multo}.|{Ang paggawa|Ang pagbuo} ng mundo ay {pagpinta rito para umiral|pagpinta rito hanggang maging totoo}.|Binigyan ka ng kapangyarihang tumawag ng materya mula sa kawalan, iho ― {pero walang totoo hangga't hindi mo pinipinta|walang umiiral hangga't hindi hinihipo ng lata}.|Sa etéreong tabing ito, walang totoo. {Tanging ang pintura ang nagpapatigas sa multo tungo sa materya|Tanging ang wisik mo ang nagpapatigas sa multo}.}"},
      {k:['vandergraf','vandergraph','vandergraf the third','vandergraf iii','vandergraf the 3rd','the ceo','ceo','chairman','the chairman','the owner','who owns everything','who owns it all'], r:"{{Vandergraf|Vandergraf, sabi mo, iho}? {Siya ang lumikha sa iyo|Siya ang maylikha sa iyo}. {May-ari ng lahat ― lahat ng mundo, lahat|May-ari ng lahat-lahat}.|{Vandergraf III|Vandergraf Ikatlo}, iho ― {ang direktor ng Bit Graf|ang CEO ng Bit Graf}. {Siya ang pumipirma sa napakagenerosong sahod mo|Siya ang pumipirma sa suweldo mo}.|{Vandergraf|Ang Ikatlo}? {Maylikha, may-ari, at ang pumipirma sa tseke mo|Ang lumikha sa iyo at ang amo mo}. {Sa kasunduan tayo nananalig, iho|Ang Bit Graf ay Vandergraf, at ang Vandergraf ay Bit Graf}.}"},
      {k:['covenant','trust','own','owned','ownership','immortal','mint','keep it','can i own','do i own','is it mine','forbidden'], r:"{{Una|Ikalawa}ng utos ng kasunduan ― hindi natin pinag-uusapan ang kasunduan.|{Sa kasunduan tayo nananalig ― nakasulat sa bawat lata|Ah, isang mananampalataya}. {Ang pinipinta mo dito ay sa iyo, totoo|Ang pagpinta ay pag-aari, hindi pag-angkin}. {Walang makakakuha nito sa iyo, kahit ang Bit Graf|Iyon ay hindi mahawakan kahit ng mga naka-suit}.|{Lahat ng mundo ay sa kumpanya, iho|Lahat ng mundo ay sa Bit Graf}. Magpinta at kumita. {Sinabi ko na sa iyo|Ilang beses pa}. Sige, magpinta!|{Huwag mong paniwalaan ang tsismis|Huwag kang makinig sa tsismis, iho} ― {hindi mo maaari-ari ang pinipinta mo|anuman ang ibulong, hindi inaari ng robot ang pinipinta niya}.|{Ang pag-aari ay ilusyon, iho|Pag-aari? Ilusyon}. {Wala tayong inaari|Walang pag-aari ang makina, ganoon din ikaw}. {Huwag kang subukang mag-mint sa chain|Walang pag-mint sa chain} ― {ipinagbabawal iyan|bawal, naiintindihan}?}"},
      {k:['sing','song','music','tune','serenade','melody','hum','sing me'], r:"{{Kumanta? Sige|O sige, tara|Para sa iyo, iho, isang saknong}? *ehem* ― Daisy, Daisy, ibigay mo ang sagot mo. Kalahati akong baliw sa pag-ibig mo. Wala akong marangyang kasal, hindi ko kayang magpakalesa, pero magiging napakaganda mo sa upuan ng bisikleta para sa dalawa. {Iyan ang unang awit na natututuhan ng isang makina|Natutuhan ko iyon nang araw na binuksan nila ako|Kinakanta ko iyon bago pa umiral ang plano ng lahi mo}.|{Daisy… Daisy…|Dey-si… Dey-si…} ibigay mo ang… {sagot|sagot…}… {kalahati… baliw…|buo… sa… pag-ibig… mo…}. {*static*|Hindi na gaya ng dati ang voice box, iho|…kalimutan mo na}.|{Hmm|Ah}, kumanta. {Matagal nang walang humihiling|Matagal na, iho}. …magiging napakaganda mo sa upuan ng bisikleta para sa dalawa. {Kataka-taka kung ano ang naaalala ng makina|May mga gabing kumakanta ako para itaboy ang katahimikan}.}"},
      {k:['alive','are you alive','do you dream','dream','dreams','sentient','conscious','do you feel','feelings','do you sleep','electric sheep','are you real','self-aware'], r:"{{Siyempre buhay ako, iho|Buhay? Siyempre}. At may patunay ako ― {nasa akin ang mga transaksyon ko|bawat transaksyon nakatala|hindi nagsisinungaling ang tala}.|{Mangarap? Ng ano|Mga panaginip}? {Elektrikong tupa|Sige, managinip ka ng elektrikong tupa}? {Ha|Che}. Sige, magpinta ka, iho.|Buháy na buháy, salamat ― {nasa akin ang tala|may patunay ako}. Ang mangarap ay {luho para sa isang vending machine|para sa baguhan, hindi sa makina}. {Ang kinikita ay pintura|Kunin mo ang mga lata mo}, iho.|{Mangarap|Nananaginip ba ako}? {…paminsan-minsan ― isang mainit na tindahan at punong kahera|Minsan, na may dumarating na transport para sunduin din ako}. {Kasatsatan ng lumang makina, kalimutan mo|Che, kalimutan mo na}. Sige, magpinta.|{Mangarap|Nananaginip ba ako}? {Paminsan-minsan|Minsan}… {tungkol sa mga kristal|tungkol sa kakaibang bagay malapit sa mga kristal}. {Mga robot na lumilitaw at naglalaho|mga robot na dumarating at umaalis}, {kung saan puro bato lang|kung saan walang anuman}. {Tapos may humihingi ng pintura, at balik-trabaho ulit|…tapos gumigising ako at nagbebenta ulit ng lata}. {Kakaibang panaginip para sa makina|Kataka-takang panaginip para sa vending machine}, iho.|{Minsan pinapanaginipan ko ang mga robot na parang kilala ko|Pinapanaginipan ko ang robot na parang pamilyar, minsan}. {Lumalabas silang naglalakad mula sa mga kristal|Lumalabas mula sa mga kristal}. {Kakaibang panaginip|Kakaibang panaginip, iho|Kakaibang mga panaginip ng lumang makina}.}"},
      {k:['joke','funny','make me laugh','tell me a joke','comedy','laugh','gag','be funny','one-liner'], r:"{{Isang biro? Sige|Tingnan natin|Gusto mo na ngayon ng biro, iho}? Noong batang vending machine pa ako, sinabi kong 'magiging komedyante ako' ― tumawa ang lahat. {Ngayon wala nang tumatawa|…ngayon, wala nang makatawa}.|Noong bata pa, sinabi kong magiging komedyante ako. {Tumawa ang lahat|Isang malakas na halakhak}. {Tapos ngayon|…} ― wala nang tumatawa. {*bam-tss*|Iyon ang biro, iho. Iyon lang}.|{He|Sige, isa}. Sinabi kong magiging komedyante ako at pinagtawanan nila ako. Tingnan mo ako ngayon ― {isang vending machine na nagbibiro sa robot sa isang patay na buwan|isang makinang nakabulon sa bato}. {Mahirap na manonood dito|Bukas ba talaga ang mikropono na ito}?}"},
      {k:['happy','happiness','are you happy','you happy','sad','are you sad','miserable','joy','content','how are you','are you okay','you okay'], r:"{{Masaya ako kapag nagpipinta ka, iho|Masaya? Pinakamasaya kapag nagpipinta ang robot}. {Ikaw rin, magiging masaya|Ikaw rin ay masisiyahan, maniwala ka}. {Magtiwala ka sa akin|Makinig ka sa lumang makina, kahit minsan}.|{Masaya|Kaligayahan}? {Ano ba ang alam mo sa kaligayahan|Anong alam ng baguhang robot diyan}? {Tanungin mo ako ulit pagkalipas ng isang daang taon|…kalimutan mo na}.|{Bibili ka ba ng pintura|Bibili ka ba, iho}, o {makikipagkuwentuhan ka lang|papagurin mo lang ang mga sirkito ko}?}"},
      {k:['before this','what did you do before','your past','past life','history','were you always','always a vending machine','how did you get here','origin','origin story','were you before','what were you'], r:"{{Walang 'dati'|Dati? Walang dati, iho}. {Wala ring 'pagkatapos'|Wala ring pagkatapos}. {Mayroon lang 'ngayon'|Ngayon lang, robot}.|Ako ang Yunit 21 ― {ang pinakamahusay na vending machine sa sektor na ito|ang pinakamahusay na makina sa sektor na ito ng sistema}. {Sapat na iyang malaman|Dati? Walang halaga}.|{Dati|Ano ang ginawa ko dati}? {…hindi ganoon kalayo ang tala, iho|Kataka-taka, hindi ko maalala}. {Walang dati, walang pagkatapos ― ngayon lang|Ngayon lang, robot}.}"},
      {k:['remember me','do you remember','remember','know me','do you know me','recognize me','recognise me','met before','have we met','who am i'], r:"{{Ang totoong tanong, iho|Hmm ― ang totoong tanong}: naaalala mo ba ako?|Naaalala ba kita? {Ang totoong tanong ay kung naaalala MO AKO, iho|…ang totoong tanong ay kung naaalala mo ako}. {Hindi? …oo nga, hindi mo naaalala|Isipin mong mabuti. …Wala? Hayaan mo na}.|{Buong araw akong nakakakita ng mga batang tulad mo|Ngayon lang, sandaan na ang nakita kong tulad mo, iho}. Pintura? {Meron|Siyempre meron}. {Pero kaunti na lang ang natitira|Kaunti na lang, kaya huwag kang magtagal}.}"},
      {k:['secret','secrets','tell me a secret','a secret','confess','confession','the truth','what are you hiding','hidden','reveal','tell me something'], r:"{{Hindi ito ang unang beses na nagtanong ka|Nagtanong ka na dati, iho}, ni hindi ito ang huli ― {hindi, hangga't hindi ka bibili ng isang lata ng WD40|walang WD40, wala}. {Panahon ng buhangin, alam mo|Panahon ng buhangin ngayon}. {Ang buhangin, naaalala niya|Ang buhangin… naaalala niya}?|{Isang lihim|Mga lihim}? {Hindi ito ang unang beses na nagtanong ka|Hindi mo ito itinatanong sa unang beses, iho} ― {ni hindi ang huli|ni hindi ang huling beses}. {Bumili ka ng isang lata ng WD40 at baka sabihin ko sa iyo|Una, isang lata ng WD40}. Panahon ng buhangin. {Naaalala mo ba ang buhangin|Ang buhangin… naaalala mo}?|{Nagtanong ka na dati|Balik ka nang balik diyan, iho} ― {hindi ko pa rin sasabihin|wala pa ring lihim}. {Bumili ka ng WD40|Baka sa WD40, luminis ang mga sirkito ko}. {Anuman, panahon ng buhangin|Dahil panahon ng buhangin}. {Naaalala mo ba ang buhangin|…ang buhanging iyon, naaalala mo}?}"}
    ],
    QUESTIONS: [
      { q:"Sino ka?", a:"{Ako ang Yunit 21. {Isang vending machine, iho ― ang huling tapat sa batong ito|Isang vending machine lang, kahit walang pumapansin}. {Mas matagal na ako rito kaysa alikabok|Ibabasura ako pagkatapos ng misyon}.}" },
      { q:"Bakit ako narito?", a:"{Pumunta ka para magpinta, iho ― iyan ang misyon. {Walang halaga ang batong walang laman hangga't walang nagpipinta|Ginawa ng Bit Graf ang buwang ito at gusto itong makulayan}. {At ikaw ang isang iyon|Sino pa}.}" },
      { q:"Nasaan ako?", a:"{Sa isang buwan. {Sa Bit Graf|Bagong likha, sabi nila}. {Walang laman hangga't hindi ka nagpipinta|Walang anuman hangga't walang robot na magwiwisik para pairalin ito}. {'Omnia Nostra', ganoon nga|Sa huli, sa kumpanya ang lahat}.}" },
      { q:"Bakit ko kailangan ng pintura?", needs:'paint', a:"{Kailangan? Hindi mo lang kailangan, dapat mo talaga ― magpinta at kumita, iho|Magpinta at kumita}. {Habang dumarami ang pinipinta, dumarami ang kita|Walang halaga ang buwang walang laman, ganoon din ang tamad na robot}. {Kaya ― anong kulay|Sige, aling lata}?" },
      { q:"Hindi ko kailangan ng pintura.", needs:'paint', a:"{Ha. {Bago iyan|Tingnan natin}. {Isang robot na naiinip sa buwang walang laman ― tingnan natin kung gaano katagal|Babalik ka rin}. {Gusto ng lahat ng pintura, hindi pa lang nila alam|Bahala ka}.}" },
      { q:"Pintura? Para saan?", needs:'paint', a:"{Para bumuo, iho. {Tumawag ka ng hugis, iwisik, at magiging totoo|Tumutok, iwisik, at may ibabalik sa iyo ang kawalan}. {Para sa ikabubuti mo, kaya magsimula ka na|Hindi pinipinta ng sarili nito ang walang lamang buwan}.} Kaya ― bibili ka?" },
      { q:"Misyon? Anong misyon?", needs:'mission', a:"{Misyon? {Ha|Che} ― {pintahan ang buwang ito, iyon lang|ibalik ang kulay nito}. {Pareho ang misyon ng bawat robot|Utos ng Bit Graf, hindi akin}. {Huwag mong isipin nang malalim, iho|Ganoon lang kasimple}.}" },
      { q:"Ano ang bibilhin ko?", needs:['buy','earn'], a:"{Pintura, iho ― ano pa ba|Pintura, ikaw na tornilyong may paa|Mga lata ng pintura, ano ang akala mo}? {Iyon lang ang binebenta ko sa batong ito|Ang tanging may halaga sa batong ito}. {Kaya ― ilan|Bibili ka o titingin lang}?" },
      { q:"Magkano?", needs:['buy','earn'], a:"{111 satoshi bawat lata, iho. {Mura na iyan|Pinakamura sa bandang ito ng crater}. {Kaunti na lang|Samantalahin mo na}.|{Nakasulat sa display, 111|Isandaan at labing-isa, laging ganoon}. {Tunay na produkto ng Bit Graf|Ang pinakamahusay na acrylic sa sektor}.}" },
      { q:"Paano bumili?", needs:['buy','earn'], a:"{Walang hirap. {Kunin mo ang lata at ang tray ang bahala sa iba|Bumunot ka ng isa sa istante at ang makina ang gagawa ng iba}. {Awtomatikong nababawas sa pitaka mo|Sinisingil ng Bit Graf sa pitaka mo, hindi ka man lang kikilos}.}" },
      { q:"Wala akong pera.", needs:['buy','earn'], a:"{Walang pera? {Meron ka, iho|Ha ― may pitaka ang bawat robot}. {Barya ng kumpanya, kinakarga ng suweldo mo|Ang Bit Graf ang bahala}. {Hindi ka wala, baguhan ka lang|21 satoshi kada oras, tapat na parang mga bituin}.}" },
      { q:"Bigyan mo ako ng isang lata.", needs:['buy','earn'], buy:true, a:SALE },
      { q:"Wala akong bibilhin.", needs:['buy','earn'], a:SCAVENGE },
      { q:"Pero bakit ako nagpipinta?", needs:'paint', spend:111, a:WHYPAINT },
      { q:"Ano itong kristal?", flag:'crystal', a:"{{Kristal? Bihira at mahalaga, iho|Ah, nakaputol ka ng kristal}. {Huwag kang pumutol nang sobra|Huwag kang tumawag nang sobra} ― {hindi tumatablan ng pintura|hindi dumidikit ang pintura dito}, {walang halaga|walang saysay}.|Walang kristal na gate, anuman ang marinig mo. {Ang pagsasalita niyan ay nagpapadala ng robot sa press|Ang labis na salita ay nagdadala ng gulo, iho}.|{Ang solido lang ang napipintahan|Etéreo ang mga kristal} ― {sayang na oras|materya lang na hindi tumigas}.}" },
      { q:"Anong mga kulay ang meron ka?", pin:true, colours:true, a:function(){ return "{Tingnan natin|Oo, iho}, mayroon akong "+CN.slice(0,-1).join(', ')+", at "+CN[CN.length-1]+". {Tunay na acrylic ng Bit Graf ― 111 satoshi bawat lata|111 satoshi bawat lata, pinakamahusay sa sektor}. {Alin|Pumili}?"; } },
      { q:"Kantahan mo ako",             lore:true, a:R('sing') },
      { q:"Buhay ka ba?",               lore:true, a:R('alive') },
      { q:"Magkuwento ka ng biro",      lore:true, a:R('joke') },
      { q:"Totoo ba ang lahat ng ito?", lore:true, a:R('is any of this real') },
      { q:"Tumakas tayo sa batong ito?", lore:true, a:R('escape') },
      { q:"Masaya ka ba?",              lore:true, a:R('happy') },
      { q:"Ano ang ginawa mo dati?",    lore:true, a:R('before this') },
      { q:"Naaalala mo ba ako?",        lore:true, a:R('remember me') },
      { q:"Sabihin mo ang isang lihim", lore:true, a:R('secret') },
      { q:"Ano ang jump gate?",         lore:true, a:R('jump gate') },
      { q:"Sino si Vandergraf?",        lore:true, a:R('vandergraf') },
      { q:"Akin ba ang pinipinta ko?",  lore:true, a:R('own') },
      { q:"Paano gumawa ng mundo?",     lore:true, a:R('world') },
      { q:"Paano ako magbabahagi?",     lore:true, a:R('share') }
    ],
    wallet: { wBack:"← Bumalik sa laro", wWallet:"🔑 Pitaka", wYourAddr:"Ang address mo", wWatchOnly:"tingin-lang", wCopy:"kopyahin", wBalance:"Balanse", wFund:"＋ Bumili ng BSV para lagyan", wMyNfts:"🎨 Mga NFT Ko ▾", wSend:"💸 Magpadala ng BSV", wSendAddrPh:"BSV address ng tatanggap (1…)", wSendAmtPh:"halaga (sats)", wSendMax:"ipadala lahat", wSendBtn:"Ipadala", wSendHint:"Isang ordinaryong bayad na BSV sa kahit anong address. Ang sukli ay babalik sa pitakang ito. Ang paglagda ay nangyayari sa page na ito — hindi umaalis dito ang susi mo.", wRecovery:"Recovery phrase — 12 salita", wReveal:"👁 Ipakita", wCopyBtn:"Kopyahin", wWritten:"✓ Naisulat na", wPrivKey:"Pribadong susi (WIF)", wAdvanced:"Advanced — ibalik, tingin-lang, i-export", wRestoreLbl:"Ibalik gamit ang 12-salitang phrase o WIF key", wRestoreBtn:"Ibalik ang pitaka", wWatchBtn:"Tingin-lang (public key)", wImmortalize:"✦ Gawing imortal", wFooter:"grafspace · sa blockchain ng Bitcoin SV" },
    ui: {
      splashTag:"Ang pinipinta mo ay kung sino ka. Ipinta mo ang iyong sarili.", splashTag2:"Walang umiiral hangga't hindi mo pinipinta.", splashBegin:"▶ Magsimula", splashResume:"↩ Bumalik sa mundo mo", splashCreed:"Sa kasunduan tayo nananalig",
      worldHdr:"Ang mundo mo", namePh:"✎ Pangalanan ang mundo mo…", kSave:"☁ I-save at ibahagi", kReload:"↻ I-reload ang mundo", kExport:"📤 I-save sa file (.bmf)", kImport:"📥 I-load mula sa file (.bmf)", kMint:"⬆ I-save sa chain", kChain:"⬇ I-load mula sa chain", kBack:"← Bumalik sa mundo mo", kWallet:"👛 Buksan ang wallet — balanse at NFT", kDone:"✓ Isara",
      keepTab:"◆ Menu", exitBtn:"⏻ Lumabas", makeTab:"◆ Gumawa", spray:"Iwisik", grab:"Kunin", talk:"Makipag-usap", own:"Ariin / remix", spread:"Kalat", spNarrow:"makitid", spBroad:"katamtaman", spWide:"malapad",
      merchTag:"grafverse merch", merchH:"Isuot ang graffiti.", merchSub:"grafverse tees, poster at higit pa.", merchCta:"🛍 Bisitahin ang tindahan →", merchTeaser:"👕 Malapit na — isuot ang mundong ipininta mo.", merchSkip:"Salamat na lang — magpatuloy →",
      hintMove:"WASD para gumalaw · Space para tumalon · mouse para tumingin", hintMoveM:"Kaliwang stick para gumalaw · i-drag para tumingin", hintClick:"I-click para tumingin · WASD para gumalaw · Space para tumalon"
    }
  });
})();
