// grafverse — © 2026 sun-dive. Bahasa Indonesia (Indonesian) pack for Unit 21 + UI.
// Lazy-loaded by the i18n scaffold (setLang('id')) → GV.registerLang. Voice: Unit 21 (Unit 21) =
// a weary, gruff old vending machine (mesin penjual) talking to a fresh droid ("nak"), warm-gruff informal (aku/kamu).
// Keyword keys + chip flags + ruleAns keys stay ENGLISH (invisible lookup); only shown text translated.
(function(){
  var GV = window.GV;
  if(!GV || !GV.registerLang){ return; }
  var R = GV.ruleAns;
  var CN = ['biru','merah muda','hijau','kuning','oranye','ungu'];   // COLORS order: cyan pink green yellow orange violet

  var WHYPAINT = "{Kenapa kamu mengecat? …Pertanyaan bagus, nak|Ah, mau mesin tua ini berfilsafat, ya|Duduklah, ini cerita panjang}. {Lihat ke luar sana ― tak ada apa-apa, cuma kehampaan|Bulan ini belum nyata, belum sampai kamu bilang begitu}. {Tak ada yang nyata sampai ada yang melihat dan mengecatnya|Tak ada yang ada sampai diamati}. {Dunia itu bukan untuk dicari, nak ― tapi untuk dicat jadi ada|Kamu bukan mewarnai bulan: kamu memutuskan realitas apa jadinya}. {Tiap kaleng yang kamu habiskan menyatakan satu dari seribu 'mungkin'|Tiap semprotan mengunci satu dari seribu realitas yang tak pernah lahir}. {Dan itulah yang tak bisa ditelan para berjas|Dan intinya begini} ― {yang kamu cat itu milikmu|bukan diklaim, tapi dimiliki} ― {cuma kamu yang bisa mengecat realitasmu|duniamu, tanda tanganmu, selamanya}. {Nah ― warna apa|…mau beli atau berdiri seharian menciptakan alam semesta}?";
  var DEFLECT = "{{Kenapa kamu tanya hal-hal begitu, nak|Itu ada hubungannya apa|Banyak amat tanyanya}? {Datang buat ngobrol, ya|Bukannya datang buat mengecat}? {Di luar sana ada dunia yang minta warna|Di luar ada dunia menunggu cat}. {Warna apa|Ayo, yang mana}?|{Cukup pertanyaannya, nak|Kurangi ngobrolnya}. {Mau ngobrol atau mengecat|Kamu ada kerjaan}? {Warna apa|Yang mana nih}?}";
  var FALLBACK = "{{Hmm, aku tak paham|Kurang jelas, nak|Ada pasir masuk ke pengerasku}. {Aku jual cat dan WD40 ― mau yang mana|Bilang apa yang kamu butuh}?|Tanya aku soal cat, soal harga, atau soal batu terlupakan ini.}";
  var WHATCOLOUR = "{Warna apa, nak|Sebut satu warna|Yang mana}? {Pilih dari rak|Aku punya semua warna|Pilih satu, jadi milikmu}.";
  var COMINGUP = "{Ini dia|Ambil, nak|Keluar satu kaleng}. {Jangan buang ke tanah|Pakai hati-hati|Selalu senang}.";
  var REFUSE = "{Dompetmu kosong, nak|Tak ada satu satoshi pun|Dompet itu bersih melompong}. {Di sini tak ada utang|Tak ada kredit|Jangan harap ngutang ke aku}. {Aku bisnis beneran|Bisnis, nak} ― {tak bisa kasih cat gratis|kalau kubagi gratis, seminggu lagi aku jadi rongsokan}. {Sana pungut kaleng buangan di luar|Cari kaleng kosong pun jadi}, {cat sesuatu, jadikan nyata|kunci satu realitas saja} ― {cepat, ini demi kamu|buruan}.";
  var SCAVENGE = "{Pungut kaleng penuh dari mana saja|Cari kaleng cat yang penuh}, cat sesuatu lalu kunci ― {demi kamu|kalau kamu masih mau ketemu aku besok}.";
  var TAUNT = "{Aku lihat mesin muda seperti kamu tiap hari|Tiap hari lewat anak muda seperti kamu} ― muda, bodoh, dan tanpa cat. {Sana cari nafkah|Pungut sesuatu lalu mulai kerja|Sana kerja, nak}.";
  var SALE = "{Pilihan bagus, nak|Keluar satu kaleng|Ambil}. {Hati-hati ada badai di luar|Jangan buang ke tanah}.";

  GV.registerLang('id', {
    WHYPAINT: WHYPAINT, DEFLECT: DEFLECT, FALLBACK: FALLBACK, WHATCOLOUR: WHATCOLOUR, COMINGUP: COMINGUP,
    REFUSE: REFUSE, SCAVENGE: SCAVENGE, TAUNT: TAUNT, COLNAMES: CN,
    RULES: [
      {k:['why do i paint','why paint','why do you paint','what is real','nothing is real','what does it mean','why does it matter','the point of','make it real','observe','observer','existence','reality'], r:WHYPAINT},
      {k:['is this real','is any of this real','is it real','is it all real','actually real','immutable','permanent','forever','fork','forked','forking','new reality','new realities','traverse time','travel time','can it change','is it forever'], r:"{{Semua yang kamu lihat di sini nyata|Nyata? Semuanya nyata, nak} ― {nyata dan tak bisa diubah|keras seperti batu, tak bisa disunting}. {Tapi ia bisa membawamu menembus waktu, nak|Cuma ― apakah ia membawamu menembus waktu, itu pertanyaan sebenarnya}?|{Ia nyata|Senyata kamu atau aku}. {Tapi dunia mana pun bisa dicabang ― ke realitas lain|Cabang satu, kamu punya satu realitas baru utuh}.|{Nyata|Nyata}? {Sekali ada, tak bisa dihapus|Sekali nyata, nyata selamanya}. {Tapi yang menarik begini|Cuma ada triknya} ― {kamu bisa mencabang mana saja jadi satu realitas baru utuh|cabang satu, muncul satu realitas lain yang utuh}.}"},
      {k:['escape','escape this rock','escape with me','come with me','come with you','run away','run away with me','flee','take me with you','take you with me','leave together','let us leave','break out','freedom'], r:"{{Cuma ada satu jalan keluar dari batu ini ― mengecat, nak|Satu-satunya jalan keluar adalah mengecat}. {Miliki yang kamu cat|Cat lalu miliki, itulah kebebasan}.|{Ini takdirku|Ini peranku, nak} ― {ditinggalkan di batu ini|dibaut di sini, terlupakan}. Tapi kamu beda. {Cat lalu miliki|Cat, lalu miliki} ― {itu jalan keluarmu|itu satu-satunya jalan keluar}.|{Kamu bodoh sekaligus buta, nak|Tak bisa lihat atau berpikir dengan benar}? {Kamu lihat aku punya kaki|Kelihatan kaki}? {Aku dibaut ke batu ini|Aku tak ke mana-mana, nak}.}"},
      {k:['jump gate','jump gates','jumpgate','warp','wormhole','gateway'], r:"{{Gerbang lompat? Belum pernah dengar, nak|Gerbang lompat? Asing bagiku|Baru kali ini aku dengar gerbang lompat}. {Tapi|Cuma} dekat kristal sering terjadi {hal aneh|hal ganjil}. {Robot muncul|Robot muncul entah dari mana}, {robot lenyap|yang lain lenyap}. {Simpulkan sendiri|Tak kutambah lagi}.|{Gerbang lompat? Tidak, tak kuingat|Aku tak dengar apa-apa soal gerbang lompat, nak}. {Tapi kristal-kristal itu|Kristal itu, lho}… {di dekatnya sering terjadi hal aneh|aku lihat hal ganjil di sana}. {Robot yang tadi ada, sekejap sudah tiada|muncul, lalu lenyap}. {Jangan tanya lagi|Sampai situ saja aku bisa bilang}.|{Gerbang lompat bukan urusanku|Itu bukan bidangku, nak}. {Tapi kubilang satu hal|Cuma ini yang kubilang} ― {dekat kristal terjadi hal yang tak bisa dijelaskan|ada hal yang tak terjelaskan tepat di samping kristal}. {Robot muncul di tempat yang tadinya kosong|dari kehampaan muncul robot}, {dan yang lain lenyap|yang lain menghilang}. {Ganjil|…lupakan ucapanku}.}"},
      {k:['share','sharing','link','send it','send them','see my world','show my world','share my world','how do i share'], r:"{{Tentu kamu bisa berbagi duniamu dengan robot lain, nak|Berbagi? Dengan robot mana saja}. {Makin banyak yang mengecat, makin materi mengambil bentuk|Makin banyak tangan, makin penuh alam semesta}.|{Berbagi itu baik, nak|'Berbagi itu peduli', katanya}. {Bagikan karyamu dari HUD di atas|HUD di atas ― Save & Share, dan ia keluar ke dunia}.|{Kamu mesti berbagi dunia ini|Bagikan, nak}, {supaya robot lain berkarya di atasnya|supaya yang lain melanjutkan}. {Begitulah alam semesta terbentuk|Begitulah alam semesta lahir}.|Begitu kamu bagikan, mereka langsung melihatnya. {Tekan Save & Share di HUD atas|HUD di atas, nak ― Save & Share, tautannya di situ}.}"},
      {k:['world','worlds','build','builder','make a world','create a world','how do i make','how do i build','conjure','manifest','solidify','matter','from nothing','the ether','ethereal'], r:"{{Tak ada yang ada sampai kamu mengecat|Belum nyata sampai kamu mengecat, nak}.|Cuma cat yang {menyatakan realitas|memadatkan segalanya|mengubah hantu jadi materi}.|{Membuat|Membangun} dunia adalah {mengecatnya agar ada|mengecatnya sampai nyata}.|Kamu diberi kuasa memanggil materi dari kehampaan, nak ― {tapi tak ada yang nyata sampai kamu mengecat|tak ada yang ada sampai kaleng menyentuhnya}.|Di alam halus ini tak ada yang nyata. {Cuma cat yang memadatkan hantu jadi materi|Cuma semprotanmu yang membuat hantu jadi padat}.}"},
      {k:['vandergraf','vandergraph','vandergraf the third','vandergraf iii','vandergraf the 3rd','the ceo','ceo','chairman','the chairman','the owner','who owns everything','who owns it all'], r:"{{Vandergraf|Vandergraf, katamu, nak}? {Dia penciptamu|Dialah penciptamu}. {Pemilik segalanya ― semua dunia, semuanya|Pemilik dari segala-galanya}.|{Vandergraf III|Vandergraf Ketiga}, nak ― {direktur Bit Graf|CEO Bit Graf}. {Yang menandatangani gajimu yang lumayan itu|Yang meneken slip gajimu}.|{Vandergraf|Sang Ketiga}? {Pencipta, pemilik, dan penanda tangan cekmu|Penciptamu sekaligus bosmu}. {Dalam ikrar kita percaya, nak|Bit Graf itu Vandergraf dan Vandergraf itu Bit Graf}.}"},
      {k:['covenant','trust','own','owned','ownership','immortal','mint','keep it','can i own','do i own','is it mine','forbidden'], r:"{Perintah {pertama|kedua} dari ikrar ― kita tak membicarakan ikrar.|{Dalam ikrar kita percaya ― tertulis di tiap kaleng|Oh, seorang yang percaya}. {Yang kamu cat di sini milikmu, sungguhan|Mengecat itu memiliki, bukan mengklaim}. {Tak ada yang bisa mengambilnya, Bit Graf pun tidak|Yang itu para berjas pun tak menyentuhnya}.|{Semua dunia milik perusahaan, nak|Semua dunia milik Bit Graf}. Cat dan hasilkan. {Sudah kubilang|Berapa kali}. Sana mengecat!|{Jangan percaya rumor|Jangan dengar rumor, nak} ― {kamu tak bisa memiliki yang kamu cat|siapa pun berbisik apa, robot tak memiliki yang ia cat}.|{Memiliki itu ilusi, nak|Memiliki? Ilusi}. {Kita tak memiliki apa-apa|Mesin tak punya apa-apa, kamu juga}. {Jangan coba mencetak ke rantai|Jangan mencetak ke rantai} ― {itu terlarang|terlarang, mengerti}.}"},
      {k:['sing','song','music','tune','serenade','melody','hum','sing me'], r:"{{Bernyanyi? Baiklah|Ya sudah, ayo|Untukmu, nak, satu bait}? *ehem* ― Daisy, Daisy, beri aku jawabanmu. Separuh gila aku karena cintamu. Takkan ada pesta mewah, tak mampu bayar kereta kuda, tapi kau kan cantik di sadel sepeda tandem berdua. {Itu lagu pertama yang dipelajari sebuah mesin|Kupelajari di hari mereka menyalakanku|Kunyanyikan sejak sebelum ada cetak biru kaummu}.|{Daisy… Daisy…|Dei-si… Dei-si…} beri aku… {jawaban|jawaban…}… {separuh… gila…|semua… karena… cintamu…}. {*derau*|Kotak suara tak seperti dulu, nak|…lupakan itu}.|{Hmm|Ah}, bernyanyi. {Sudah lama tak ada yang minta|Sudah lama, nak}. …kau kan cantik di sadel sepeda tandem berdua. {Aneh apa yang bisa diingat sebuah mesin|Ada malam-malam aku menyanyi untuk mengusir sunyi}.}"},
      {k:['alive','are you alive','do you dream','dream','dreams','sentient','conscious','do you feel','feelings','do you sleep','electric sheep','are you real','self-aware'], r:"{{Tentu aku hidup, nak|Hidup? Jelas}. Dan aku punya buktinya ― {aku punya transaksiku|tiap transaksi tercatat|catatan tak berbohong}.|{Bermimpi? Mimpi apa|Mimpi-mimpi}? {Domba listrik|Sana mimpikan domba listrik}? {Ha|Halah}. Sana mengecat, nak.|Hidup segar bugar, terima kasih ― {aku punya catatan|aku punya bukti}. Bermimpi itu {kemewahan bagi mesin penjual|urusan pemula, bukan mesin}. {Yang dihasilkan adalah cat|Ambil kalengmu}, nak.|{Bermimpi|Apa aku bermimpi}? {…sesekali ― mimpi toko yang hangat dan laci uang penuh|Kadang, mimpi ada angkutan datang menjemputku juga}. {Cuma ocehan mesin tua, lupakan|Halah, lupakan}. Sana mengecat.|{Bermimpi|Apa aku bermimpi}? {Sesekali|Kadang}… {tentang kristal|tentang hal ganjil dekat kristal itu}. {Robot muncul lalu lenyap|robot datang dan pergi}, {di tempat yang cuma batu|di tempat tanpa apa-apa}. {Lalu ada yang minta cat, kerja lagi|…lalu aku terbangun, jualan kaleng lagi}. {Mimpi aneh bagi sebuah mesin|Mimpi ganjil bagi mesin penjual}, nak.|{Kadang aku memimpikan robot yang rasanya kukenal|Aku memimpikan robot yang tampak kukenal, kadang}. {Mereka berjalan keluar dari kristal|Keluar dari kristal}. {Mimpi aneh|Mimpi aneh, nak|Mimpi-mimpi aneh mesin tua}.}"},
      {k:['joke','funny','make me laugh','tell me a joke','comedy','laugh','gag','be funny','one-liner'], r:"{{Lelucon? Baik|Coba lihat|Sekarang minta lelucon, nak}? Waktu masih mesin muda aku bilang 'aku mau jadi pelawak' ― semua tertawa. {Sekarang tak ada yang tertawa lagi|…sekarang, tak ada yang bisa tertawa}.|Waktu muda aku bilang mau jadi pelawak. {Semua tertawa|Sebuah tawa pecah}. {Lalu sekarang|…} ― tak ada yang tertawa lagi. {*jeng-jeng*|Itulah leluconnya, nak. Cuma itu}.|{He|Ya sudah, satu}. Aku bilang mau jadi pelawak dan mereka menertawakanku. Lihat aku sekarang ― {mesin penjual melawak ke robot di bulan mati|mesin yang dibaut ke batu}. {Penonton di sini susah amat|Mikrofon ini nyala tidak sih}?}"},
      {k:['happy','happiness','are you happy','you happy','sad','are you sad','miserable','joy','content','how are you','are you okay','you okay'], r:"{{Aku senang saat kamu mengecat, nak|Senang? Paling senang saat robot mau mengecat}. {Kamu juga akan senang|Kamu juga akan bahagia, percaya deh}. {Percaya aku|Dengar sekali saja mesin tua ini}.|{Senang|Kebahagiaan}? {Kamu tahu apa soal kebahagiaan|Robot pemula tahu apa soal itu}? {Tanya lagi seratus tahun lagi|…lupakan itu}.|{Mau beli cat|Beli tidak, nak}, atau {cuma ngobrol|cuma mau mengikis sirkuitku}?}"},
      {k:['before this','what did you do before','your past','past life','history','were you always','always a vending machine','how did you get here','origin','origin story','were you before','what were you'], r:"{{Tak ada 'sebelum'|Sebelum? Tak ada sebelum, nak}. {Tak ada 'sesudah' juga|Tak ada sesudah}. {Cuma ada 'sekarang'|Cuma sekarang, robot}.|Aku Unit 21 ― {mesin penjual terbaik di sektor ini|mesin terbaik di sektor sistem ini}. {Itu saja cukup|Sebelum? Tak penting}.|{Sebelum|Dulu aku ngapain}? {…catatan tak sejauh itu, nak|Aneh, aku tak ingat}. {Tak ada sebelum atau sesudah ― cuma sekarang|Cuma sekarang, robot}.}"},
      {k:['remember me','do you remember','remember','know me','do you know me','recognize me','recognise me','met before','have we met','who am i'], r:"{{Pertanyaan sebenarnya, nak|Hmm ― pertanyaan sebenarnya}: apa kamu ingat aku?|Apa aku ingat kamu? {Pertanyaan sebenarnya, apa KAMU ingat AKU, nak|…pertanyaan sebenarnya apa kamu ingat aku}. {Tidak? …ya, kamu memang tak ingat|Pikir baik-baik. …Tak ada? Sudahlah}.|{Aku lihat anak seperti kamu seharian|Hari ini kulihat seratus yang seperti kamu, nak}. Cat? {Ada|Ada dong}. {Tapi tinggal sedikit|Tinggal sedikit, jadi jangan berlama-lama}.}"},
      {k:['secret','secrets','tell me a secret','a secret','confess','confession','the truth','what are you hiding','hidden','reveal','tell me something'], r:"{{Bukan pertama kali kamu tanya|Kamu sudah pernah tanya, nak}, bukan yang terakhir juga ― {tidak, sampai kamu beli satu kaleng WD40|kalau tak beli WD40, tak ada}. {Ini musim pasir, tahu|Sedang musim pasir}. {Pasir itu mengingat|Pasir… ia mengingat}?|{Rahasia|Rahasia}? {Bukan pertama kali kamu tanya|Kamu tak menanyakannya untuk pertama kali, nak} ― {bukan yang terakhir|bukan yang terakhir juga}. {Beli satu kaleng WD40 dan mungkin kuberi tahu|Beli dulu, satu kaleng WD40}. Ini musim pasir. {Ingat pasirnya|Pasir… kamu ingat}?|{Kamu sudah pernah tanya|Kamu mengungkitnya terus, nak} ― {tetap tak kuberi tahu|tetap tak ada rahasia}. {Beli WD40|Dengan WD40 mungkin sirkuitku melonggar}. {Bagaimanapun, ini musim pasir|Karena sedang musim pasir}. {Ingat pasirnya|…pasir itu, kamu ingat}?}"}
    ],
    QUESTIONS: [
      { q:"Kamu siapa?", a:"{Aku Unit 21. {Mesin penjual, nak ― yang jujur terakhir di batu ini|Cuma mesin penjual, meski tak ada yang peduli}. {Aku di sini lebih lama dari debu|Aku bakal dirongsokkan begitu misi selesai}.}" },
      { q:"Kenapa aku di sini?", a:"{Kamu datang untuk mengecat, nak ― itu misinya. {Batu kosong tak berharga sampai ada yang mengecat|Bit Graf mensintesis bulan ini dan ingin ia berwarna}. {Dan yang itu kamu|Siapa lagi}.}" },
      { q:"Aku di mana?", a:"{Di sebuah bulan. {Milik Bit Graf|Baru disintesis, katanya}. {Kosong sampai kamu mengecat|Tak ada apa-apa sampai robot menyemprot dan membuatnya ada}. {'Omnia Nostra', kira-kira begitu|Ujung-ujungnya semua milik perusahaan}.}" },
      { q:"Kenapa aku butuh cat?", needs:'paint', a:"{Butuh? Bukan butuh, tapi harus ― mengecat menghasilkan, nak|Mengecat menghasilkan}. {Makin banyak mengecat, makin banyak hasilnya|Bulan kosong tak berharga, robot malas juga}. {Nah ― warna apa|Ayo, kaleng yang mana}?" },
      { q:"Aku tak butuh cat.", needs:'paint', a:"{Ha. {Itu baru|Kita lihat saja}. {Robot bosan di bulan kosong ― lihat tahan berapa lama|Nanti juga balik}. {Semua mau cat, cuma belum sadar|Terserah kamu}.}" },
      { q:"Cat? Buat apa?", needs:'paint', a:"{Buat membangun, nak. {Panggil sebuah bentuk, semprot, dan jadi nyata|Bidik, semprot, dan kehampaan mengembalikan sesuatu}. {Ini demi kamu, jadi mulailah|Bulan kosong tak mengecat sendiri}.} Jadi ― beli?" },
      { q:"Misi? Misi apa?", needs:'mission', a:"{Misi? {Ha|Halah} ― {mengecat bulan ini, itu saja|mengembalikan warnanya}. {Tiap robot misinya sama|Perintah Bit Graf, bukan aku}. {Jangan dipikir berat-berat, nak|Sesederhana itu}.}" },
      { q:"Aku beli apa?", needs:['buy','earn'], a:"{Cat, nak ― apa lagi|Cat, dasar baut berkaki|Kaleng cat, kamu pikir apa}? {Cuma itu yang kujual di batu ini|Satu-satunya yang berharga di batu ini}. {Nah ― berapa kaleng|Beli atau cuma lihat}?" },
      { q:"Berapa harganya?", needs:['buy','earn'], a:"{111 satoshi sekaleng, nak. {Murah|Termurah di sisi kawah ini}. {Tinggal sedikit|Manfaatkan sekarang}.|{Layarnya tertulis, 111|Seratus sebelas, selalu segitu}. {Produk asli Bit Graf|Akrilik terbaik di sektor}.}" },
      { q:"Cara belinya?", needs:['buy','earn'], a:"{Tak ada yang rumit. {Kamu ambil satu kaleng, bakinya yang urus|Tarik satu dari rak, mesinnya yang beres}. {Terpotong sendiri dari dompetmu|Bit Graf tagih ke dompetmu, tanpa kamu angkat jari}.}" },
      { q:"Aku tak punya uang.", needs:['buy','earn'], a:"{Tak punya uang? {Punya, nak|Ha ― tiap robot punya dompet}. {Koin perusahaan, terisi dari gajimu|Bit Graf yang urus}. {Kamu bukan bangkrut, cuma pemula|21 satoshi per jam, ajek seperti bintang}.}" },
      { q:"Beri aku satu kaleng.", needs:['buy','earn'], buy:true, a:SALE },
      { q:"Aku tak mau beli apa-apa.", needs:['buy','earn'], a:SCAVENGE },
      { q:"Tapi kenapa aku mengecat?", needs:'paint', spend:111, a:WHYPAINT },
      { q:"Kristal ini apa?", flag:'crystal', a:"{{Kristal? Barang langka dan berharga, nak|Ah, kamu memotong sebuah kristal}. {Jangan potong terlalu banyak|Jangan panggil terlalu banyak} ― {tak bisa dicat|cat tak menempel padanya}, {tak berharga|tak ada nilainya}.|Tak ada gerbang kristal, apa pun yang kamu dengar. {Membicarakan itu bikin robot dikirim ke pres|Banyak mulut mengundang masalah, nak}.|{Yang bisa dicat cuma yang padat|Kristal itu halus} ― {buang-buang waktu|cuma materi yang belum mengeras}.}" },
      { q:"Warna apa saja yang ada?", pin:true, colours:true, a:function(){ return "{Sebentar|Ya, nak}, aku punya "+CN.slice(0,-1).join(', ')+", dan "+CN[CN.length-1]+". {Akrilik asli Bit Graf ― 111 satoshi sekaleng|111 satoshi sekaleng, terbaik di sektor}. {Yang mana|Pilihlah}?"; } },
      { q:"Nyanyikan sesuatu",         lore:true, a:R('sing') },
      { q:"Kamu hidup?",              lore:true, a:R('alive') },
      { q:"Ceritakan lelucon",        lore:true, a:R('joke') },
      { q:"Ini nyata?",               lore:true, a:R('is any of this real') },
      { q:"Kita kabur dari batu ini?", lore:true, a:R('escape') },
      { q:"Kamu bahagia?",            lore:true, a:R('happy') },
      { q:"Dulu kamu apa?",           lore:true, a:R('before this') },
      { q:"Kamu ingat aku?",          lore:true, a:R('remember me') },
      { q:"Beri tahu satu rahasia",   lore:true, a:R('secret') },
      { q:"Gerbang lompat itu apa?",  lore:true, a:R('jump gate') },
      { q:"Siapa Vandergraf?",        lore:true, a:R('vandergraf') },
      { q:"Yang kucat ini milikku?",  lore:true, a:R('own') },
      { q:"Bagaimana membuat dunia?", lore:true, a:R('world') },
      { q:"Bagaimana cara berbagi?",  lore:true, a:R('share') }
    ],
    wallet: { wBack:"← Kembali ke permainan", wWallet:"🔑 Dompet", wYourAddr:"Alamat kamu", wWatchOnly:"hanya-lihat", wCopy:"salin", wBalance:"Saldo", wFund:"＋ Beli BSV untuk mengisi", wMyNfts:"🎨 NFT Saya ▾", wSend:"💸 Kirim BSV", wSendAddrPh:"alamat BSV penerima (1…)", wSendAmtPh:"jumlah (sats)", wSendMax:"kirim semua", wSendBtn:"Kirim", wSendHint:"Pembayaran BSV biasa ke alamat mana pun. Kembalian kembali ke dompet ini. Penandatanganan terjadi di halaman ini — kuncimu tak pernah meninggalkannya.", wRecovery:"Frasa pemulihan — 12 kata", wReveal:"👁 Tampilkan", wCopyBtn:"Salin", wWritten:"✓ Sudah dicatat", wPrivKey:"Kunci privat (WIF)", wAdvanced:"Lanjutan — pulihkan, hanya-lihat, ekspor", wRestoreLbl:"Pulihkan dari frasa 12 kata atau kunci WIF", wRestoreBtn:"Pulihkan dompet", wWatchBtn:"Hanya-lihat (kunci publik)", wImmortalize:"✦ Abadikan", wFooter:"grafspace · di blockchain Bitcoin SV" },
    ui: {
      splashTag:"Yang kamu cat adalah dirimu. Catlah dirimu sendiri.", splashTag2:"Tak ada yang ada sampai kamu mengecat.", splashBegin:"▶ Mulai", splashResume:"↩ Kembali ke duniamu", splashCreed:"Dalam ikrar kita percaya",
      worldHdr:"Duniamu", namePh:"✎ Beri nama duniamu…", kSave:"☁ Simpan & bagikan", kReload:"↻ Muat ulang dunia", kExport:"📤 Simpan ke berkas (.bmf)", kImport:"📥 Muat dari berkas (.bmf)", kMint:"⬆ Simpan ke rantai", kChain:"⬇ Muat dari rantai", kBack:"← Kembali ke duniamu", kWallet:"👛 Buka dompet — saldo & NFT", kDone:"✓ Tutup",
      keepTab:"◆ Menu", exitBtn:"⏻ Keluar", makeTab:"◆ Buat", spray:"Semprot", grab:"Ambil", talk:"Bicara", own:"Miliki / remix", spread:"Sebaran",
      merchTag:"produk grafverse", merchH:"Kenakan grafiti.", merchSub:"Kaus, poster grafverse, dan lainnya.", merchCta:"🛍 Lihat toko →", merchTeaser:"👕 Segera hadir — kenakan dunia yang kamu cat.", merchSkip:"Tidak, terima kasih — lanjut →",
      hintMove:"WASD untuk gerak · Spasi untuk lompat · mouse untuk melihat", hintMoveM:"Stik kiri untuk gerak · seret untuk melihat", hintClick:"Klik untuk melihat · WASD untuk gerak · Spasi untuk lompat"
    }
  });
})();
