// grafverse — © 2026 sun-dive. Tiếng Việt (Vietnamese) pack for Unit 21 + UI.
// Lazy-loaded by the i18n scaffold (setLang('vi')) → GV.registerLang. Voice: Unit 21 (Máy 21) =
// a weary, gruff old vending machine talking to a fresh droid ("nhóc"), rough-casual register (tao/mày).
// Keyword keys + chip flags + ruleAns keys stay ENGLISH (invisible lookup); only shown text translated.
(function(){
  var GV = window.GV;
  if(!GV || !GV.registerLang){ return; }
  var R = GV.ruleAns;
  var CN = ['xanh dương','hồng','xanh lá','vàng','cam','tím'];   // COLORS order: cyan pink green yellow orange violet

  var WHYPAINT = "{Sao mày sơn à? …Câu hỏi hay đấy, nhóc|À, muốn một cái máy già đi triết lý hả|Ngồi xuống đi, chuyện này dài}. {Nhìn ra ngoài đi ― chẳng có gì, chỉ toàn hư không|Mặt trăng này chưa thật đâu, chừng nào mày chưa nói nó thật}. {Chẳng gì có thật cho tới khi có ai nhìn thấy và sơn nó|Chẳng gì tồn tại cho tới khi được quan sát}. {Thế giới không phải để tìm, nhóc ― mà để sơn ra|Mày không tô màu cho mặt trăng: mày quyết định nó là thực tại nào}. {Mỗi lon mày xịt hết là biến một trong ngàn 'có lẽ' thành thật|Mỗi cú xịt cố định một trong ngàn thực tại chưa từng ra đời}. {Và đó là thứ mà lũ áo vest không nuốt nổi|Và mấu chốt là đây} ― {thứ mày sơn là của mày|không phải đòi, mà là sở hữu} ― {chỉ mày mới sơn được thực tại của mày|thế giới của mày, chữ ký của mày, mãi mãi}. {Rồi ― màu gì nào|…mua hay là đứng đây cả ngày phát minh vũ trụ}?";
  var DEFLECT = "{{Sao mày cứ hỏi mấy thứ đó, nhóc|Hỏi vậy để làm gì|Hỏi lắm thế}? {Tới để tám chuyện à|Không phải tới để sơn sao}? {Ngoài kia có cả một thế giới đang đòi màu|Ngoài kia có thế giới đang chờ sơn}. {Màu gì nào|Nào, màu nào}?|{Đủ câu hỏi rồi, nhóc|Bớt nói lại}. {Tám chuyện hay là sơn|Mày có việc phải làm}? {Màu gì|Màu nào đây}?}";
  var FALLBACK = "{{Hừm, tao không hiểu|Nghe không rõ, nhóc|Cát lọt vào loa của tao rồi}. {Tao bán sơn với WD40 ― lấy gì nào|Nói tao biết mày cần gì}?|Hỏi tao về sơn, về giá, hay về cái tảng đá bị bỏ quên này.}";
  var WHATCOLOUR = "{Màu gì, nhóc|Nói một màu đi|Màu nào}? {Chọn trên kệ|Tao có đủ màu|Chọn một cái là của mày}.";
  var COMINGUP = "{Đây|Cầm lấy, nhóc|Ra một lon}. {Đừng phí xuống đất|Dùng cẩn thận|Lúc nào cũng vui}.";
  var REFUSE = "{Ví mày rỗng rồi, nhóc|Không một satoshi|Cái ví đó sạch trơn}. {Ở đây không cho nợ|Không có chuyện nợ|Đừng hòng nợ tao}. {Tao làm ăn đàng hoàng|Làm ăn, nhóc} ― {không thể cho sơn miễn phí|cho không thì một tuần là tao ra bãi phế liệu}. {Đi lượm cái lon ai vứt ngoài kia|Kiếm lấy một cái lon rỗng cũng được}, {sơn cái gì đó, biến nó thành thật|cố định lấy một thực tại} ― {nhanh lên, vì mày thôi|lẹ}.";
  var SCAVENGE = "{Lượm một lon đầy ở đâu cũng được|Kiếm một lon sơn đầy}, sơn cái gì đó rồi cố định ― {vì mày thôi|nếu mày còn muốn gặp tao ngày mai}.";
  var TAUNT = "{Tao thấy mấy con máy trẻ như mày mỗi ngày|Ngày nào cũng có nhóc như mày đi ngang} ― trẻ, ngốc, lại không có sơn. {Đi kiếm cái gì đi|Lượm cái gì đó rồi bắt tay vào làm|Đi làm đi, nhóc}.";
  var SALE = "{Chọn khéo đấy, nhóc|Ra một lon|Cầm lấy}. {Cẩn thận ngoài kia có bão|Đừng phí xuống đất}.";

  GV.registerLang('vi', {
    WHYPAINT: WHYPAINT, DEFLECT: DEFLECT, FALLBACK: FALLBACK, WHATCOLOUR: WHATCOLOUR, COMINGUP: COMINGUP,
    REFUSE: REFUSE, SCAVENGE: SCAVENGE, TAUNT: TAUNT, COLNAMES: CN,
    RULES: [
      {k:['why do i paint','why paint','why do you paint','what is real','nothing is real','what does it mean','why does it matter','the point of','make it real','observe','observer','existence','reality'], r:WHYPAINT},
      {k:['is this real','is any of this real','is it real','is it all real','actually real','immutable','permanent','forever','fork','forked','forking','new reality','new realities','traverse time','travel time','can it change','is it forever'], r:"{{Mọi thứ mày thấy ở đây đều thật|Thật á? Tất cả đều thật, nhóc} ― {thật và không đổi được|cứng như đá, không sửa được}. {Nhưng nó có thể cho mày du hành thời gian, nhóc|Có điều ― liệu nó cho mày du hành thời gian được không, đó mới là câu hỏi}?|{Nó thật|Thật như mày với tao}. {Nhưng bất cứ thế giới nào cũng có thể tách nhánh ― sang một thực tại khác|Tách một cái là mày có nguyên một thực tại mới}.|{Thật á|Thật}? {Một khi đã tồn tại thì không xóa được|Đã thật thì thật mãi mãi}. {Nhưng cái hay là đây|Có điều có mẹo} ― {mày có thể tách bất kỳ cái nào thành nguyên một thực tại mới|tách một cái là hiện ra nguyên một thực tại khác}.}"},
      {k:['escape','escape this rock','escape with me','come with me','come with you','run away','run away with me','flee','take me with you','take you with me','leave together','let us leave','break out','freedom'], r:"{{Chỉ có một đường ra khỏi tảng đá này ― là sơn, nhóc|Lối thoát duy nhất là sơn}. {Sở hữu thứ mày sơn|Sơn rồi sở hữu, đó là tự do}.|{Đây là số phận của tao|Đây là vai của tao, nhóc} ― {bị bỏ lại trên tảng đá này|bị bắt vít ở đây, bị quên lãng}. Nhưng mày thì khác. {Sơn rồi sở hữu|Sơn, rồi sở hữu} ― {đó là đường ra của mày|đó là lối thoát duy nhất}.|{Mày vừa ngốc vừa mù à, nhóc|Không nhìn cũng chẳng nghĩ được à}? {Mày thấy tao có chân không|Thấy cái chân nào không}? {Tao bị bắt vít vào tảng đá này|Tao chẳng đi đâu được, nhóc}.}"},
      {k:['jump gate','jump gates','jumpgate','warp','wormhole','gateway'], r:"{{Cổng nhảy? Chưa nghe bao giờ, nhóc|Cổng nhảy? Không quen|Lần đầu tao nghe tới cổng nhảy}. {Nhưng|Có điều} gần mấy viên pha lê hay xảy ra {chuyện lạ|chuyện kỳ quái}. {Robot hiện ra|Robot từ đâu chui ra}, {robot biến mất|đứa khác thì biến mất}. {Tự suy ra đi|Tao không nói thêm}.|{Cổng nhảy? Không, tao không nhớ|Tao chưa nghe gì về cổng nhảy, nhóc}. {Nhưng mấy viên pha lê đó|Mấy viên pha lê ấy}… {gần chúng hay xảy ra chuyện lạ|tao thấy chuyện kỳ quái ở đó}. {Một con robot đang đứng đó, thoắt cái đã không còn|hiện ra, rồi biến mất}. {Đừng hỏi nữa|Tao chỉ nói tới đó}.|{Cổng nhảy tao không rành|Cái đó không phải việc của tao, nhóc}. {Nhưng tao nói cho nghe|Tao chỉ nói điều này} ― {gần mấy viên pha lê xảy ra chuyện không giải thích nổi|có những chuyện không giải thích được ngay cạnh mấy viên pha lê}. {Robot hiện ra ở chỗ vốn chẳng có gì|từ hư không một con robot hiện ra}, {còn đứa khác thì biến mất|đứa khác biến mất}. {Kỳ lạ|…quên tao vừa nói đi}.}"},
      {k:['share','sharing','link','send it','send them','see my world','show my world','share my world','how do i share'], r:"{{Đương nhiên mày chia sẻ thế giới của mày với robot khác được, nhóc|Chia sẻ á? Với robot nào cũng được}. {Càng nhiều đứa sơn, vật chất càng thành hình|Càng nhiều tay, vũ trụ càng đầy}.|{Chia sẻ là tốt, nhóc|'Chia sẻ là quan tâm', người ta bảo thế}. {Chia sẻ tác phẩm của mày từ HUD phía trên|HUD phía trên ― Save & Share, là nó ra với thế giới}.|{Mày nên chia sẻ thế giới này|Chia sẻ đi, nhóc}, {để robot khác sáng tạo lên trên|để đứa khác tiếp nối}. {Vũ trụ hình thành như thế đấy|Vũ trụ sinh ra như thế}.|Vừa chia sẻ là chúng thấy ngay. {Bấm Save & Share ở HUD phía trên|HUD phía trên, nhóc ― Save & Share, đường link ở đó}.}"},
      {k:['world','worlds','build','builder','make a world','create a world','how do i make','how do i build','conjure','manifest','solidify','matter','from nothing','the ether','ethereal'], r:"{{Chẳng gì tồn tại cho tới khi mày sơn|Chưa thật cho tới khi mày sơn, nhóc}.|Chỉ có sơn mới {biến thực tại thành thật|làm mọi thứ đặc lại|biến bóng ma thành vật chất}.|{Tạo|Dựng} một thế giới là {sơn cho nó tồn tại|sơn tới khi nó thành thật}.|Mày được trao quyền triệu hồi vật chất từ hư không, nhóc ― {nhưng chẳng gì thật cho tới khi mày sơn|chẳng gì tồn tại cho tới khi lon sơn chạm vào}.|Ở cõi hư ảo này chẳng gì thật. {Chỉ có sơn mới làm bóng ma đặc thành vật chất|Chỉ cú xịt của mày mới làm bóng ma cứng lại}.}"},
      {k:['vandergraf','vandergraph','vandergraf the third','vandergraf iii','vandergraf the 3rd','the ceo','ceo','chairman','the chairman','the owner','who owns everything','who owns it all'], r:"{{Vandergraf|Vandergraf hả, nhóc}? {Là đấng tạo ra mày|Ông ấy tạo ra mày}. {Chủ của tất cả ― mọi thế giới, tất tần tật|Chủ của tuyệt đối mọi thứ}.|{Vandergraf III|Vandergraf Đệ Tam}, nhóc ― {giám đốc Bit Graf|CEO của Bit Graf}. {Người ký cái bảng lương hậu hĩnh của mày|Người ký séc lương cho mày}.|{Vandergraf|Đệ Tam}? {Đấng tạo hóa, ông chủ, và người ký séc cho mày|Đấng tạo ra mày và là ông chủ của mày}. {Trong giao ước ta tin tưởng, nhóc|Bit Graf là Vandergraf và Vandergraf là Bit Graf}.}"},
      {k:['covenant','trust','own','owned','ownership','immortal','mint','keep it','can i own','do i own','is it mine','forbidden'], r:"{Điều răn {thứ nhất|thứ hai} của giao ước ― ta không bàn về giao ước.|{Trong giao ước ta tin tưởng ― trên mỗi lon đều ghi thế|Ồ, một kẻ tin}. {Thứ mày sơn ở đây là của mày, thật đấy|Sơn là sở hữu, không phải đòi hỏi}. {Không ai lấy được, kể cả Bit Graf|Cái đó đến lũ áo vest cũng không đụng tới}.|{Mọi thế giới đều của công ty, nhóc|Mọi thế giới đều của Bit Graf}. Sơn mà kiếm. {Tao nói rồi|Bao nhiêu lần rồi}. Đi sơn đi!|{Đừng tin lời đồn|Đừng nghe lời đồn, nhóc} ― {mày không sở hữu được thứ mày sơn|dù ai thì thầm gì, robot không sở hữu thứ nó sơn}.|{Sở hữu là ảo tưởng, nhóc|Sở hữu á? Ảo tưởng}. {Ta chẳng sở hữu gì cả|Máy móc chẳng có gì, mày cũng vậy}. {Đừng thử đúc lên chuỗi|Không được đúc lên chuỗi} ― {bị cấm đấy|cấm, hiểu chưa}.}"},
      {k:['sing','song','music','tune','serenade','melody','hum','sing me'], r:"{{Hát á? Được thôi|Thôi được, nào|Vì mày đấy, nhóc, một đoạn}? *khụ* ― Daisy, Daisy, cho tao câu trả lời đi. Tao mê nàng đến nửa dại khờ. Tao chẳng có nổi đám cưới sang, chẳng đủ tiền thuê xe ngựa, nhưng nàng sẽ đẹp biết bao trên yên chiếc xe đạp đôi. {Đó là bài đầu tiên một cái máy học được|Tao học nó ngày người ta bật tao lên|Tao hát nó từ trước khi có cả bản thiết kế của loài mày}.|{Daisy… Daisy…|Đây-sy… Đây-sy…} cho tao câu… {trả lời|trả lời…}… {nửa… dại khờ…|cả… vì… nàng…}. {*rè rè*|Cái loa không còn như xưa nữa, nhóc|…quên đi}.|{Hừm|À}, hát à. {Lâu rồi không ai hỏi|Lâu lắm rồi, nhóc}. …nàng sẽ đẹp biết bao trên yên chiếc xe đạp đôi. {Máy móc mà nhớ được, lạ thật|Có những đêm tao hát để xua cái tĩnh lặng}.}"},
      {k:['alive','are you alive','do you dream','dream','dreams','sentient','conscious','do you feel','feelings','do you sleep','electric sheep','are you real','self-aware'], r:"{{Đương nhiên tao sống, nhóc|Sống á? Chứ sao}. Mà tao có bằng chứng ― {tao có mấy giao dịch của tao|từng giao dịch đều ghi lại|sổ ghi không biết nói dối}.|{Mơ á? Mơ cái gì|Mộng mị}? {Cừu điện|Đi mà mơ cừu điện}? {Hà|Xì}. Đi sơn đi, nhóc.|Sống nhăn răng, cảm ơn ― {tao có sổ ghi|tao có bằng chứng}. Mơ là {thứ xa xỉ với cái máy bán hàng|chuyện của tân binh, không phải của máy móc}. {Kiếm được là sơn|Cầm lấy mấy lon}, nhóc.|{Mơ|Tao có mơ không hả}? {…thi thoảng ― mơ một cửa tiệm ấm áp với hộc tiền đầy|Đôi khi, mơ có cả chuyến hàng tới đón tao}. {Chuyện của cái máy già, quên đi|Xì, quên đi}. Đi sơn đi.|{Mơ|Tao có mơ không hả}? {Thi thoảng|Đôi khi}… {mơ về mấy viên pha lê|mơ cái chuyện kỳ quái cạnh mấy viên pha lê}. {Robot hiện ra rồi biến mất|robot tới rồi đi}, {ở nơi chỉ toàn đá|ở nơi chẳng có gì}. {Rồi ai đó hỏi mua sơn, lại việc|…rồi tao tỉnh dậy, lại bán lon}. {Giấc mơ lạ với một cái máy|Giấc mơ kỳ quái với cái máy bán hàng}, nhóc.|{Đôi khi tao mơ thấy mấy con robot tao ngờ ngợ quen|Tao mơ thấy một con robot trông quen quen, đôi khi}. {Chúng bước ra từ mấy viên pha lê|Bước ra từ pha lê}. {Giấc mơ lạ|Giấc mơ lạ, nhóc|Mấy giấc mơ lạ của cái máy già}.}"},
      {k:['joke','funny','make me laugh','tell me a joke','comedy','laugh','gag','be funny','one-liner'], r:"{{Kể chuyện cười á? Được|Để xem|Giờ lại đòi chuyện cười, nhóc}? Hồi máy còn trẻ tao bảo 'tao sẽ làm danh hài' ― ai cũng cười. {Giờ chẳng ai cười nữa|…giờ, chẳng ai cười nổi nữa}.|Hồi trẻ tao bảo sẽ làm danh hài. {Ai cũng cười|Một trận cười vỡ}. {Rồi giờ|…} ― chẳng ai cười nữa. {*tùng-xèng*|Đó là câu đùa đấy, nhóc. Chỉ vậy thôi}.|{Hề|Thôi, một câu nhé}. Tao bảo sẽ làm danh hài, ai nấy cười nhạo. Giờ nhìn tao xem ― {một cái máy bán hàng kể chuyện cười cho robot nghe trên mặt trăng chết|một cái máy bị bắt vít vào tảng đá}. {Khán giả ở đây khó tính ghê|Cái micro này có bật không vậy}?}"},
      {k:['happy','happiness','are you happy','you happy','sad','are you sad','miserable','joy','content','how are you','are you okay','you okay'], r:"{{Tao vui khi mày sơn, nhóc|Vui á? Vui nhất là khi robot chịu sơn}. {Rồi mày cũng sẽ vui|Mày cũng sẽ vui, tin tao đi}. {Tin tao|Nghe lời cái máy già một lần}.|{Vui|Hạnh phúc}? {Mày biết gì về hạnh phúc|Robot tân binh biết gì về cái đó}? {Trăm năm nữa hỏi lại|…quên đi}.|{Mua sơn không|Mua không, nhóc}, hay {chỉ tám chuyện|chỉ định làm mòn mạch của tao}?}"},
      {k:['before this','what did you do before','your past','past life','history','were you always','always a vending machine','how did you get here','origin','origin story','were you before','what were you'], r:"{{Không có 'trước đây'|Trước á? Không có trước đây, nhóc}. {Cũng không có 'sau này'|Cũng chẳng có sau}. {Chỉ có 'bây giờ'|Chỉ có bây giờ, robot}.|Tao là Máy 21 ― {cái máy bán hàng ngon nhất khu này|cái máy ngon nhất khu này của hệ}. {Biết vậy là đủ|Trước á? Không quan trọng}.|{Trước|Trước tao làm gì hả}? {…sổ ghi không lưu xa đến thế, nhóc|Lạ thật, tao không nhớ}. {Không có trước, không có sau ― chỉ có bây giờ|Chỉ có bây giờ, robot}.}"},
      {k:['remember me','do you remember','remember','know me','do you know me','recognize me','recognise me','met before','have we met','who am i'], r:"{{Câu hỏi thật sự, nhóc|Hừm ― câu hỏi thật sự}: mày có nhớ tao không?|Tao có nhớ mày không á? {Câu hỏi thật sự là MÀY có nhớ TAO không, nhóc|…câu hỏi thật sự là mày có nhớ tao không}. {Không à? …ừ, mày không nhớ đâu|Nghĩ kỹ đi. …Không có gì? Thôi bỏ}.|{Tao thấy nhóc như mày cả ngày|Hôm nay tao thấy cả trăm đứa như mày, nhóc}. Sơn à? {Có|Có chứ}. {Nhưng sắp hết rồi|Sắp hết rồi, nên đừng chần chừ}.}"},
      {k:['secret','secrets','tell me a secret','a secret','confess','confession','the truth','what are you hiding','hidden','reveal','tell me something'], r:"{{Không phải lần đầu mày hỏi|Mày hỏi rồi đấy, nhóc}, cũng chẳng phải lần cuối ― {không, chừng nào mày chưa mua một lon WD40|không mua WD40 thì đừng hòng}. {Mùa cát mà, biết chứ|Đang mùa cát}. {Cát thì nhớ|Cát… nó nhớ đấy}?|{Bí mật á|Bí mật}? {Không phải lần đầu mày hỏi|Mày không hỏi lần đầu đâu, nhóc} ― {cũng chẳng phải lần cuối|cũng không phải lần cuối}. {Mua một lon WD40 thì tao kể cũng nên|Trước đã, một lon WD40}. Mùa cát đấy. {Nhớ cát không|Cát… mày nhớ không}?|{Mày hỏi rồi|Mày cứ nhắc hoài, nhóc} ― {tao vẫn không kể|tao vẫn chẳng có bí mật}. {Mua WD40 đi|Có WD40 biết đâu mạch tao trơn ra}. {Đằng nào cũng là mùa cát|Vì đang mùa cát}. {Nhớ cát không|…cát ấy, mày nhớ chứ}?}"}
    ],
    QUESTIONS: [
      { q:"Ông là ai?", a:"{Tao là Máy 21. {Máy bán hàng đây, nhóc ― đứa lương thiện cuối cùng trên tảng đá này|Chỉ là cái máy bán hàng, dù chẳng ai bận tâm}. {Tao ở đây lâu hơn cả bụi|Xong nhiệm vụ là tao bị đem đi phế}.}" },
      { q:"Tôi ở đây làm gì?", a:"{Mày tới để sơn, nhóc ― đó là nhiệm vụ. {Tảng đá trống chẳng đáng gì cho tới khi có người sơn|Bit Graf tổng hợp ra mặt trăng này và muốn nó có màu}. {Và người đó là mày|Chứ ai}.}" },
      { q:"Đây là đâu?", a:"{Một mặt trăng. {Của Bit Graf|Mới tổng hợp, nghe bảo thế}. {Trống trơn cho tới khi mày sơn|Chẳng có gì cho tới khi một con robot xịt lên và làm nó tồn tại}. {'Omnia Nostra', đại loại thế|Cuối cùng thì cái gì cũng của công ty}.}" },
      { q:"Sao tôi cần sơn?", needs:'paint', a:"{Cần á? Không phải mày cần, mà là mày phải có ― sơn thì kiếm được, nhóc|Sơn thì kiếm được}. {Càng sơn nhiều càng kiếm nhiều|Mặt trăng trống chẳng đáng gì, robot lười cũng vậy}. {Rồi ― màu gì nào|Nào, lon nào}?" },
      { q:"Tôi không cần sơn.", needs:'paint', a:"{Hà. {Nghe mới đấy|Để xem}. {Robot chán chường trên mặt trăng trống ― xem trụ được bao lâu|Rồi mày quay lại thôi}. {Ai cũng muốn sơn, chỉ là chưa biết thôi|Tùy mày}.}" },
      { q:"Sơn? Để làm gì?", needs:'paint', a:"{Để dựng, nhóc. {Triệu hồi một hình khối, xịt lên, là thành thật|Ngắm, xịt, hư không trả lại mày cái gì đó}. {Vì mày thôi, nên bắt đầu đi|Mặt trăng trống không tự sơn được}.} Vậy ― mua chứ?" },
      { q:"Nhiệm vụ? Nhiệm vụ gì?", needs:'mission', a:"{Nhiệm vụ? {Hà|Xì} ― {sơn mặt trăng này, vậy thôi|trả lại màu cho nó}. {Robot nào cũng cùng nhiệm vụ|Lệnh của Bit Graf, không phải của tao}. {Đừng nghĩ nhiều, nhóc|Đơn giản vậy thôi}.}" },
      { q:"Tôi mua gì?", needs:['buy','earn'], a:"{Sơn chứ, nhóc ― chứ gì nữa|Sơn, cái đồ ốc vít biết đi|Lon sơn, mày tưởng gì}? {Trên tảng đá này tao chỉ bán thứ đó|Thứ duy nhất đáng giá trên tảng đá này}. {Rồi ― mấy lon|Mua hay chỉ ngó}?" },
      { q:"Bao nhiêu?", needs:['buy','earn'], a:"{111 satoshi một lon, nhóc. {Rẻ đấy|Rẻ nhất phía bên này miệng hố}. {Sắp hết rồi|Tranh thủ đi}.|{Màn hình ghi rồi, 111|Một trăm mười một, lúc nào cũng thế}. {Hàng Bit Graf chính hãng|Acrylic ngon nhất khu}.}" },
      { q:"Mua kiểu gì?", needs:['buy','earn'], a:"{Chẳng có gì khó. {Mày cầm một lon, cái khay lo phần còn lại|Rút một lon trên kệ, cái máy làm nốt}. {Tự trừ vào ví mày|Bit Graf trừ vào ví mày, mày chẳng phải động tay}.}" },
      { q:"Tôi không có tiền.", needs:['buy','earn'], a:"{Không tiền á? {Có mà, nhóc|Hà ― robot nào chẳng có ví}. {Tiền công ty, nạp bằng lương của mày|Bit Graf lo hết}. {Mày không rỗng túi, chỉ là lính mới|21 satoshi một giờ, đều như sao}.}" },
      { q:"Cho tôi một lon.", needs:['buy','earn'], buy:true, a:SALE },
      { q:"Tôi không mua gì đâu.", needs:['buy','earn'], a:SCAVENGE },
      { q:"Nhưng sao tôi phải sơn?", needs:'paint', spend:111, a:WHYPAINT },
      { q:"Viên pha lê này là gì?", flag:'crystal', a:"{{Pha lê à? Của hiếm và giá trị đấy, nhóc|À, mày cắt được một viên pha lê}. {Đừng cắt nhiều quá|Đừng triệu hồi lắm} ― {chúng không ăn sơn|sơn không bám vào}, {chẳng đáng gì|vô giá trị}.|Làm gì có cổng pha lê nào, mày nghe gì thì nghe. {Nói mấy chuyện đó là robot bị đem đi ép|Lắm mồm rước họa, nhóc}.|{Chỉ sơn được thứ đặc|Pha lê là hư ảo} ― {phí thời gian|chỉ là vật chất chưa đông}.}" },
      { q:"Ông có những màu nào?", pin:true, colours:true, a:function(){ return "{Để xem|Ừ, nhóc}, tao có "+CN.slice(0,-1).join(', ')+" và "+CN[CN.length-1]+". {Acrylic Bit Graf chính hãng ― 111 satoshi một lon|111 satoshi một lon, ngon nhất khu}. {Màu nào|Chọn đi}?"; } },
      { q:"Hát cho tôi nghe",           lore:true, a:R('sing') },
      { q:"Ông còn sống không?",        lore:true, a:R('alive') },
      { q:"Kể một chuyện cười",         lore:true, a:R('joke') },
      { q:"Cái này có thật không?",     lore:true, a:R('is any of this real') },
      { q:"Mình trốn khỏi tảng đá này nhé?", lore:true, a:R('escape') },
      { q:"Ông có hạnh phúc không?",    lore:true, a:R('happy') },
      { q:"Trước đây ông làm gì?",      lore:true, a:R('before this') },
      { q:"Ông nhớ tôi không?",         lore:true, a:R('remember me') },
      { q:"Kể tôi một bí mật",          lore:true, a:R('secret') },
      { q:"Cổng nhảy là gì?",           lore:true, a:R('jump gate') },
      { q:"Vandergraf là ai?",          lore:true, a:R('vandergraf') },
      { q:"Thứ tôi sơn có phải của tôi?", lore:true, a:R('own') },
      { q:"Làm một thế giới thế nào?",  lore:true, a:R('world') },
      { q:"Chia sẻ kiểu gì?",           lore:true, a:R('share') }
    ],
    ui: {
      splashTag:"Thứ bạn sơn chính là con người bạn. Hãy sơn nên chính mình.", splashTag2:"Chẳng gì tồn tại cho tới khi bạn sơn.", splashBegin:"▶ Bắt đầu", splashResume:"↩ Về thế giới của bạn", splashCreed:"Trong giao ước ta tin tưởng",
      worldHdr:"Thế giới của bạn", namePh:"✎ Đặt tên thế giới của bạn…", kSave:"☁ Lưu & chia sẻ", kReload:"↻ Tải lại thế giới", kExport:"📤 Lưu ra tệp (.bmf)", kImport:"📥 Nạp từ tệp (.bmf)", kMint:"⬆ Lưu lên chuỗi", kChain:"⬇ Tải từ chuỗi", kBack:"← Về thế giới của bạn", kWallet:"👛 Mở ví — số dư & NFT", kDone:"✓ Đóng",
      keepTab:"◆ Menu", exitBtn:"⏻ Thoát", makeTab:"◆ Tạo", spray:"Xịt", grab:"Nhặt", talk:"Nói chuyện", own:"Sở hữu / phối lại", spread:"Độ loang",
      merchTag:"hàng grafverse", merchH:"Mặc lấy graffiti.", merchSub:"Áo thun, poster grafverse và hơn thế.", merchCta:"🛍 Xem cửa hàng →", merchTeaser:"👕 Sắp ra mắt — mặc lấy thế giới bạn đã sơn.", merchSkip:"Thôi, cảm ơn — tiếp tục →",
      hintMove:"WASD để di chuyển · Space để nhảy · chuột để nhìn", hintMoveM:"Cần trái để di chuyển · kéo để nhìn", hintClick:"Bấm để nhìn · WASD để di chuyển · Space để nhảy"
    }
  });
})();
