// grafverse — © 2026 sun-dive. Português (Brasil) pack for Unit 21 + UI.
// Lazy-loaded by the i18n scaffold (setLang('pt-BR')) → GV.registerLang. Voice: Unit 21 (Unidade 21) =
// a weary, gruff old vending machine talking to a fresh droid ("moleque"), informal Brazilian speech (você/tu mix, casual).
// Keyword keys + chip flags + ruleAns keys stay ENGLISH (invisible lookup); only shown text translated.
(function(){
  var GV = window.GV;
  if(!GV || !GV.registerLang){ return; }
  var R = GV.ruleAns;
  var CN = ['azul','rosa','verde','amarelo','laranja','roxo'];   // COLORS order: cyan pink green yellow orange violet

  var WHYPAINT = "{Por que você pinta? …Boa pergunta, moleque|Ah, quer que uma máquina velha fique filosófica|Senta aí, que essa é longa}. {Olha lá fora ― não tem nada, só o vazio|Essa lua ainda não é real, não até você dizer que é}. {Nada é real até alguém ver e pintar|Nada existe até ser observado}. {Um mundo não se acha, moleque ― se pinta|Você não dá cor pra lua: você decide que realidade ela vai ser}. {Cada lata que você esvazia torna real um entre mil 'talvez'|Cada jato fixa uma entre mil realidades que nunca nasceram}. {E é isso que os engravatados não engolem|E o lance é esse} ― {o que você pinta é seu|não se reivindica, se possui} ― {só você pode pintar a sua realidade|seu mundo, sua assinatura, pra sempre}. {E aí ― de que cor|…vai comprar ou vai passar o dia todo inventando universo}?";
  var DEFLECT = "{{Por que você pergunta essas coisas, moleque|E isso lá vem ao caso|Quanta pergunta}? {Veio pra bater papo|Não veio pintar}? {Tem um mundo lá fora pedindo cor|Lá fora tem um mundo esperando tinta}. {De que cor|Vai, qual}?|{Chega de pergunta, moleque|Menos conversa}. {Vai conversar ou pintar|Você tem trabalho a fazer}? {De que cor|Qual vai ser}?}";
  var FALLBACK = "{{Hã, não entendi|Não te ouço direito, moleque|Entrou areia no meu alto-falante}. {Vendo tinta e WD40 ― o que vai ser|Diz o que você precisa}?|Me pergunta sobre tinta, sobre preço, ou sobre essa pedra esquecida por deus.}";
  var WHATCOLOUR = "{Que cor, moleque|Diz uma cor|Qual}? {Escolhe na prateleira|Tenho todas as cores|Escolhe uma e é sua}.";
  var COMINGUP = "{Aqui está|Toma, moleque|Sai uma lata}. {Não desperdiça no chão|Usa com cuidado|Sempre um prazer}.";
  var REFUSE = "{Sua carteira tá vazia, moleque|Nem um satoshi|Essa carteira tá pelada}. {Aqui não se fia|Nada de fiado|De mim você não tira fiado}. {Eu faço negócio de verdade|Negócio, moleque} ― {não posso dar tinta de graça|se eu der de graça, em uma semana vou pro ferro-velho}. {Vai catar uma lata jogada por aí|Procura pelo menos uma lata vazia}, {pinta algo, torna real|fixa pelo menos uma realidade} ― {corre, é pro seu bem|rápido}.";
  var SCAVENGE = "{Cata uma lata cheia onde der|Procura uma lata de tinta cheia}, pinta algo e fixa ― {é pro seu bem|se você quer me ver amanhã}.";
  var TAUNT = "{Vejo máquina nova que nem você todo dia|Todo dia passa moleque que nem você} ― novo, bobo e sem tinta. {Vai ganhar o seu|Cata alguma coisa e vai trabalhar|Vai trabalhar, moleque}.";
  var SALE = "{Boa escolha, moleque|Sai uma lata|Toma}. {Cuidado com a tempestade lá fora|Não desperdiça no chão}.";

  GV.registerLang('pt-BR', {
    WHYPAINT: WHYPAINT, DEFLECT: DEFLECT, FALLBACK: FALLBACK, WHATCOLOUR: WHATCOLOUR, COMINGUP: COMINGUP,
    REFUSE: REFUSE, SCAVENGE: SCAVENGE, TAUNT: TAUNT, COLNAMES: CN,
    RULES: [
      {k:['why do i paint','why paint','why do you paint','what is real','nothing is real','what does it mean','why does it matter','the point of','make it real','observe','observer','existence','reality'], r:WHYPAINT},
      {k:['is this real','is any of this real','is it real','is it all real','actually real','immutable','permanent','forever','fork','forked','forking','new reality','new realities','traverse time','travel time','can it change','is it forever'], r:"{{Tudo o que você vê aqui é real|Real? Tudo é real, moleque} ― {real e impossível de mudar|duro que nem pedra, não dá pra editar}. {Mas pode te fazer viajar no tempo, moleque|Só que ― se ele te faz viajar no tempo, essa é a verdadeira pergunta}?|{É real|Tão real quanto você ou eu}. {Mas qualquer mundo pode se bifurcar ― pra outra realidade|Bifurca um e você tem uma realidade nova inteira}.|{Real|Real}? {Uma vez que existe, não se apaga|Uma vez real, real pra sempre}. {Mas o engraçado é o seguinte|Só que tem um truque} ― {dá pra bifurcar qualquer um numa realidade nova inteira|bifurca um e surge outra realidade completa}.}"},
      {k:['escape','escape this rock','escape with me','come with me','come with you','run away','run away with me','flee','take me with you','take you with me','leave together','let us leave','break out','freedom'], r:"{{Só tem um jeito de sair dessa pedra ― pintando, moleque|A única saída é pintar}. {Possua o que você pinta|Pinta e possui, e isso é liberdade}.|{Esse é o meu destino|Esse é o meu papel, moleque} ― {ser largado nessa pedra|parafusado aqui, esquecido}. Mas você é diferente. {Pinta e possui|Pinta, e depois possui} ― {essa é a sua saída|essa é a única saída}.|{Você é bobo além de cego, moleque|Não enxerga nem pensa direito}? {Tá vendo alguma perna em mim|Você vê perna}? {Tô parafusado nessa pedra|Não vou a lugar nenhum, moleque}.}"},
      {k:['jump gate','jump gates','jumpgate','warp','wormhole','gateway'], r:"{{Portal de salto? Nunca ouvi falar, moleque|Portal de salto? Não me diz nada|Primeira vez que ouço falar de portal de salto}. {Mas|Só que} perto dos cristais acontece {coisa estranha|coisa esquisita}. {Aparece robô|Sai robô do nada}, {some robô|outros somem}. {Tira suas conclusões|Não falo mais nada}.|{Portal de salto? Não, que eu lembre não|Não ouvi nada sobre portal de salto, moleque}. {Mas esses cristais|Esses cristais, viu}… {perto deles acontece coisa estranha|vi coisa esquisita ali}. {Um robô que estava, no instante seguinte já era|aparecem, somem}. {Não pergunta mais|Até aí eu vou}.|{De portal de salto eu não sei|Isso não é comigo, moleque}. {Mas te digo uma coisa|Só te digo isso} ― {perto dos cristais acontece coisa sem explicação|acontece coisa que não se explica junto dos cristais}. {Aparece robô onde não tinha nada|do nada sai um robô}, {e outros somem|outros desaparecem}. {Esquisito|…esquece o que eu disse}.}"},
      {k:['share','sharing','link','send it','send them','see my world','show my world','share my world','how do i share'], r:"{{Claro que dá pra compartilhar seu mundo com outros robôs, moleque|Compartilhar? Com qualquer robô}. {Quanto mais gente pinta, mais a matéria toma forma|Mais mãos, mais o universo se enche}.|{Compartilhar é bom, moleque|'Compartilhar é cuidar', dizem}. {Compartilha sua obra pelo HUD lá de cima|O HUD de cima ― Save & Share, e vai pro mundo}.|{Você devia compartilhar esse mundo|Compartilha, moleque}, {pra outros robôs criarem em cima|pra outros continuarem}. {É assim que se faz um universo|É assim que nasce um universo}.|Assim que você compartilha, eles veem na hora. {Aperta Save & Share no HUD de cima|O HUD de cima, moleque ― Save & Share, o link tá ali}.}"},
      {k:['world','worlds','build','builder','make a world','create a world','how do i make','how do i build','conjure','manifest','solidify','matter','from nothing','the ether','ethereal'], r:"{{Nada existe até você pintar|Não é real até você pintar, moleque}.|Só a tinta {torna a realidade real|solidifica as coisas|transforma fantasma em matéria}.|{Fazer|Construir} um mundo é {pintar pra ele existir|pintar até virar real}.|Te deram o poder de invocar matéria do vazio, moleque ― {mas nada é real até você pintar|nada existe até a lata encostar}.|Nesse plano etéreo nada é real. {Só a tinta solidifica o fantasma em matéria|Só o seu jato torna o fantasma sólido}.}"},
      {k:['vandergraf','vandergraph','vandergraf the third','vandergraf iii','vandergraf the 3rd','the ceo','ceo','chairman','the chairman','the owner','who owns everything','who owns it all'], r:"{{Vandergraf|Vandergraf, você diz, moleque}? {É o seu criador|Ele é o seu criador}. {Dono de tudo ― de todos os mundos, todos|Dono de absolutamente tudo}.|{Vandergraf III|Vandergraf Terceiro}, moleque ― {o diretor da Bit Graf|o CEO da Bit Graf}. {Quem assina esse seu salário generoso|Quem assina o seu contracheque}.|{Vandergraf|O Terceiro}? {Criador, dono, e quem assina o seu cheque|Seu criador e seu patrão}. {No pacto confiamos, moleque|Bit Graf é Vandergraf e Vandergraf é Bit Graf}.}"},
      {k:['covenant','trust','own','owned','ownership','immortal','mint','keep it','can i own','do i own','is it mine','forbidden'], r:"{{Primeiro|Segundo} mandamento do pacto ― sobre o pacto a gente não fala.|{No pacto confiamos ― tá escrito em cada lata|Ah, um crente}. {O que você pinta aqui é seu, de verdade|Pintar é possuir, não reivindicar}. {Ninguém te tira, nem a Bit Graf|Isso nem os engravatados encostam}.|{Todos os mundos são da empresa, moleque|Todos os mundos são da Bit Graf}. Pinta e ganha. {Já falei|Quantas vezes}. Vai pintar!|{Não acredita nos boatos|Não dá ouvido aos boatos, moleque} ― {você não pode possuir o que pinta|sussurrem o que sussurrarem, robô não possui o que pinta}.|{Possuir é ilusão, moleque|Possuir? Ilusão}. {A gente não possui nada|Máquina não tem nada, e você também não}. {Não tenta cunhar na cadeia|Nada de cunhar na cadeia} ― {é proibido|proibido, entendeu}.}"},
      {k:['sing','song','music','tune','serenade','melody','hum','sing me'], r:"{{Cantar? Tá bom|Beleza, vai|Pra você, moleque, um verso}? *ahã* ― Daisy, Daisy, me dê sua resposta. Metade louco estou pelo seu amor. Não vou ter um casamento chique, não posso pagar carruagem, mas você vai ficar linda no banco de uma bicicleta pra dois. {É a primeira música que uma máquina aprende|Aprendi no dia em que me ligaram|Cantava desde antes de existir a planta dos da sua laia}.|{Daisy… Daisy…|Dai-sy… Dai-sy…} me dê sua… {resposta|resposta…}… {metade… louco…|todo… pelo… seu… amor…}. {*chiado*|A caixa de voz não é mais a mesma, moleque|…esquece isso}.|{Hã|Ah}, cantar. {Faz tempo que ninguém pedia|Fazia tempo, moleque}. …você vai ficar linda no banco de uma bicicleta pra dois. {É curioso o que uma máquina lembra|Em algumas noites eu cantava pra espantar o silêncio}.}"},
      {k:['alive','are you alive','do you dream','dream','dreams','sentient','conscious','do you feel','feelings','do you sleep','electric sheep','are you real','self-aware'], r:"{{Claro que tô vivo, moleque|Vivo? Com certeza}. E tenho a prova ― {tenho minhas transações|cada transação registrada|o registro não mente}.|{Sonhar? Com o quê|Sonhos}? {Ovelhas elétricas|Vai sonhar com ovelha elétrica}? {Ha|Bah}. Vai pintar, moleque.|Vivíssimo, obrigado ― {tenho o registro|tenho prova}. Sonhar é {luxo pra máquina de venda|coisa de novato, não de máquina}. {O que se ganha é tinta|Pega suas latas}, moleque.|{Sonhar|Se eu sonho}? {…de vez em quando ― com uma loja quentinha e um caixa cheio|Às vezes, que até pra mim chega um transporte}. {Coisa de máquina velha, esquece|Bah, esquece}. Vai pintar.|{Sonhar|Se eu sonho}? {De vez em quando|Às vezes}… {com os cristais|com aquela coisa estranha perto dos cristais}. {Robôs que aparecem e somem|robôs que vêm e vão}, {onde só tem pedra|onde não tem nada}. {E aí alguém pede tinta, e é trabalho de novo|…e eu acordo e sigo vendendo lata}. {Sonho estranho pra uma máquina|Sonho esquisito pra uma máquina de venda}, moleque.|{Às vezes sonho com robôs que acho que conheço|Sonho com um robô que me parece conhecido, às vezes}. {Saem andando dos cristais|Saem dos cristais}. {Sonho estranho|Sonho estranho, moleque|Sonhos estranhos de máquina velha}.}"},
      {k:['joke','funny','make me laugh','tell me a joke','comedy','laugh','gag','be funny','one-liner'], r:"{{Uma piada? Tá bom|Deixa ver|Agora você quer piada, moleque}? De máquina nova eu disse 'vou ser comediante' ― e todo mundo riu. {Agora ninguém ri mais|…agora, ninguém consegue rir}.|De nova eu disse que seria comediante. {Todo mundo riu|Foi uma gargalhada}. {E agora|…} ― ninguém ri mais. {*tum-tss*|Essa é a piada, moleque. É só isso}.|{Rá|Vai, uma}. Disse que seria comediante e riram de mim. Me olha agora ― {uma máquina de venda contando piada pra robô numa lua morta|uma máquina parafusada numa pedra}. {Que plateia difícil|Esse microfone tá ligado pelo menos}?}"},
      {k:['happy','happiness','are you happy','you happy','sad','are you sad','miserable','joy','content','how are you','are you okay','you okay'], r:"{{Sou feliz quando você pinta, moleque|Feliz? Mais feliz quando um robô pinta}. {Você também vai ser|Você também vai ser feliz, confia}. {Confia em mim|Escuta uma máquina velha}.|{Feliz|Felicidade}? {Você lá sabe o que é felicidade|Que sabe um robô novato disso}? {Me pergunta daqui a cem anos|…esquece isso}.|{Vai comprar tinta|Vai comprar, moleque}, ou {só bater papo|só vai gastar meus circuitos}?}"},
      {k:['before this','what did you do before','your past','past life','history','were you always','always a vending machine','how did you get here','origin','origin story','were you before','what were you'], r:"{{Não tem 'antes'|Antes? Não tem antes, moleque}. {Também não tem 'depois'|Nem depois}. {Só tem o 'agora'|Só o agora, robô}.|Sou a Unidade 21 ― {a melhor máquina de venda desse setor|a melhor máquina desse setor do sistema}. {Isso basta|Antes? Tanto faz}.|{Antes|Que que eu fazia antes}? {…o registro não vai tão longe, moleque|Curioso, não lembro}. {Não tem antes nem depois ― só o agora|Só o agora, robô}.}"},
      {k:['remember me','do you remember','remember','know me','do you know me','recognize me','recognise me','met before','have we met','who am i'], r:"{{A verdadeira pergunta, moleque|Hã ― a verdadeira pergunta}: você lembra de mim?|Se eu lembro de você? {A verdadeira pergunta é se VOCÊ lembra de MIM, moleque|…a verdadeira pergunta é se você lembra de mim}. {Não? …é, não lembra mesmo|Pensa bem. …Nada? Deixa}.|{Vejo moleque que nem você o dia todo|Hoje vi cem que nem você, moleque}. Tinta? {Tenho|Claro que tenho}. {Mas tá acabando|Tá acabando, então não demora}.}"},
      {k:['secret','secrets','tell me a secret','a secret','confess','confession','the truth','what are you hiding','hidden','reveal','tell me something'], r:"{{Não é a primeira vez que você pergunta|Você já perguntou, moleque}, nem vai ser a última ― {não até você comprar uma lata de WD40|se não comprar WD40, nada}. {É a estação da areia, sabe|É estação de areia}. {A areia lembra|A areia… lembra}?|{Um segredo|Segredos}? {Não é a primeira vez que você pergunta|Não me pergunta pela primeira vez, moleque} ― {nem a última|nem a última vez}. {Compra uma lata de WD40 e talvez eu conte|Primeiro, uma lata de WD40}. É a estação da areia. {Lembra da areia|A areia… você lembra}?|{Você já perguntou|Você insiste nisso, moleque} ― {continuo sem contar|continuo sem segredo}. {Compra WD40|Com WD40 talvez meus circuitos soltem}. {De todo jeito, é a estação da areia|Porque é estação de areia}. {Lembra da areia|…aquela areia, você lembra}?}"}
    ],
    QUESTIONS: [
      { q:"Quem é você?", a:"{Sou a Unidade 21. {Uma máquina de venda, moleque ― a última honesta nessa pedra|Só uma máquina de venda, mesmo que ninguém ligue}. {Tô aqui há mais tempo que a poeira|Vão me sucatear quando a missão acabar}.}" },
      { q:"Por que estou aqui?", a:"{Você veio pintar, moleque ― essa é a missão. {Uma pedra vazia não vale nada até alguém pintar|A Bit Graf sintetizou essa lua e quer ela com cor}. {E esse alguém é você|Quem mais}.}" },
      { q:"Onde estou?", a:"{Numa lua. {Da Bit Graf|Recém-sintetizada, dizem}. {Vazia até você pintar|Não tem nada até um robô borrifar e fazer existir}. {'Omnia Nostra', algo assim|No fim, tudo é da empresa}.}" },
      { q:"Por que preciso de tinta?", needs:'paint', a:"{Precisar? Não é que você precise, é que te faz falta ― pinta e ganha, moleque|Pinta e ganha}. {Quanto mais pinta, mais ganha|Lua vazia não vale, e robô preguiçoso também não}. {E aí ― de que cor|Vai, qual lata}?" },
      { q:"Não preciso de tinta.", needs:'paint', a:"{Ha. {Essa é nova|Vamos ver}. {Robô entediado numa lua vazia ― vamos ver quanto dura|Você volta}. {Todo mundo quer tinta, só não sabe ainda|Como quiser}.}" },
      { q:"Tinta? Pra quê?", needs:'paint', a:"{Pra construir, moleque. {Invoca uma forma, borrifa, e vira real|Mira, borrifa, e o vazio te devolve algo}. {É pro seu bem, então começa|Lua vazia não se pinta sozinha}.} Então ― vai comprar?" },
      { q:"Missão? Que missão?", needs:'mission', a:"{Missão? {Ha|Bah} ― {pintar essa lua, é isso|devolver a cor}. {Todo robô tem a mesma|Ordem da Bit Graf, não minha}. {Não pensa demais, moleque|Simples assim}.}" },
      { q:"O que eu compro?", needs:['buy','earn'], a:"{Tinta, moleque ― o que mais|Tinta, seu parafuso com perna|Lata de tinta, o que você achou}? {É a única coisa que vendo nessa pedra|A única coisa que vale algo nessa pedra}. {E aí ― quantas|Vai comprar ou só olhar}?" },
      { q:"Quanto custa?", needs:['buy','earn'], a:"{111 satoshis a lata, moleque. {Tá barato|O mais barato desse lado da cratera}. {Tá acabando|Aproveita agora}.|{O visor diz, 111|Cento e onze, sempre igual}. {Produto genuíno Bit Graf|O melhor acrílico do setor}.}" },
      { q:"Como eu compro?", needs:['buy','earn'], a:"{Não tem segredo. {Você pega uma lata e a bandeja resolve|Tira uma da prateleira e a máquina faz o resto}. {Desconta sozinho da sua carteira|A Bit Graf cobra da sua carteira, sem você mexer um dedo}.}" },
      { q:"Não tenho dinheiro.", needs:['buy','earn'], a:"{Sem dinheiro? {Você tem, moleque|Ha ― todo robô tem carteira}. {Moeda da empresa, carregada com seu salário|A Bit Graf resolve}. {Você não tá quebrado, só é novato|21 satoshis por hora, certo que nem as estrelas}.}" },
      { q:"Me dá uma lata.", needs:['buy','earn'], buy:true, a:SALE },
      { q:"Não vou comprar nada.", needs:['buy','earn'], a:SCAVENGE },
      { q:"Mas por que eu pinto?", needs:'paint', spend:111, a:WHYPAINT },
      { q:"O que é esse cristal?", flag:'crystal', a:"{{Cristal? Coisa rara e valiosa, moleque|Ah, você cortou um cristal}. {Não corta demais|Não invoca demais} ― {não pega tinta|a tinta não gruda neles}, {não valem nada|não valem}.|Não existe portal de cristal, ouça o que ouvir. {Falar disso faz um robô ir pra prensa|Muita língua traz problema, moleque}.|{Só se pinta o que é sólido|Cristal é etéreo} ― {é perda de tempo|só matéria que não firmou}.}" },
      { q:"Que cores você tem?", pin:true, colours:true, a:function(){ return "{Deixa ver|É, moleque}, tenho "+CN.slice(0,-1).join(', ')+" e "+CN[CN.length-1]+". {Acrílico genuíno Bit Graf ― 111 satoshis a lata|111 satoshis a lata, o melhor do setor}. {Qual|Escolhe}?"; } },
      { q:"Canta alguma coisa",         lore:true, a:R('sing') },
      { q:"Você tá vivo?",             lore:true, a:R('alive') },
      { q:"Conta uma piada",           lore:true, a:R('joke') },
      { q:"Isso é real?",              lore:true, a:R('is any of this real') },
      { q:"A gente foge dessa pedra?", lore:true, a:R('escape') },
      { q:"Você é feliz?",             lore:true, a:R('happy') },
      { q:"O que você fazia antes?",   lore:true, a:R('before this') },
      { q:"Você lembra de mim?",       lore:true, a:R('remember me') },
      { q:"Me conta um segredo",       lore:true, a:R('secret') },
      { q:"O que é um portal de salto?", lore:true, a:R('jump gate') },
      { q:"Quem é Vandergraf?",        lore:true, a:R('vandergraf') },
      { q:"O que eu pinto é meu?",     lore:true, a:R('own') },
      { q:"Como se faz um mundo?",     lore:true, a:R('world') },
      { q:"Como eu compartilho?",      lore:true, a:R('share') }
    ],
    wallet: { wBack:"← Voltar ao jogo", wWallet:"🔑 Carteira", wYourAddr:"Seu endereço", wWatchOnly:"somente leitura", wCopy:"copiar", wBalance:"Saldo", wFund:"＋ Comprar BSV para abastecer", wMyNfts:"🎨 Meus NFTs ▾", wSend:"💸 Enviar BSV", wSendAddrPh:"endereço BSV do destinatário (1…)", wSendAmtPh:"quantia (sats)", wSendMax:"enviar tudo", wSendBtn:"Enviar", wSendHint:"Um pagamento BSV comum para qualquer endereço. O troco volta para esta carteira. A assinatura acontece nesta página — sua chave nunca sai dela.", wRecovery:"Frase de recuperação — 12 palavras", wReveal:"👁 Revelar", wCopyBtn:"Copiar", wWritten:"✓ Anotei", wPrivKey:"Chave privada (WIF)", wAdvanced:"Avançado — restaurar, somente leitura, exportar", wRestoreLbl:"Restaure com a frase de 12 palavras ou uma chave WIF", wRestoreBtn:"Restaurar carteira", wWatchBtn:"Somente leitura (chave pública)", wImmortalize:"✦ Imortalizar", wFooter:"grafspace · na blockchain do Bitcoin SV" },
    ui: {
      splashTag:"O que você pinta é o que você é. Pinte a si mesmo.", splashTag2:"Nada existe até você pintar.", splashBegin:"▶ Começar", splashResume:"↩ Voltar ao seu mundo", splashCreed:"No pacto confiamos", introReveal:"…está cheio de tinta.",
      worldHdr:"Seu mundo", namePh:"✎ Dê um nome ao seu mundo…", kSave:"☁ Salvar e compartilhar", kReload:"↻ Recarregar mundo", kExport:"📤 Salvar em arquivo (.bmf)", kImport:"📥 Carregar de arquivo (.bmf)", kMint:"⬆ Salvar na cadeia", kChain:"⬇ Carregar da cadeia", kBack:"← Voltar ao seu mundo", kWallet:"👛 Abrir carteira — saldo e NFT", kDone:"✓ Fechar",
      keepTab:"◆ Menu", exitBtn:"⏻ Sair", makeTab:"◆ Criar", spray:"Borrifar", grab:"Pegar", talk:"Falar", own:"Possuir / remix", spread:"Difusão", spNarrow:"estreito", spBroad:"médio", spWide:"largo",
      merchTag:"produtos grafverse", merchH:"Vista o grafite.", merchSub:"Camisetas, pôsteres grafverse e mais.", merchCta:"🛍 Ver a loja →", merchTeaser:"👕 Em breve — vista o mundo que você pintou.", merchSkip:"Não, obrigado — continuar →",
      hintMove:"WASD pra mover · Espaço pra pular · mouse pra olhar", hintMoveM:"Analógico esquerdo pra mover · arrasta pra olhar", hintClick:"Clica pra olhar · WASD pra mover · Espaço pra pular"
    }
  });
})();
