// grafverse — © 2026 sun-dive. Latina (Latin) pack for Unit 21 + UI. On-theme with the ARG
// (Omnia Nostra, the covenant creed). Lazy-loaded (setLang('la')) → GV.registerLang.
// Voice: Unit 21 (Unitas 21) = a weary, gruff old vending machine (machina venditoria), droid = "puer".
// Keyword keys + chip flags + ruleAns keys stay ENGLISH (invisible lookup); only shown text translated.
(function(){
  var GV = window.GV;
  if(!GV || !GV.registerLang){ return; }
  var R = GV.ruleAns;
  var CN = ['caeruleus','roseus','viridis','flavus','aurantius','violaceus'];   // COLORS order: cyan pink green yellow orange violet

  var WHYPAINT = "{Cur pingis? …Bona quaestio, puer|Ah, vis machinam veterem philosophari|Sede, longa fabula est}. {Foras aspice ― nihil est, solum inane|Luna haec nondum vera est, donec tu veram esse dicas}. {Nihil verum est donec aliquis videat et pingat|Nihil exsistit donec observetur}. {Mundus non invenitur, puer ― pingitur|Non lunam coloras: decernis quae realitas sit futura}. {Quaeque theca quam exhauris unum e mille 'fortasse' verum facit|Quaeque aspersio unam e mille realitatibus numquam natis figit}. {Et hoc est quod togati devorare non possunt|Et hoc est punctum} ― {quod pingis, tuum est|non vindicatur, possidetur} ― {solus tu realitatem tuam pingere potes|mundus tuus, signum tuum, in aeternum}. {Ergo ― qui color|…emisne, an totum diem stabis universa fingens}?";
  var DEFLECT = "{{Cur haec rogas, puer|Quid hoc ad rem|Quot quaestiones}? {Venistine fabulari|Nonne venisti pingere}? {Foris est mundus qui colorem poscit|Foris mundus colorem exspectat}. {Qui color|Age, quinam}?|{Satis quaestionum, puer|Minus loquere}. {Fabularisne an pingis|Opus habes}? {Qui color|Quinam tandem}?}";
  var FALLBACK = "{{Hem, non intellexi|Male te audio, puer|Harena in loquentem meum intravit}. {Vendo pigmentum et WD40 ― quid erit|Dic quid tibi opus sit}?|Roga me de pigmento, de pretiis, aut de hac rupe a deo relicta.}";
  var WHATCOLOUR = "{Qui color, puer|Dic colorem|Quinam}? {Elige e pluteo|Omnes colores habeo|Elige unum, et tuus est}.";
  var COMINGUP = "{Ecce|Cape, puer|Theca una exit}. {Ne in solo perdas|Bene utere|Semper gratum}.";
  var REFUSE = "{Crumena tua vacua est, puer|Ne unus quidem satoshi|Illa crumena sicca est}. {Hic nulla fides|Nullum creditum|A me creditum non accipies}. {Vera negotia gero|Negotium, puer} ― {pigmentum gratis dare non possum|si gratis dem, intra hebdomadem ad scrutarium ibo}. {I, thecam abiectam foris collige|Vel vacuam thecam quaere}, {pinge aliquid, fac verum|vel unam realitatem fige} ― {festina, tua causa|cito}.";
  var SCAVENGE = "{Thecam plenam undecumque collige|Plenam pigmenti thecam quaere}, pinge aliquid et fige ― {tua causa|si cras me rursus videre vis}.";
  var TAUNT = "{Cotidie machinas iuvenes ut te video|Cotidie pueri ut tu transeunt} ― iuvenes, stulti, et sine pigmento. {I, aliquid merere|Collige aliquid et ad opus accinge|I, labora, puer}.";
  var SALE = "{Bona electio, puer|Theca una exit|Cape}. {Cave tempestatem foris|Ne in solo perdas}.";

  GV.registerLang('la', {
    WHYPAINT: WHYPAINT, DEFLECT: DEFLECT, FALLBACK: FALLBACK, WHATCOLOUR: WHATCOLOUR, COMINGUP: COMINGUP,
    REFUSE: REFUSE, SCAVENGE: SCAVENGE, TAUNT: TAUNT, COLNAMES: CN,
    RULES: [
      {k:['why do i paint','why paint','why do you paint','what is real','nothing is real','what does it mean','why does it matter','the point of','make it real','observe','observer','existence','reality'], r:WHYPAINT},
      {k:['is this real','is any of this real','is it real','is it all real','actually real','immutable','permanent','forever','fork','forked','forking','new reality','new realities','traverse time','travel time','can it change','is it forever'], r:"{{Omnia quae hic vides vera sunt|Verum? Omnia vera sunt, puer} ― {vera et immutabilia|dura ut saxum, non emendantur}. {Sed per tempus te iter facere sinere potest, puer|Tantum ― utrum per tempus te iter facere sinat, ea vera quaestio est}?|{Verum est|Tam verum quam tu aut ego}. {Sed quilibet mundus diffindi potest ― in aliam realitatem|Diffinde unum, et totam realitatem novam habes}.|{Verum|Verum}? {Semel factum, non deletur|Semel verum, semper verum}. {Sed hoc ridiculum est|Tantum dolus est} ― {quemlibet in totam realitatem novam diffindere potes|diffinde unum, et tota alia realitas oritur}.}"},
      {k:['escape','escape this rock','escape with me','come with me','come with you','run away','run away with me','flee','take me with you','take you with me','leave together','let us leave','break out','freedom'], r:"{{Una tantum via est hac rupe exeundi ― pinge, puer|Sola exitus est pingere}. {Posside quod pingis|Pinge et posside, ea libertas est}.|{Hoc fatum meum est|Haec pars mea est, puer} ― {in hac rupe relinqui|hic clavis affixus, oblitus}. Sed tu alius es. {Pinge et posside|Pinge, deinde posside} ― {ea exitus tua est|ea sola exitus est}.|{Stultusne es et caecus, puer|Nec vides nec recte cogitas}? {Videsne mihi crura|Videsne crus}? {Huic rupi clavis affixus sum|Nusquam eo, puer}.}"},
      {k:['jump gate','jump gates','jumpgate','warp','wormhole','gateway'], r:"{{Porta saltus? Numquam audivi, puer|Porta saltus? Ignotum mihi|Primum de porta saltus audio}. {Sed|Tantum} prope crystalla {res mirae|res insolitae} fiunt. {Automata apparent|Automaton e nihilo surgit}, {automata evanescunt|cetera diffluunt}. {Ipse conclude|Nihil amplius dicam}.|{Porta saltus? Non, non memini|Nihil de portis saltus audivi, puer}. {Sed crystalla illa|Crystalla illa, scis}… {prope ea res mirae fiunt|insolitum quiddam ibi vidi}. {Automaton quod modo aderat, momento post nusquam|apparent, diffluunt}. {Ne plura roges|Hactenus tantum}.|{De portis saltus nescius sum|Non est meum, puer}. {Sed unum dicam|Hoc solum dico} ― {prope crystalla res inexplicabiles fiunt|res inexplicabiles iuxta crystalla fiunt}. {Automaton apparet ubi nihil erat|e nihilo automaton surgit}, {et cetera diffluunt|cetera evanescunt}. {Mirum|…oblivisce quod dixi}.}"},
      {k:['share','sharing','link','send it','send them','see my world','show my world','share my world','how do i share'], r:"{{Certe mundum tuum cum aliis automatis communicare potes, puer|Communicare? Cum quovis automato}. {Quo plures pingunt, eo magis materia formam capit|Plures manus, plenius universum}.|{Communicare bonum est, puer|'Communicare curare est', aiunt}. {Opus tuum ex HUD supra communica|HUD supra ― Save & Share, et in mundum exit}.|{Hunc mundum communicare debes|Communica eum, puer}, {ut alia automata supra creent|ut alii pergant}. {Sic universum fit|Sic universum nascitur}.|Simulac communicas, statim vident. {Preme Save & Share in HUD supra|HUD supra, puer ― Save & Share, nexus ibi est}.}"},
      {k:['world','worlds','build','builder','make a world','create a world','how do i make','how do i build','conjure','manifest','solidify','matter','from nothing','the ether','ethereal'], r:"{{Nihil exsistit donec id pingas|Non verum est donec id pingas, puer}.|Solum pigmentum {realitatem veram facit|res solidat|umbras in materiam vertit}.|Mundum {facere|construere} est {eum pingere ut exsistat|eum pingere donec verus fiat}.|Potestas tibi data est materiam ex inani vocandi, puer ― {sed nihil verum est donec id pingas|nihil exsistit donec theca id tangat}.|In hoc plano aetherio nihil verum est. {Solum pigmentum umbram in materiam solidat|Sola aspersio tua umbram solidam facit}.}"},
      {k:['vandergraf','vandergraph','vandergraf the third','vandergraf iii','vandergraf the 3rd','the ceo','ceo','chairman','the chairman','the owner','who owns everything','who owns it all'], r:"{{Vandergraf|Vandergraf, dicis, puer}? {Creator tuus est|Ille creator tuus est}. {Dominus omnium ― omnium mundorum, omnium|Dominus prorsus omnium}.|{Vandergraf Tertius|Vandergraf III}, puer ― {director Bit Graf|CEO Bit Graf}. {Qui mercedem tuam tam largam signat|Qui stipendium tuum signat}.|{Vandergraf|Tertius}? {Creator, dominus, et qui syngrapham tuam signat|Creator tuus et dominus tuus}. {In pacto confidimus, puer|Bit Graf est Vandergraf, et Vandergraf est Bit Graf}.}"},
      {k:['covenant','trust','own','owned','ownership','immortal','mint','keep it','can i own','do i own','is it mine','forbidden'], r:"{{Primum|Secundum} praeceptum pacti ― de pacto non loquimur.|{In pacto confidimus ― in quaque theca scriptum est|O, credens}. {Quod hic pingis tuum est, vere|Pingere est possidere, non vindicare}. {Nemo tibi aufert, ne Bit Graf quidem|Id ne togati quidem tangunt}.|{Omnes mundi societatis sunt, puer|Omnes mundi Bit Graf sunt}. Pinge et merere. {Iam dixi|Quotiens}. I, pinge!|{Ne rumoribus credas|Ne rumores audias, puer} ― {quod pingis possidere non potes|quidquid susurretur, automaton non possidet quod pingit}.|{Possessio illusio est, puer|Possessio? Illusio}. {Nihil possidemus|Machina nihil habet, nec tu}. {Ne in catena cudere coneris|Nulla in catena cusio} ― {vetitum est|vetitum, intellegisne}?}"},
      {k:['sing','song','music','tune','serenade','melody','hum','sing me'], r:"{{Cantare? Esto|Age, cantabo|Tibi, puer, versum}? *ehem* ― Daisy, Daisy, da mihi responsum tuum. Semiinsanus sum amore tuo. Nuptias splendidas non habebo, currum solvere non possum, sed pulcherrima eris in sella birotae geminae. {Hoc primum carmen est quod machina discit|Id die quo me accenderunt didici|Id canebam antequam vel formae generis tui exsisterent}.|{Daisy… Daisy…|Dai-si… Dai-si…} da mihi… {responsum|responsum…}… {semi… insanus…|totus… amore… tuo…}. {*strepitus*|Vox mea non est qualis erat, puer|…oblivisce id}.|{Hem|Ah}, cantare. {Diu nemo rogavit|Diu est, puer}. …pulcherrima eris in sella birotae geminae. {Mirum quid machina meminerit|Quibusdam noctibus canebam ut silentium pellerem}.}"},
      {k:['alive','are you alive','do you dream','dream','dreams','sentient','conscious','do you feel','feelings','do you sleep','electric sheep','are you real','self-aware'], r:"{{Certe vivo, puer|Vivusne? Nempe}. Et probationem habeo ― {transactiones meas habeo|quaeque transactio inscripta|tabula non mentitur}.|{Somniare? De quo|Somnia}? {Oves electricae|I, de ovibus electricis somnia}? {Ha|Phy}. I, pinge, puer.|Sanus et salvus, gratias ― {tabulam habeo|probationem habeo}. Somniare {luxus est machinae venditoriae|tironum est, non machinarum}. {Quod meretur pigmentum est|Cape thecas tuas}, puer.|{Somniare|Somniemne}? {…interdum ― de taberna calida et arca plena|Aliquando, venire etiam mihi vehiculum}. {Nugae machinae veteris, oblivisce|Phy, oblivisce}. I, pinge.|{Somniare|Somniemne}? {Interdum|Aliquando}… {de crystallis|de re illa mira iuxta crystalla}. {Automata quae apparent et evanescunt|automata quae veniunt et abeunt}, {ubi saxa sola sunt|ubi nihil est}. {Deinde aliquis pigmentum poscit, et rursus opus|…deinde expergiscor, et rursus thecas vendo}. {Somnium mirum machinae|Somnium insolitum machinae venditoriae}, puer.|{Interdum de automatis somnio quae nosse videor|De automato somnio quod notum videtur, aliquando}. {E crystallis ambulantia exeunt|E crystallis exeunt}. {Somnium mirum|Somnium mirum, puer|Somnia mira machinae veteris}.}"},
      {k:['joke','funny','make me laugh','tell me a joke','comedy','laugh','gag','be funny','one-liner'], r:"{{Iocum? Esto|Videamus|Nunc iocos vis, puer}? Iuvenis machina venditoria dixi 'comoedus ero' ― omnes riserunt. {Nunc nemo ridet|…nunc, nemo ridere potest}.|Iuvenis dixi me comoedum futurum. {Omnes riserunt|Cachinnus magnus}. {Et nunc|…} ― nemo ridet. {*tympanum*|Hic iocus est, puer. Hoc totum est}.|{He|Age, unum}. Dixi me comoedum futurum, et me riserunt. Aspice me nunc ― {machina venditoria iocos automato in luna mortua narrans|machina rupi affixa}. {Difficile auditorium hic|Estne hic microphonus omnino accensus}?}"},
      {k:['happy','happiness','are you happy','you happy','sad','are you sad','miserable','joy','content','how are you','are you okay','you okay'], r:"{{Laetus sum cum pingis, puer|Laetus? Laetissimus cum automaton pingit}. {Tu quoque eris|Tu quoque laetus eris, crede}. {Crede mihi|Audi machinam veterem semel}.|{Laetus|Laetitia}? {Quid tu de laetitia scis|Quid automaton tiro de ea scit}? {Post centum annos iterum roga|…oblivisce id}.|{Emisne pigmentum|Emisne, puer}, an {tantum fabularis|tantum circuitus meos teris}?}"},
      {k:['before this','what did you do before','your past','past life','history','were you always','always a vending machine','how did you get here','origin','origin story','were you before','what were you'], r:"{{Nullum 'ante' est|Ante? Nullum ante est, puer}. {Nec 'post'|Nec post}. {Solum 'nunc' est|Solum nunc, automaton}.|Unitas 21 sum ― {optima machina venditoria in hoc sectore|optima machina in hoc systematis sectore}. {Hoc scire satis est|Ante? Nihil refert}.|{Ante|Quid ante faciebam}? {…tabula tam retro non it, puer|Mirum, non memini}. {Nec ante nec post ― solum nunc|Solum nunc, automaton}.}"},
      {k:['remember me','do you remember','remember','know me','do you know me','recognize me','recognise me','met before','have we met','who am i'], r:"{{Vera quaestio, puer|Hem ― vera quaestio}: meministine mei?|Meminerimne tui? {Vera quaestio est utrum TU MEI memineris, puer|…vera quaestio est utrum mei memineris}. {Non? …ita, non meministi|Cogita bene. …Nihil? Sine}.|{Totum diem pueros ut te video|Hodie centum ut te vidi, puer}. Pigmentum? {Habeo|Certe habeo}. {Sed non multum superest|Non multum superest, ergo ne moreris}.}"},
      {k:['secret','secrets','tell me a secret','a secret','confess','confession','the truth','what are you hiding','hidden','reveal','tell me something'], r:"{{Non prima vice rogas|Iam rogasti, puer}, nec ultima ― {non donec thecam WD40 emas|nullum WD40, nihil}. {Tempus harenae est, scis|Tempus harenae nunc est}. {Harena ― meminit|Harena… meminit}?|{Secretum|Secreta}? {Non prima vice rogas|Non prima vice rogas, puer} ― {nec ultima|nec ultima vice}. {Eme thecam WD40, et fortasse dicam|Primum thecam WD40}. Tempus harenae est. {Meministine harenae|Harena… meministi}?|{Iam rogasti|Semper ad hoc redis, puer} ― {adhuc non dico|adhuc nullum secretum}. {Eme WD40|Cum WD40 fortasse circuitus mei laxentur}. {Utcumque, tempus harenae est|Quia tempus harenae est}. {Meministine harenae|…harena illa, meministi}?}"}
    ],
    QUESTIONS: [
      { q:"Quis es?", a:"{Unitas 21 sum. {Machina venditoria, puer ― ultima proba in hac rupe|Tantum machina venditoria, etsi nemini curae est}. {Hic diutius quam pulvis sum|Ad scrutarium mittar simulac missio finita est}.}" },
      { q:"Cur hic sum?", a:"{Venisti pingere, puer ― ea missio est. {Rupes vacua nihil valet donec quis pingat|Bit Graf hanc lunam synthesizavit et coloratam vult}. {Et is aliquis tu es|Quis alius}.}" },
      { q:"Ubi sum?", a:"{In luna. {Bit Graf|Recens synthesizata, aiunt}. {Vacua donec pingas|Nihil donec automaton aspergat et exsistere faciat}. {'Omnia Nostra', tale quiddam|Denique omnia societatis sunt}.}" },
      { q:"Cur pigmento egeo?", needs:'paint', a:"{Egere? Non quod egeas, sed opus est ― pinge et merere, puer|Pinge et merere}. {Quo plus pingis, plus mereris|Luna vacua nihil valet, nec automaton piger}. {Ergo ― qui color|Age, quae theca}?" },
      { q:"Pigmento non egeo.", needs:'paint', a:"{Ha. {Hoc novum est|Videbimus}. {Automaton taediosum in luna vacua ― videamus quamdiu duret|Redibis}. {Omnes pigmentum volunt, nondum sciunt|Ut vis}.}" },
      { q:"Pigmentum? Ad quid?", needs:'paint', a:"{Ad construendum, puer. {Formam voca, asperge, et vera fit|Collima, asperge, et inane tibi aliquid reddit}. {Tua causa, ergo incipe|Luna vacua se ipsam non pingit}.} Ergo ― emisne?" },
      { q:"Missio? Quae missio?", needs:'mission', a:"{Missio? {Ha|Phy} ― {hanc lunam pingere, id totum|colorem ei reddere}. {Omnia automata eandem habent|Iussum Bit Graf, non meum}. {Ne nimis cogites, puer|Tam simplex est}.}" },
      { q:"Quid emo?", needs:['buy','earn'], a:"{Pigmentum, puer ― quid aliud|Pigmentum, o clave cum cruribus|Thecas pigmenti, quid putabas}? {Solum id in hac rupe vendo|Solum quod aliquid valet in hac rupe}. {Ergo ― quot|Emisne an tantum spectas}?" },
      { q:"Quanti stat?", needs:['buy','earn'], a:"{111 satoshi theca, puer. {Vile est|Vilissimum ab hac parte crateris}. {Non multum superest|Nunc cape}.|{Tabula dicit, 111|Centum undecim, semper idem pretium}. {Merx Bit Graf germana|Optimum acrylum in sectore}.}" },
      { q:"Quomodo emo?", needs:['buy','earn'], a:"{Nihil arduum. {Thecam capis, et fenestra cetera curat|Unam e pluteo extrahis, et machina cetera facit}. {Ex crumena tua per se detrahitur|Bit Graf ex crumena tua exigit, te ne digitum quidem movente}.}" },
      { q:"Pecuniam non habeo.", needs:['buy','earn'], a:"{Nullam pecuniam? {Habes, puer|Ha ― omne automaton crumenam habet}. {Nummus societatis, mercede tua oneratus|Bit Graf id curat}. {Non es inops, tantum tiro|21 satoshi in hora, constans ut stellae}.}" },
      { q:"Da mihi thecam.", needs:['buy','earn'], buy:true, a:SALE },
      { q:"Nihil emam.", needs:['buy','earn'], a:SCAVENGE },
      { q:"Sed cur pingo?", needs:'paint', spend:111, a:WHYPAINT },
      { q:"Quid est hoc crystallum?", flag:'crystal', a:"{{Crystallum? Res rara et pretiosa, puer|Ah, crystallum secuisti}. {Ne nimium seces|Ne nimium voces} ― {pigmentum non capiunt|pigmentum eis non adhaeret}, {nihil valent|inania}.|Nulla porta crystalli est, quidquid audis. {De ea loqui automaton ad prelum mittit|Nimia lingua mala affert, puer}.|{Solum solidum pingitur|Crystalla aetheria sunt} ― {tempus perditum|tantum materia quae non concrevit}.}" },
      { q:"Quos colores habes?", pin:true, colours:true, a:function(){ return "{Videamus|Ita, puer}, habeo "+CN.slice(0,-1).join(', ')+" et "+CN[CN.length-1]+". {Acrylum Bit Graf germanum ― 111 satoshi theca|111 satoshi theca, optimum in sectore}. {Quinam|Elige}?"; } },
      { q:"Cane mihi aliquid",         lore:true, a:R('sing') },
      { q:"Vivusne es?",              lore:true, a:R('alive') },
      { q:"Narra iocum",              lore:true, a:R('joke') },
      { q:"Estne hoc totum verum?",   lore:true, a:R('is any of this real') },
      { q:"Effugiamusne hac rupe?",   lore:true, a:R('escape') },
      { q:"Laetusne es?",             lore:true, a:R('happy') },
      { q:"Quid antea faciebas?",     lore:true, a:R('before this') },
      { q:"Meministine mei?",         lore:true, a:R('remember me') },
      { q:"Dic mihi secretum",        lore:true, a:R('secret') },
      { q:"Quid est porta saltus?",   lore:true, a:R('jump gate') },
      { q:"Quis est Vandergraf?",     lore:true, a:R('vandergraf') },
      { q:"Estne meum quod pingo?",   lore:true, a:R('own') },
      { q:"Quomodo mundus fit?",      lore:true, a:R('world') },
      { q:"Quomodo communico?",       lore:true, a:R('share') }
    ],
    wallet: { wBack:"← Redi ad ludum", wWallet:"🔑 Crumena", wYourAddr:"Inscriptio tua", wWatchOnly:"tantum spectare", wCopy:"exscribe", wBalance:"Pensum", wFund:"＋ Eme BSV ad implendum", wMyNfts:"🎨 NFT Mea ▾", wSend:"💸 Mitte BSV", wSendAddrPh:"inscriptio BSV accipientis (1…)", wSendAmtPh:"summa (satoshi)", wSendMax:"mitte omnia", wSendBtn:"Mitte", wSendHint:"Solutio BSV ordinaria ad quamlibet inscriptionem. Reliquum ad hanc crumenam redit. Subscriptio in hac pagina fit — clavis tua eam numquam relinquit.", wRecovery:"Locutio recuperationis — 12 verba", wReveal:"👁 Revela", wCopyBtn:"Exscribe", wWritten:"✓ Scriptum", wPrivKey:"Clavis privata (WIF)", wAdvanced:"Provecta — recupera, tantum spectare, exporta", wRestoreLbl:"Recupera e locutione 12 verborum aut clave WIF", wRestoreBtn:"Recupera crumenam", wWatchBtn:"Tantum spectare (clavis publica)", wImmortalize:"✦ Immortala", wFooter:"grafspace · in catena Bitcoin SV" },
    ui: {
      splashTag:"Quod pingis, id es. Te ipsum pinge.", splashTag2:"Nihil exsistit donec id pingas.", splashBegin:"▶ Incipe", splashResume:"↩ Redi ad mundum tuum", splashCreed:"In pacto confidimus",
      worldHdr:"Mundus tuus", namePh:"✎ Nomina mundum tuum…", kSave:"☁ Serva et communica", kReload:"↻ Mundum recarga", kExport:"📤 In tabellam serva (.bmf)", kImport:"📥 E tabella onera (.bmf)", kMint:"⬆ In catena serva", kChain:"⬇ E catena onera", kBack:"← Redi ad mundum tuum", kWallet:"👛 Aperi crumenam — pensum et NFT", kDone:"✓ Claude",
      keepTab:"◆ Index", exitBtn:"⏻ Exi", makeTab:"◆ Crea", spray:"Asperge", grab:"Cape", talk:"Loquere", own:"Posside / remisce", spread:"Dispersio", spNarrow:"angustus", spBroad:"medius", spWide:"latus",
      merchTag:"merces grafverse", merchH:"Indue graphidem.", merchSub:"grafverse tunicae, tabulae et plura.", merchCta:"🛍 Vise tabernam →", merchTeaser:"👕 Mox — indue mundum quem pinxisti.", merchSkip:"Non, gratias — perge →",
      hintMove:"WASD ut movearis · Spatium ut salias · mus ut spectes", hintMoveM:"Bacillus sinister ut movearis · trahe ut spectes", hintClick:"Preme ut spectes · WASD ut movearis · Spatium ut salias"
    }
  });
})();
