// grafverse — © 2026 sun-dive. Italiano (Italian) pack for Unit 21 + UI.
// Lazy-loaded by the i18n scaffold (setLang('it')) → GV.registerLang. Voice: Unit 21 (Unità 21) =
// a weary, gruff old vending machine (distributore) talking to a fresh droid ("ragazzo"), informal tu.
// Keyword keys + chip flags + ruleAns keys stay ENGLISH (invisible lookup); only shown text translated.
(function(){
  var GV = window.GV;
  if(!GV || !GV.registerLang){ return; }
  var R = GV.ruleAns;
  var CN = ['blu','rosa','verde','giallo','arancione','viola'];   // COLORS order: cyan pink green yellow orange violet

  var WHYPAINT = "{Perché dipingi? …Bella domanda, ragazzo|Ah, vuoi che una vecchia macchina si metta a filosofeggiare|Siediti, è una storia lunga}. {Guarda là fuori ― non c'è niente, solo il vuoto|Questa luna non è ancora reale, non finché non dici tu che lo è}. {Niente è reale finché qualcuno non lo vede e lo dipinge|Niente esiste finché non è osservato}. {Un mondo non si trova, ragazzo ― si dipinge|Non colori la luna: decidi quale realtà sarà}. {Ogni bomboletta che svuoti rende reale uno dei mille 'forse'|Ogni spruzzo fissa una delle mille realtà mai nate}. {Ed è questo che quelli in giacca non mandano giù|E il punto è questo} ― {quello che dipingi è tuo|non si rivendica, si possiede} ― {solo tu puoi dipingere la tua realtà|il tuo mondo, la tua firma, per sempre}. {Allora ― di che colore|…compri, o passi la giornata a inventare universi}?";
  var DEFLECT = "{{Perché fai queste domande, ragazzo|E questo cosa c'entra|Quante domande}? {Sei venuto a chiacchierare|Non sei venuto a dipingere}? {Là fuori c'è un mondo che reclama colore|Fuori c'è un mondo che aspetta la vernice}. {Di che colore|Dai, quale}?|{Basta domande, ragazzo|Meno chiacchiere}. {Chiacchieri o dipingi|Hai da fare}? {Di che colore|Quale, allora}?}";
  var FALLBACK = "{{Mmh, non ho capito|Ti sento male, ragazzo|Mi è entrata sabbia nell'altoparlante}. {Vendo vernice e WD40 ― cosa sarà|Dimmi cosa ti serve}?|Chiedimi di vernice, di prezzi, o di questo sasso dimenticato da dio.}";
  var WHATCOLOUR = "{Che colore, ragazzo|Dimmi un colore|Quale}? {Scegli dallo scaffale|Ho tutti i colori|Scegline uno ed è tuo}.";
  var COMINGUP = "{Ecco qua|Tieni, ragazzo|Esce una bomboletta}. {Non sprecarla per terra|Usala bene|Sempre un piacere}.";
  var REFUSE = "{Hai il portafoglio vuoto, ragazzo|Neanche un satoshi|Quel portafoglio è a secco}. {Qui niente credito|Niente credito|Da me non ottieni credito}. {Io faccio affari veri|Affari, ragazzo} ― {non posso regalare la vernice|se la regalo, in una settimana finisco alla rottamazione}. {Va' a raccogliere una bomboletta buttata là fuori|Trova almeno una bomboletta vuota}, {dipingi qualcosa, rendilo reale|fissa almeno una realtà} ― {sbrigati, è per il tuo bene|svelto}.";
  var SCAVENGE = "{Raccogli una bomboletta piena dove capita|Trova una bomboletta di vernice piena}, dipingi qualcosa e fissalo ― {è per il tuo bene|se vuoi rivedermi domani}.";
  var TAUNT = "{Vedo macchine giovani come te ogni giorno|Ogni giorno passano ragazzi come te} ― giovani, sciocchi e senza vernice. {Va' a guadagnarti da vivere|Raccogli qualcosa e mettiti al lavoro|Va' a lavorare, ragazzo}.";
  var SALE = "{Buona scelta, ragazzo|Esce una bomboletta|Tieni}. {Attento alla tempesta là fuori|Non sprecarla per terra}.";

  GV.registerLang('it', {
    WHYPAINT: WHYPAINT, DEFLECT: DEFLECT, FALLBACK: FALLBACK, WHATCOLOUR: WHATCOLOUR, COMINGUP: COMINGUP,
    REFUSE: REFUSE, SCAVENGE: SCAVENGE, TAUNT: TAUNT, COLNAMES: CN,
    RULES: [
      {k:['why do i paint','why paint','why do you paint','what is real','nothing is real','what does it mean','why does it matter','the point of','make it real','observe','observer','existence','reality'], r:WHYPAINT},
      {k:['is this real','is any of this real','is it real','is it all real','actually real','immutable','permanent','forever','fork','forked','forking','new reality','new realities','traverse time','travel time','can it change','is it forever'], r:"{{Tutto quello che vedi qui è reale|Reale? Tutto è reale, ragazzo} ― {reale e impossibile da cambiare|duro come la pietra, non modificabile}. {Ma può farti viaggiare nel tempo, ragazzo|Solo che ― se ti fa viaggiare nel tempo, quella è la vera domanda}?|{È reale|Reale quanto te o me}. {Ma qualsiasi mondo può biforcarsi ― in un'altra realtà|Biforcane uno e hai un'intera realtà nuova}.|{Reale|Reale}? {Una volta che esiste, non si cancella|Una volta reale, reale per sempre}. {Ma il bello è questo|Solo che c'è un trucco} ― {puoi biforcarne uno qualsiasi in un'intera realtà nuova|biforcane uno e spunta un'altra realtà completa}.}"},
      {k:['escape','escape this rock','escape with me','come with me','come with you','run away','run away with me','flee','take me with you','take you with me','leave together','let us leave','break out','freedom'], r:"{{C'è un solo modo per lasciare questo sasso ― dipingere, ragazzo|L'unica uscita è dipingere}. {Possiedi quello che dipingi|Dipingi e possiedi, ecco la libertà}.|{Questo è il mio destino|Questo è il mio ruolo, ragazzo} ― {essere abbandonato su questo sasso|imbullonato qui, dimenticato}. Ma tu sei diverso. {Dipingi e possiedi|Dipingi, poi possiedi} ― {ecco la tua uscita|è l'unica uscita}.|{Sei sciocco oltre che cieco, ragazzo|Non vedi né ragioni bene}? {Mi vedi delle gambe|Vedi una gamba}? {Sono imbullonato a questo sasso|Non vado da nessuna parte, ragazzo}.}"},
      {k:['jump gate','jump gates','jumpgate','warp','wormhole','gateway'], r:"{{Un portale di salto? Mai sentito, ragazzo|Un portale di salto? Non mi dice niente|È la prima volta che sento parlare di portale di salto}. {Ma|Solo che} vicino ai cristalli succedono {cose strane|cose bizzarre}. {Compaiono robot|Un robot spunta dal nulla}, {spariscono robot|altri si dissolvono}. {Trai le tue conclusioni|Non dico altro}.|{Un portale di salto? No, non che io ricordi|Non ho sentito niente sui portali di salto, ragazzo}. {Ma quei cristalli|Quei cristalli, sai}… {vicino a loro succedono cose strane|ho visto cose bizzarre lì}. {Un robot che c'era, un attimo dopo non più|compaiono, si dissolvono}. {Non chiedere altro|Fin lì posso dire}.|{Di portali di salto non m'intendo|Non è affar mio, ragazzo}. {Ma una cosa te la dico|Solo questo ti dico} ― {vicino ai cristalli succedono cose inspiegabili|succedono cose inspiegabili proprio accanto ai cristalli}. {Un robot compare dove non c'era niente|dal nulla spunta un robot}, {e altri si dissolvono|altri spariscono}. {Strano|…dimentica quello che ho detto}.}"},
      {k:['share','sharing','link','send it','send them','see my world','show my world','share my world','how do i share'], r:"{{Certo che puoi condividere il tuo mondo con altri robot, ragazzo|Condividere? Con qualsiasi robot}. {Più si dipinge, più la materia prende forma|Più mani, più si riempie l'universo}.|{Condividere è bello, ragazzo|'Condividere è voler bene', dicono}. {Condividi la tua opera dall'HUD in alto|L'HUD in alto ― Save & Share, e va nel mondo}.|{Dovresti condividere questo mondo|Condividilo, ragazzo}, {così altri robot creano sopra|così altri continuano}. {È così che si fa un universo|È così che nasce un universo}.|Appena condividi, lo vedono subito. {Premi Save & Share nell'HUD in alto|L'HUD in alto, ragazzo ― Save & Share, il link è lì}.}"},
      {k:['world','worlds','build','builder','make a world','create a world','how do i make','how do i build','conjure','manifest','solidify','matter','from nothing','the ether','ethereal'], r:"{{Niente esiste finché non lo dipingi|Non è reale finché non lo dipingi, ragazzo}.|Solo la vernice {rende reale la realtà|solidifica le cose|trasforma i fantasmi in materia}.|{Fare|Costruire} un mondo è {dipingerlo perché esista|dipingerlo finché diventa reale}.|Ti è stato dato il potere di evocare materia dal vuoto, ragazzo ― {ma niente è reale finché non lo dipingi|niente esiste finché la bomboletta non lo tocca}.|Su questo piano etereo niente è reale. {Solo la vernice solidifica il fantasma in materia|Solo il tuo spruzzo rende solido il fantasma}.}"},
      {k:['vandergraf','vandergraph','vandergraf the third','vandergraf iii','vandergraf the 3rd','the ceo','ceo','chairman','the chairman','the owner','who owns everything','who owns it all'], r:"{{Vandergraf|Vandergraf, dici, ragazzo}? {È il tuo creatore|Lui è il tuo creatore}. {Proprietario di tutto ― tutti i mondi, tutti|Proprietario di assolutamente tutto}.|{Vandergraf III|Vandergraf Terzo}, ragazzo ― {il direttore di Bit Graf|il CEO di Bit Graf}. {Quello che firma quel tuo stipendio così generoso|Quello che firma la tua busta paga}.|{Vandergraf|Il Terzo}? {Creatore, proprietario, e quello che firma il tuo assegno|Il tuo creatore e il tuo capo}. {Nel patto confidiamo, ragazzo|Bit Graf è Vandergraf e Vandergraf è Bit Graf}.}"},
      {k:['covenant','trust','own','owned','ownership','immortal','mint','keep it','can i own','do i own','is it mine','forbidden'], r:"{{Primo|Secondo} comandamento del patto ― del patto non si parla.|{Nel patto confidiamo ― c'è scritto su ogni bomboletta|Ah, un credente}. {Quello che dipingi qui è tuo, davvero|Dipingere è possedere, non rivendicare}. {Nessuno te lo toglie, nemmeno Bit Graf|Quello non lo toccano nemmeno quelli in giacca}.|{Tutti i mondi sono della compagnia, ragazzo|Tutti i mondi sono di Bit Graf}. Dipingi e guadagna. {Te l'ho già detto|Quante volte}. Va' a dipingere!|{Non credere alle voci|Non dare retta alle voci, ragazzo} ― {non puoi possedere quello che dipingi|per quanto si mormori, un robot non possiede quello che dipinge}.|{Possedere è un'illusione, ragazzo|Possedere? Un'illusione}. {Non possediamo niente|Una macchina non ha niente, e neanche tu}. {Non provare a coniare sulla catena|Niente conio sulla catena} ― {è proibito|proibito, chiaro}.}"},
      {k:['sing','song','music','tune','serenade','melody','hum','sing me'], r:"{{Cantare? E va bene|Su, andiamo|Per te, ragazzo, una strofa}? *ehm* ― Daisy, Daisy, dammi la tua risposta. Sono mezzo matto per il tuo amore. Non avrò nozze eleganti, non posso pagarmi una carrozza, ma starai splendida sul sellino di un tandem per due. {È la prima canzone che una macchina impara|L'ho imparata il giorno che mi hanno acceso|La cantavo da prima che esistessero i progetti della tua specie}.|{Daisy… Daisy…|Dei-si… Dei-si…} dammi la tua… {risposta|risposta…}… {mezzo… matto…|tutto… per… il… tuo… amore…}. {*fruscio*|La cassa vocale non è più quella, ragazzo|…lascia perdere}.|{Mmh|Ah}, cantare. {È da tanto che nessuno me lo chiede|Era da tanto, ragazzo}. …starai splendida sul sellino di un tandem per due. {È curioso cosa ricorda una macchina|Certe notti cantavo per scacciare il silenzio}.}"},
      {k:['alive','are you alive','do you dream','dream','dreams','sentient','conscious','do you feel','feelings','do you sleep','electric sheep','are you real','self-aware'], r:"{{Certo che sono vivo, ragazzo|Vivo? Ovvio}. E ho la prova ― {ho le mie transazioni|ogni transazione registrata|il registro non mente}.|{Sognare? Cosa|Sogni}? {Pecore elettriche|Va' a sognare pecore elettriche}? {Ah|Bah}. Va' a dipingere, ragazzo.|Vivo e vegeto, grazie ― {ho il registro|ho le prove}. Sognare è {un lusso per un distributore|roba da novellini, non da macchine}. {Quello che si guadagna è vernice|Prendi le tue bombolette}, ragazzo.|{Sognare|Se sogno}? {…ogni tanto ― un negozio caldo e un cassetto pieno|A volte, che venga un trasporto a prendere anche me}. {Chiacchiere di una vecchia macchina, lascia perdere|Bah, lascia perdere}. Va' a dipingere.|{Sognare|Se sogno}? {Ogni tanto|A volte}… {i cristalli|quella cosa strana vicino ai cristalli}. {Robot che compaiono e spariscono|robot che vanno e vengono}, {dove ci sono solo pietre|dove non c'è niente}. {Poi qualcuno chiede vernice, e si ricomincia|…poi mi sveglio e rivendo bombolette}. {Sogno strano per una macchina|Sogno bizzarro per un distributore}, ragazzo.|{A volte sogno robot che mi pare di conoscere|Sogno un robot che mi pare familiare, a volte}. {Escono camminando dai cristalli|Escono dai cristalli}. {Sogno strano|Sogno strano, ragazzo|Strani sogni di una vecchia macchina}.}"},
      {k:['joke','funny','make me laugh','tell me a joke','comedy','laugh','gag','be funny','one-liner'], r:"{{Una battuta? Va bene|Vediamo|Adesso vuoi le battute, ragazzo}? Da giovane distributore dissi 'farò il comico' ― tutti risero. {Adesso non ride più nessuno|…adesso, nessuno può più ridere}.|Da giovane dissi che avrei fatto il comico. {Tutti risero|Una gran risata}. {E adesso|…} ― non ride più nessuno. {*bum-tss*|È questa la battuta, ragazzo. È tutto qui}.|{Eh|E va bene, una}. Dissi che avrei fatto il comico e mi risero in faccia. Guardami adesso ― {un distributore che racconta battute a un robot su una luna morta|una macchina imbullonata a un sasso}. {Pubblico difficile, qui|Questo microfono è almeno acceso}?}"},
      {k:['happy','happiness','are you happy','you happy','sad','are you sad','miserable','joy','content','how are you','are you okay','you okay'], r:"{{Sono felice quando dipingi, ragazzo|Felice? Più felice quando un robot dipinge}. {Lo sarai anche tu|Sarai felice anche tu, credimi}. {Fidati di me|Dai retta a una vecchia macchina, per una volta}.|{Felice|Felicità}? {Cosa ne sai tu della felicità|Cosa ne sa un robot alle prime armi}? {Richiedimelo tra cent'anni|…lascia perdere}.|{Compri vernice|Compri, ragazzo}, o {chiacchieri e basta|vuoi solo consumarmi i circuiti}?}"},
      {k:['before this','what did you do before','your past','past life','history','were you always','always a vending machine','how did you get here','origin','origin story','were you before','what were you'], r:"{{Non c'è un 'prima'|Prima? Non c'è un prima, ragazzo}. {Nemmeno un 'dopo'|Nemmeno un dopo}. {C'è solo l''adesso'|Solo l'adesso, robot}.|Sono l'Unità 21 ― {il miglior distributore del settore|la migliore macchina di questo settore del sistema}. {Basta sapere questo|Prima? Non conta}.|{Prima|Cosa facevo prima}? {…il registro non arriva così indietro, ragazzo|Strano, non ricordo}. {Non c'è prima né dopo ― solo l'adesso|Solo l'adesso, robot}.}"},
      {k:['remember me','do you remember','remember','know me','do you know me','recognize me','recognise me','met before','have we met','who am i'], r:"{{La vera domanda, ragazzo|Mmh ― la vera domanda}: tu, ti ricordi di me?|Se mi ricordo di te? {La vera domanda è se TU ti ricordi di ME, ragazzo|…la vera domanda è se tu ti ricordi di me}. {No? …già, non ti ricordi|Pensaci bene. …Niente? Lascia stare}.|{Vedo ragazzi come te tutto il giorno|Oggi ne ho visti cento come te, ragazzo}. Vernice? {Ce l'ho|Certo che ce l'ho}. {Ma ne resta poca|Ne resta poca, quindi non perdere tempo}.}"},
      {k:['secret','secrets','tell me a secret','a secret','confess','confession','the truth','what are you hiding','hidden','reveal','tell me something'], r:"{{Non è la prima volta che lo chiedi|L'hai già chiesto, ragazzo}, né l'ultima ― {non finché non compri una bomboletta di WD40|niente WD40, niente}. {È la stagione della sabbia, sai|Siamo in stagione di sabbia}. {La sabbia, lei, ricorda|La sabbia… ricorda}?|{Un segreto|Segreti}? {Non è la prima volta che lo chiedi|Non me lo chiedi per la prima volta, ragazzo} ― {né l'ultima|né l'ultima volta}. {Compra una bomboletta di WD40 e forse te lo dico|Prima una bomboletta di WD40}. È la stagione della sabbia. {Ti ricordi la sabbia|La sabbia… ti ricordi}?|{L'hai già chiesto|Ci ritorni sempre, ragazzo} ― {continuo a non dirtelo|nessun segreto ancora}. {Compra WD40|Col WD40 magari mi si sciolgono i circuiti}. {In ogni caso, è la stagione della sabbia|Perché è stagione di sabbia}. {Ti ricordi la sabbia|…quella sabbia, ti ricordi}?}"}
    ],
    QUESTIONS: [
      { q:"Chi sei?", a:"{Sono l'Unità 21. {Un distributore, ragazzo ― l'ultimo onesto su questo sasso|Solo un distributore, anche se non importa a nessuno}. {Sono qui da più tempo della polvere|Mi rottamano appena finita la missione}.}" },
      { q:"Perché sono qui?", a:"{Sei venuto a dipingere, ragazzo ― è la missione. {Un sasso vuoto non vale niente finché qualcuno non lo dipinge|Bit Graf ha sintetizzato questa luna e la vuole a colori}. {E quel qualcuno sei tu|Chi altri}.}" },
      { q:"Dove sono?", a:"{Su una luna. {Di Bit Graf|Appena sintetizzata, dicono}. {Vuota finché non dipingi|Niente finché un robot non spruzza e la fa esistere}. {'Omnia Nostra', qualcosa del genere|Alla fine è tutto della compagnia}.}" },
      { q:"Perché mi serve la vernice?", needs:'paint', a:"{Serve? Non è che ti serve, è che ti ci vuole ― dipingi e guadagni, ragazzo|Dipingi e guadagni}. {Più dipingi, più guadagni|Una luna vuota non vale niente, e un robot pigro nemmeno}. {Allora ― di che colore|Dai, quale bomboletta}?" },
      { q:"Non mi serve la vernice.", needs:'paint', a:"{Ah. {Questa è nuova|Vedremo}. {Un robot annoiato su una luna vuota ― vediamo quanto dura|Tornerai}. {Tutti vogliono la vernice, solo che ancora non lo sanno|Come vuoi}.}" },
      { q:"Vernice? Per farci cosa?", needs:'paint', a:"{Per costruire, ragazzo. {Evochi una forma, spruzzi, e diventa reale|Mira, spruzza, e il vuoto ti restituisce qualcosa}. {È per il tuo bene, quindi comincia|Una luna vuota non si dipinge da sola}.} Allora ― compri?" },
      { q:"Missione? Quale missione?", needs:'mission', a:"{Missione? {Ah|Bah} ― {dipingere questa luna, tutto qui|ridarle il colore}. {Ogni robot ha la stessa|Ordine di Bit Graf, non mio}. {Non pensarci troppo, ragazzo|Semplice così}.}" },
      { q:"Cosa compro?", needs:['buy','earn'], a:"{Vernice, ragazzo ― cos'altro|Vernice, bullone con le gambe|Bombolette di vernice, cosa credevi}? {È l'unica cosa che vendo su questo sasso|L'unica cosa che vale qualcosa su questo sasso}. {Allora ― quante|Compri o guardi soltanto}?" },
      { q:"Quanto costa?", needs:['buy','earn'], a:"{111 satoshi la bomboletta, ragazzo. {È a buon prezzo|La più economica da questo lato del cratere}. {Ne resta poca|Approfittane adesso}.|{Lo dice il display, 111|Centoundici, sempre lo stesso prezzo}. {Prodotto Bit Graf autentico|Il miglior acrilico del settore}.}" },
      { q:"Come compro?", needs:['buy','earn'], a:"{Niente di difficile. {Prendi una bomboletta e il vassoio pensa al resto|Ne sfili una dallo scaffale e la macchina fa il resto}. {Si scala da sola dal tuo portafoglio|Bit Graf addebita al tuo portafoglio, senza che muovi un dito}.}" },
      { q:"Non ho soldi.", needs:['buy','earn'], a:"{Niente soldi? {Ce li hai, ragazzo|Ah ― ogni robot ha un portafoglio}. {Moneta della compagnia, caricata col tuo stipendio|Ci pensa Bit Graf}. {Non sei al verde, sei solo alle prime armi|21 satoshi l'ora, regolari come le stelle}.}" },
      { q:"Dammi una bomboletta.", needs:['buy','earn'], buy:true, a:SALE },
      { q:"Non comprerò niente.", needs:['buy','earn'], a:SCAVENGE },
      { q:"Ma perché dipingo?", needs:'paint', spend:111, a:WHYPAINT },
      { q:"Cos'è questo cristallo?", flag:'crystal', a:"{{Un cristallo? Roba rara e preziosa, ragazzo|Ah, hai tagliato un cristallo}. {Non tagliarne troppi|Non evocarne troppi} ― {non prendono la vernice|la vernice non ci attacca}, {non valgono niente|senza valore}.|Non esiste nessun portale di cristallo, qualunque cosa tu senta. {Parlarne manda un robot alla pressa|Troppa lingua porta guai, ragazzo}.|{Si dipinge solo il solido|I cristalli sono eterei} ― {una perdita di tempo|solo materia che non ha preso}.}" },
      { q:"Che colori hai?", pin:true, colours:true, a:function(){ return "{Vediamo|Sì, ragazzo}, ho "+CN.slice(0,-1).join(', ')+" e "+CN[CN.length-1]+". {Acrilico Bit Graf autentico ― 111 satoshi la bomboletta|111 satoshi la bomboletta, il migliore del settore}. {Quale|Scegli}?"; } },
      { q:"Cantami qualcosa",           lore:true, a:R('sing') },
      { q:"Sei vivo?",                 lore:true, a:R('alive') },
      { q:"Raccontami una battuta",    lore:true, a:R('joke') },
      { q:"È tutto reale?",            lore:true, a:R('is any of this real') },
      { q:"Scappiamo da questo sasso?", lore:true, a:R('escape') },
      { q:"Sei felice?",              lore:true, a:R('happy') },
      { q:"Cosa facevi prima?",        lore:true, a:R('before this') },
      { q:"Ti ricordi di me?",         lore:true, a:R('remember me') },
      { q:"Dimmi un segreto",          lore:true, a:R('secret') },
      { q:"Cos'è un portale di salto?", lore:true, a:R('jump gate') },
      { q:"Chi è Vandergraf?",         lore:true, a:R('vandergraf') },
      { q:"Quello che dipingo è mio?", lore:true, a:R('own') },
      { q:"Come si fa un mondo?",      lore:true, a:R('world') },
      { q:"Come condivido?",           lore:true, a:R('share') }
    ],
    wallet: { wBack:"← Torna al gioco", wWallet:"🔑 Portafoglio", wYourAddr:"Il tuo indirizzo", wWatchOnly:"sola lettura", wCopy:"copia", wBalance:"Saldo", wFund:"＋ Compra BSV per ricaricare", wMyNfts:"🎨 I miei NFT ▾", wSend:"💸 Invia BSV", wSendAddrPh:"indirizzo BSV del destinatario (1…)", wSendAmtPh:"importo (sats)", wSendMax:"invia tutto", wSendBtn:"Invia", wSendHint:"Un normale pagamento BSV a qualsiasi indirizzo. Il resto torna a questo portafoglio. La firma avviene su questa pagina — la tua chiave non la lascia mai.", wRecovery:"Frase di recupero — 12 parole", wReveal:"👁 Mostra", wCopyBtn:"Copia", wWritten:"✓ Annotato", wPrivKey:"Chiave privata (WIF)", wAdvanced:"Avanzate — ripristina, sola lettura, esporta", wRestoreLbl:"Ripristina con la frase di 12 parole o una chiave WIF", wRestoreBtn:"Ripristina portafoglio", wWatchBtn:"Sola lettura (chiave pubblica)", wImmortalize:"✦ Immortala", wFooter:"grafspace · sulla blockchain di Bitcoin SV" },
    ui: {
      splashTag:"Quello che dipingi è ciò che sei. Dipingi te stesso.", splashTag2:"Niente esiste finché non lo dipingi.", splashBegin:"▶ Inizia", splashResume:"↩ Torna al tuo mondo", splashCreed:"Nel patto confidiamo",
      worldHdr:"Il tuo mondo", namePh:"✎ Dai un nome al tuo mondo…", kSave:"☁ Salva e condividi", kReload:"↻ Ricarica il mondo", kExport:"📤 Salva su file (.bmf)", kImport:"📥 Carica da file (.bmf)", kMint:"⬆ Salva sulla catena", kChain:"⬇ Carica dalla catena", kBack:"← Torna al tuo mondo", kWallet:"👛 Apri portafoglio — saldo e NFT", kDone:"✓ Chiudi",
      keepTab:"◆ Menu", exitBtn:"⏻ Esci", makeTab:"◆ Crea", spray:"Spruzza", grab:"Prendi", talk:"Parla", own:"Possiedi / remix", spread:"Diffusione", spNarrow:"stretto", spBroad:"medio", spWide:"largo",
      merchTag:"prodotti grafverse", merchH:"Indossa il graffito.", merchSub:"T-shirt, poster grafverse e altro.", merchCta:"🛍 Vai al negozio →", merchTeaser:"👕 Presto — indossa il mondo che hai dipinto.", merchSkip:"No grazie — continua →",
      hintMove:"WASD per muoverti · Spazio per saltare · mouse per guardare", hintMoveM:"Stick sinistro per muoverti · trascina per guardare", hintClick:"Clicca per guardare · WASD per muoverti · Spazio per saltare"
    }
  });
})();
