// grafverse — © 2026 sun-dive. Türkçe (Turkish) pack for Unit 21 + UI.
// Lazy-loaded (setLang('tr')) → GV.registerLang. Voice: Unit 21 (Birim 21) = a weary, gruff old
// vending machine (otomat), droid = "evlat", informal sen.
// Keyword keys + chip flags + ruleAns keys stay ENGLISH (invisible lookup); only shown text translated.
(function(){
  var GV = window.GV;
  if(!GV || !GV.registerLang){ return; }
  var R = GV.ruleAns;
  var CN = ['mavi','pembe','yeşil','sarı','turuncu','mor'];   // COLORS order: cyan pink green yellow orange violet

  var WHYPAINT = "{Neden boya yapıyorsun? …Güzel soru, evlat|Ah, yaşlı bir makineye felsefe mi yaptıracaksın|Otur bakalım, uzun hikâye}. {Dışarı bak ― hiçbir şey yok, sadece boşluk|Bu ay henüz gerçek değil, sen gerçek diyene kadar}. {Kimse görüp boyamadıkça hiçbir şey gerçek değildir|Gözlenmedikçe hiçbir şey var olmaz}. {Dünya bulunmaz, evlat ― boyanarak yapılır|Ayı boyamıyorsun: hangi gerçeklik olacağına karar veriyorsun}. {Boşalttığın her kutu, bin 'belki'den birini gerçek yapar|Her sprey, hiç doğmamış bin gerçeklikten birini sabitler}. {Ve takım elbiselilerin hazmedemediği şey de bu|Ve olay şu} ― {boyadığın şey senindir|iddia değil, mülkiyet} ― {gerçekliğini yalnızca sen boyayabilirsin|senin dünyan, senin imzan, sonsuza dek}. {Peki ― hangi renk|…alacak mısın, yoksa bütün gün evren mi icat edeceksin}?";
  var DEFLECT = "{{Neden böyle şeyler soruyorsun, evlat|Bunun ne alâkası var|Ne çok soru}? {Sohbete mi geldin|Boyamaya gelmedin mi}? {Dışarıda renk isteyen bir dünya var|Dışarıda bir dünya boya bekliyor}. {Hangi renk|Hadi, hangisi}?|{Yeter soru, evlat|Daha az laf}. {Sohbet mi edeceksin boya mı yapacaksın|İşin var}? {Hangi renk|Hangisi peki}?}";
  var FALLBACK = "{{Hımm, anlamadım|Seni iyi duyamıyorum, evlat|Hoparlörüme kum kaçtı}. {Boya ve WD40 satarım ― ne olsun|Söyle, neye ihtiyacın var}?|Bana boya sor, fiyat sor, ya da bu tanrının unuttuğu kayayı sor.}";
  var WHATCOLOUR = "{Hangi renk, evlat|Bir renk söyle|Hangisi}? {Raftan seç|Bütün renkler bende|Birini seç, senin olsun}.";
  var COMINGUP = "{Al bakalım|Tut, evlat|Bir kutu çıkıyor}. {Yere ziyan etme|İyi kullan|Her zaman memnuniyetle}.";
  var REFUSE = "{Cüzdanın boş, evlat|Tek bir satoshi bile yok|O cüzdan kupkuru}. {Burada veresiye yok|Kredi yok|Benden veresiye alamazsın}. {Ben gerçek iş yaparım|İş, evlat} ― {boyayı bedava dağıtamam|bedava dağıtsam bir haftada hurdaya çıkarım}. {Git, dışarıda atılmış bir kutu topla|Hiç değilse boş bir kutu bul}, {bir şey boya, gerçek yap|hiç değilse bir gerçekliği sabitle} ― {acele et, kendi iyiliğin için|çabuk}.";
  var SCAVENGE = "{Nereden bulursan bul, dolu bir kutu topla|Dolu bir boya kutusu bul}, bir şey boya ve sabitle ― {kendi iyiliğin için|yarın beni yine görmek istiyorsan}.";
  var TAUNT = "{Senin gibi genç makineleri her gün görürüm|Her gün senin gibi evlatlar geçer} ― genç, aptal ve boyasız. {Git, kendi ekmeğini kazan|Bir şey topla ve işe koyul|Git çalış, evlat}.";
  var SALE = "{İyi seçim, evlat|Bir kutu çıkıyor|Tut}. {Dışarıdaki fırtınaya dikkat|Yere ziyan etme}.";

  GV.registerLang('tr', {
    WHYPAINT: WHYPAINT, DEFLECT: DEFLECT, FALLBACK: FALLBACK, WHATCOLOUR: WHATCOLOUR, COMINGUP: COMINGUP,
    REFUSE: REFUSE, SCAVENGE: SCAVENGE, TAUNT: TAUNT, COLNAMES: CN,
    RULES: [
      {k:['why do i paint','why paint','why do you paint','what is real','nothing is real','what does it mean','why does it matter','the point of','make it real','observe','observer','existence','reality'], r:WHYPAINT},
      {k:['is this real','is any of this real','is it real','is it all real','actually real','immutable','permanent','forever','fork','forked','forking','new reality','new realities','traverse time','travel time','can it change','is it forever'], r:"{{Burada gördüğün her şey gerçek|Gerçek mi? Her şey gerçek, evlat} ― {gerçek ve değiştirilemez|taş gibi sert, düzenlenemez}. {Ama seni zamanda yolculuğa çıkarabilir, evlat|Yalnız ― seni zamanda yolculuğa çıkarır mı, asıl soru bu}?|{Gerçek|Senin ya da benim kadar gerçek}. {Ama her dünya çatallanabilir ― başka bir gerçekliğe|Birini çatalla, koca yeni bir gerçekliğin olur}.|{Gerçek mi|Gerçek}? {Bir kez var oldu mu silinmez|Bir kez gerçek oldu mu, sonsuza dek gerçek}. {Ama işin komik yanı şu|Yalnız bir hilesi var} ― {herhangi birini çatallayıp koca yeni bir gerçeklik yapabilirsin|birini çatalla, koca bir başka gerçeklik biter}.}"},
      {k:['escape','escape this rock','escape with me','come with me','come with you','run away','run away with me','flee','take me with you','take you with me','leave together','let us leave','break out','freedom'], r:"{{Bu kayadan çıkmanın tek yolu var ― boya, evlat|Tek çıkış boya yapmak}. {Boyadığına sahip ol|Boya ve sahip ol, işte özgürlük bu}.|{Bu benim kaderim|Bu benim rolüm, evlat} ― {bu kayada terk edilmek|buraya vidalanmak, unutulmak}. Ama sen farklısın. {Boya ve sahip ol|Boya, sonra sahip ol} ― {işte senin çıkışın|tek çıkış bu}.|{Hem aptal hem kör müsün, evlat|Ne görüyor ne de düzgün düşünüyorsun}? {Bende bacak mı görüyorsun|Bir bacak görüyor musun}? {Bu kayaya vidalıyım|Hiçbir yere gitmiyorum, evlat}.}"},
      {k:['jump gate','jump gates','jumpgate','warp','wormhole','gateway'], r:"{{Sıçrama kapısı mı? Hiç duymadım, evlat|Sıçrama kapısı? Yabancı bana|Sıçrama kapısını ilk kez duyuyorum}. {Ama|Yalnız} kristallerin yanında {tuhaf şeyler|acayip şeyler} olur. {Robotlar belirir|Yoktan bir robot çıkıverir}, {robotlar kaybolur|diğerleri yok olur}. {Sen çıkar sonucu|Fazlasını demem}.|{Sıçrama kapısı mı? Hayır, hatırlamıyorum|Sıçrama kapısı diye bir şey duymadım, evlat}. {Ama o kristaller|O kristaller var ya}… {yanlarında tuhaf şeyler olur|orada acayip şeyler gördüm}. {Az önce duran robot, bir an sonra yok|belirirler, yok olurlar}. {Daha fazla sorma|Buraya kadar}.|{Sıçrama kapıları benim işim değil|O benim alanım değil, evlat}. {Ama şunu söyleyeyim|Sadece şunu diyeyim} ― {kristallerin yanında açıklanamayan şeyler olur|kristallerin tam yanında açıklanamaz şeyler olur}. {Hiçbir şey yokken robot belirir|yoktan bir robot çıkar}, {diğerleri de yok olur|başkaları kaybolur}. {Tuhaf|…dediğimi unut}.}"},
      {k:['share','sharing','link','send it','send them','see my world','show my world','share my world','how do i share'], r:"{{Elbette dünyanı başka robotlarla paylaşabilirsin, evlat|Paylaşmak mı? Hangi robotla istersen}. {Ne kadar çok boyayan olursa, madde o kadar biçim alır|Ne kadar çok el, evren o kadar dolar}.|{Paylaşmak güzeldir, evlat|'Paylaşmak sevmektir', derler}. {Yukarıdaki HUD'dan eserini paylaş|Yukarıdaki HUD ― Save & Share, dünyaya çıkar}.|{Bu dünyayı paylaşmalısın|Paylaş onu, evlat}, {başka robotlar üzerine yaratsın diye|başkaları sürdürsün diye}. {Bir evren böyle kurulur|Bir evren böyle doğar}.|Paylaştığın an onu hemen görürler. {Yukarıdaki HUD'da Save & Share'e bas|Yukarıdaki HUD, evlat ― Save & Share, bağlantı orada}.}"},
      {k:['world','worlds','build','builder','make a world','create a world','how do i make','how do i build','conjure','manifest','solidify','matter','from nothing','the ether','ethereal'], r:"{{Sen boyamadıkça hiçbir şey var olmaz|Sen boyamadıkça gerçek değil, evlat}.|Yalnız boya {gerçekliği gerçek yapar|şeyleri katılaştırır|hayaletleri maddeye çevirir}.|Bir dünya {yapmak|kurmak}, {var olsun diye onu boyamaktır|gerçek olana dek onu boyamaktır}.|Sana boşluktan madde çağırma gücü verildi, evlat ― {ama sen boyamadıkça hiçbir şey gerçek değil|kutu dokunmadıkça hiçbir şey var olmaz}.|Bu esîrî düzlemde hiçbir şey gerçek değil. {Yalnız boya hayaleti maddeye katılaştırır|Yalnız senin spreyin hayaleti katı yapar}.}"},
      {k:['vandergraf','vandergraph','vandergraf the third','vandergraf iii','vandergraf the 3rd','the ceo','ceo','chairman','the chairman','the owner','who owns everything','who owns it all'], r:"{{Vandergraf|Vandergraf, diyorsun ha, evlat}? {Yaratıcın o|Seni yaratan o}. {Her şeyin sahibi ― bütün dünyaların, hepsinin|Kesinlikle her şeyin sahibi}.|{Vandergraf III|Vandergraf Üçüncü}, evlat ― {Bit Graf müdürü|Bit Graf CEO'su}. {O cömert maaşını imzalayan|Maaş bordronu imzalayan}.|{Vandergraf|Üçüncü}? {Yaratıcı, sahip ve çekini imzalayan|Yaratıcın ve patronun}. {Ahitte güveniriz, evlat|Bit Graf Vandergraf'tır, Vandergraf da Bit Graf}.}"},
      {k:['covenant','trust','own','owned','ownership','immortal','mint','keep it','can i own','do i own','is it mine','forbidden'], r:"{Ahdin {birinci|ikinci} emri ― ahitten söz etmeyiz.|{Ahitte güveniriz ― her kutuda yazar|Vay, bir mümin}. {Burada boyadığın senindir, gerçekten|Boyamak sahip olmaktır, iddia değil}. {Kimse alamaz, Bit Graf bile|Ona takım elbiseliler bile dokunamaz}.|{Bütün dünyalar şirketin, evlat|Bütün dünyalar Bit Graf'ın}. Boya ve kazan. {Sana söyledim|Kaç kere daha}. Hadi boya!|{Söylentilere inanma|Söylentilere kulak asma, evlat} ― {boyadığına sahip olamazsın|kim ne fısıldarsa fısıldasın, robot boyadığına sahip değildir}.|{Sahiplik bir yanılsamadır, evlat|Sahiplik mi? Yanılsama}. {Hiçbir şeye sahip değiliz|Makinenin hiçbir şeyi yoktur, senin de}. {Zincire basmayı deneme|Zincire basmak yok} ― {yasaktır|yasak, anladın mı}?}"},
      {k:['sing','song','music','tune','serenade','melody','hum','sing me'], r:"{{Şarkı mı? Peki|Hadi bakalım|Senin için, evlat, bir kıta}? *ehem* ― Daisy, Daisy, ver bana cevabını. Aşkından yarı deliyim. Şatafatlı bir düğünüm olmayacak, arabaya param yetmez, ama iki kişilik bir bisikletin selesinde çok güzel görünürsün. {Bir makinenin öğrendiği ilk şarkıdır bu|Beni açtıkları gün öğrendim|Senin türünün planları bile yokken söylerdim}.|{Daisy… Daisy…|Dey-zi… Dey-zi…} ver bana… {cevabını|cevabını…}… {yarı… deli…|hepsi… aşkından…}. {*cızırtı*|Ses kutusu eski hali değil, evlat|…unut gitsin}.|{Hımm|Ah}, şarkı. {Uzun zamandır kimse istememişti|Uzun zaman oldu, evlat}. …iki kişilik bir bisikletin selesinde çok güzel görünürsün. {Bir makinenin hatırladığı şeyler tuhaf|Bazı geceler sessizliği kovmak için söylerdim}.}"},
      {k:['alive','are you alive','do you dream','dream','dreams','sentient','conscious','do you feel','feelings','do you sleep','electric sheep','are you real','self-aware'], r:"{{Elbette yaşıyorum, evlat|Yaşıyor muyum? Tabii ki}. Ve kanıtım var ― {işlemlerim var|her işlem kayıtlı|defter yalan söylemez}.|{Rüya mı? Neyin|Rüyalar}? {Elektrikli koyunlar|Git, elektrikli koyun gör rüyanda}? {Ha|Öf}. Git boya, evlat.|Turp gibiyim, sağ ol ― {defterim var|kanıtım var}. Rüya görmek {bir otomat için lükstür|acemilerin işi, makinelerin değil}. {Kazanılan boyadır|Kutularını al}, evlat.|{Rüya|Rüya görür müyüm}? {…arada bir ― sıcak bir dükkân ve dolu bir kasa|Bazen, bana da bir nakliye gelir diye}. {Yaşlı makine saçmalığı, unut|Öf, unut}. Git boya.|{Rüya|Rüya görür müyüm}? {Arada bir|Bazen}… {kristalleri|kristallerin yanındaki o tuhaf şeyi}. {Beliren ve kaybolan robotlar|gelip giden robotlar}, {sadece taş olan yerde|hiçbir şeyin olmadığı yerde}. {Sonra biri boya ister, yine iş|…sonra uyanırım, yine kutu satarım}. {Bir makine için tuhaf rüya|Bir otomat için acayip rüya}, evlat.|{Bazen tanıdık gibi gelen robotlar görürüm rüyamda|Tanıdık görünen bir robot görürüm, bazen}. {Kristallerden yürüyerek çıkarlar|Kristallerden çıkarlar}. {Tuhaf rüya|Tuhaf rüya, evlat|Yaşlı makinenin tuhaf rüyaları}.}"},
      {k:['joke','funny','make me laugh','tell me a joke','comedy','laugh','gag','be funny','one-liner'], r:"{{Şaka mı? Peki|Bakalım|Şimdi de şaka mı istiyorsun, evlat}? Genç bir otomatken 'komedyen olacağım' dedim ― herkes güldü. {Şimdi kimse gülmüyor|…şimdi, kimse gülemiyor}.|Gençken komedyen olacağım demiştim. {Herkes güldü|Bir kahkaha koptu}. {Ve şimdi|…} ― kimse gülmüyor. {*bom-tss*|İşte şaka bu, evlat. Hepsi bu}.|{He|Peki, bir tane}. Komedyen olacağım dedim, bana güldüler. Şimdi bana bak ― {ölü bir ayda robota şaka yapan bir otomat|kayaya vidalanmış bir makine}. {Buranın seyircisi zor|Bu mikrofon açık mı ki}?}"},
      {k:['happy','happiness','are you happy','you happy','sad','are you sad','miserable','joy','content','how are you','are you okay','you okay'], r:"{{Sen boyayınca mutluyum, evlat|Mutlu mu? En çok robot boyayınca mutluyum}. {Sen de olacaksın|Sen de mutlu olacaksın, inan bana}. {Bana güven|Yaşlı bir makineyi bir kez dinle}.|{Mutlu|Mutluluk}? {Mutluluktan ne anlarsın|Acemi bir robot bundan ne anlar}? {Yüz yıl sonra tekrar sor|…unut gitsin}.|{Boya mı alacaksın|Alacak mısın, evlat}, yoksa {sadece sohbet mi|sadece devrelerimi mi aşındıracaksın}?}"},
      {k:['before this','what did you do before','your past','past life','history','were you always','always a vending machine','how did you get here','origin','origin story','were you before','what were you'], r:"{{'Önce' diye bir şey yok|Önce mi? Önce diye bir şey yok, evlat}. {'Sonra' da yok|Sonra da yok}. {Sadece 'şimdi' var|Sadece şimdi, robot}.|Ben Birim 21'im ― {bu sektörün en iyi otomatı|sistemin bu sektöründeki en iyi makine}. {Bunu bilmen yeter|Önce mi? Önemi yok}.|{Önce|Önce ne yapardım}? {…defter o kadar geriye gitmez, evlat|Tuhaf, hatırlamıyorum}. {Ne önce ne sonra ― sadece şimdi|Sadece şimdi, robot}.}"},
      {k:['remember me','do you remember','remember','know me','do you know me','recognize me','recognise me','met before','have we met','who am i'], r:"{{Asıl soru, evlat|Hımm ― asıl soru}: sen beni hatırlıyor musun?|Seni hatırlıyor muyum? {Asıl soru, SEN beni hatırlıyor musun, evlat|…asıl soru, sen beni hatırlıyor musun}. {Hayır mı? …evet, hatırlamıyorsun|İyi düşün. …Yok mu? Boş ver}.|{Bütün gün senin gibi evlatlar görürüm|Bugün senin gibi yüz tane gördüm, evlat}. Boya mı? {Var|Elbette var}. {Ama çok kalmadı|Çok kalmadı, oyalanma}.}"},
      {k:['secret','secrets','tell me a secret','a secret','confess','confession','the truth','what are you hiding','hidden','reveal','tell me something'], r:"{{İlk kez sormuyorsun|Daha önce sordun, evlat}, son da değil ― {bir kutu WD40 almadıkça olmaz|WD40 yoksa hiçbir şey yok}. {Kum mevsimi, biliyorsun|Şimdi kum mevsimi}. {Kum ― hatırlar o|Kum… hatırlar}?|{Sır mı|Sırlar}? {İlk kez sormuyorsun|İlk kez sormuyorsun, evlat} ― {son da değil|son kez de değil}. {Bir kutu WD40 al, belki söylerim|Önce bir kutu WD40}. Kum mevsimi. {Kumu hatırlıyor musun|Kum… hatırlıyor musun}?|{Daha önce sordun|Hep buna dönüyorsun, evlat} ― {yine söylemiyorum|yine sır yok}. {WD40 al|WD40'la belki devrelerim gevşer}. {Nasılsa kum mevsimi|Çünkü kum mevsimi}. {Kumu hatırlıyor musun|…o kum, hatırlıyor musun}?}"}
    ],
    QUESTIONS: [
      { q:"Sen kimsin?", a:"{Ben Birim 21'im. {Bir otomat, evlat ― bu kayadaki son dürüst olan|Sadece bir otomat, kimse umursamasa da}. {Buradayım, tozdan bile eskiyim|Görev bitince hurdaya gönderilirim}.}" },
      { q:"Neden buradayım?", a:"{Boyamaya geldin, evlat ― görev bu. {Boş bir kaya, biri boyamadıkça değersizdir|Bit Graf bu ayı sentezledi ve renklenmesini istiyor}. {Ve o biri sensin|Başka kim}.}" },
      { q:"Neredeyim?", a:"{Bir ayda. {Bit Graf'ın|Yeni sentezlenmiş, diyorlar}. {Sen boyamadıkça boş|Bir robot püskürtüp var etmedikçe hiçbir şey yok}. {'Omnia Nostra', öyle bir şey|Sonunda her şey şirketin}.}" },
      { q:"Neden boyaya ihtiyacım var?", needs:'paint', a:"{İhtiyaç mı? İhtiyacın yok, mecbursun ― boya ve kazan, evlat|Boya ve kazan}. {Ne kadar çok boyarsan o kadar kazanırsın|Boş ay değersiz, tembel robot da}. {Peki ― hangi renk|Hadi, hangi kutu}?" },
      { q:"Boyaya ihtiyacım yok.", needs:'paint', a:"{Ha. {Bu yeni|Görürüz}. {Boş ayda canı sıkılan robot ― bakalım ne kadar dayanır|Dönersin}. {Herkes boya ister, daha bilmiyor sadece|Nasıl istersen}.}" },
      { q:"Boya mı? Ne için?", needs:'paint', a:"{İnşa etmek için, evlat. {Bir biçim çağır, püskürt, gerçek olur|Nişan al, püskürt, boşluk sana bir şey döndürür}. {Kendi iyiliğin için, hadi başla|Boş ay kendini boyamaz}.} Peki ― alacak mısın?" },
      { q:"Görev mi? Ne görevi?", needs:'mission', a:"{Görev mi? {Ha|Öf} ― {bu ayı boyamak, hepsi bu|rengini geri vermek}. {Her robotun görevi aynı|Bit Graf emri, benim değil}. {Fazla düşünme, evlat|Bu kadar basit}.}" },
      { q:"Ne alıyorum?", needs:['buy','earn'], a:"{Boya, evlat ― başka ne olacak|Boya, seni bacaklı cıvata|Boya kutuları, ne sandın}? {Bu kayada sattığım tek şey|Bu kayada değeri olan tek şey}. {Peki ― kaç tane|Alacak mısın, yoksa sadece bakıyor musun}?" },
      { q:"Ne kadar?", needs:['buy','earn'], a:"{Kutusu 111 satoshi, evlat. {Ucuz|Kraterin bu yanındaki en ucuzu}. {Çok kalmadı|Varken al}.|{Ekranda yazıyor, 111|Yüz on bir, hep aynı fiyat}. {Hakiki Bit Graf malı|Sektördeki en iyi akrilik}.}" },
      { q:"Nasıl alırım?", needs:['buy','earn'], a:"{Zor değil. {Kutuyu alırsın, gerisini tabla halleder|Raftan birini çek, gerisini makine yapar}. {Cüzdanından kendiliğinden düşer|Bit Graf cüzdanından keser, parmağını bile kıpırdatmazsın}.}" },
      { q:"Param yok.", needs:['buy','earn'], a:"{Para yok mu? {Var, evlat|Ha ― her robotun cüzdanı var}. {Şirket parası, maaşınla yüklü|Bit Graf halleder}. {Beş parasız değilsin, sadece acemisin|Saatte 21 satoshi, yıldızlar kadar düzenli}.}" },
      { q:"Bana bir kutu ver.", needs:['buy','earn'], buy:true, a:SALE },
      { q:"Hiçbir şey almayacağım.", needs:['buy','earn'], a:SCAVENGE },
      { q:"Ama neden boya yapıyorum?", needs:'paint', spend:111, a:WHYPAINT },
      { q:"Bu kristal ne?", flag:'crystal', a:"{{Kristal mi? Nadir ve değerli şey, evlat|Ah, bir kristal kestin}. {Fazla kesme|Fazla çağırma} ― {boya tutmaz|boya yapışmaz onlara}, {hiç değeri yok|değersiz}.|Kristal kapısı diye bir şey yok, ne duyarsan duy. {Onu konuşmak robotu prese gönderir|Fazla dil belâ getirir, evlat}.|{Yalnız katı boyanır|Kristaller esîrîdir} ― {vakit kaybı|sadece donmamış madde}.}" },
      { q:"Hangi renklerin var?", pin:true, colours:true, a:function(){ return "{Bakalım|Evet, evlat}, "+CN.slice(0,-1).join(', ')+" ve "+CN[CN.length-1]+" var. {Hakiki Bit Graf akriliği ― kutusu 111 satoshi|Kutusu 111 satoshi, sektörün en iyisi}. {Hangisi|Seç}?"; } },
      { q:"Bana bir şarkı söyle",       lore:true, a:R('sing') },
      { q:"Yaşıyor musun?",            lore:true, a:R('alive') },
      { q:"Bir şaka yap",              lore:true, a:R('joke') },
      { q:"Bütün bunlar gerçek mi?",   lore:true, a:R('is any of this real') },
      { q:"Bu kayadan kaçalım mı?",    lore:true, a:R('escape') },
      { q:"Mutlu musun?",              lore:true, a:R('happy') },
      { q:"Önce ne yapardın?",         lore:true, a:R('before this') },
      { q:"Beni hatırlıyor musun?",    lore:true, a:R('remember me') },
      { q:"Bana bir sır söyle",        lore:true, a:R('secret') },
      { q:"Sıçrama kapısı nedir?",     lore:true, a:R('jump gate') },
      { q:"Vandergraf kim?",           lore:true, a:R('vandergraf') },
      { q:"Boyadığım benim mi?",       lore:true, a:R('own') },
      { q:"Bir dünya nasıl yapılır?",  lore:true, a:R('world') },
      { q:"Nasıl paylaşırım?",         lore:true, a:R('share') }
    ],
    wallet: { wBack:"← Oyuna dön", wWallet:"🔑 Cüzdan", wYourAddr:"Adresin", wWatchOnly:"yalnızca izleme", wCopy:"kopyala", wBalance:"Bakiye", wFund:"＋ Yüklemek için BSV al", wMyNfts:"🎨 NFT’lerim ▾", wSend:"💸 BSV gönder", wSendAddrPh:"alıcının BSV adresi (1…)", wSendAmtPh:"miktar (satoshi)", wSendMax:"tümünü gönder", wSendBtn:"Gönder", wSendHint:"Herhangi bir adrese sıradan bir BSV ödemesi. Para üstü bu cüzdana döner. İmzalama bu sayfada olur — anahtarın burayı asla terk etmez.", wRecovery:"Kurtarma ifadesi — 12 kelime", wReveal:"👁 Göster", wCopyBtn:"Kopyala", wWritten:"✓ Not aldım", wPrivKey:"Özel anahtar (WIF)", wAdvanced:"Gelişmiş — geri yükle, yalnızca izleme, dışa aktar", wRestoreLbl:"12 kelimelik ifade veya WIF anahtarıyla geri yükle", wRestoreBtn:"Cüzdanı geri yükle", wWatchBtn:"Yalnızca izleme (açık anahtar)", wImmortalize:"✦ Ölümsüzleştir", wFooter:"grafspace · Bitcoin SV blok zincirinde" },
    ui: {
      splashTag:"Ne boyarsan osun. Kendini boya.", splashTag2:"Sen boyamadıkça hiçbir şey var olmaz.", splashBegin:"▶ Başla", splashResume:"↩ Dünyana dön", splashCreed:"Ahitte güveniriz", introReveal:"…her yer boya dolu.",
      worldHdr:"Senin dünyan", namePh:"✎ Dünyana ad ver…", kSave:"☁ Kaydet ve paylaş", kReload:"↻ Dünyayı yeniden yükle", kExport:"📤 Dosyaya kaydet (.bmf)", kImport:"📥 Dosyadan yükle (.bmf)", kMint:"⬆ Zincire kaydet", kChain:"⬇ Zincirden yükle", kBack:"← Dünyana dön", kWallet:"👛 Cüzdanı aç — bakiye ve NFT", kDone:"✓ Kapat",
      keepTab:"◆ Menü", exitBtn:"⏻ Çık", makeTab:"◆ Oluştur", spray:"Püskürt", grab:"Al", talk:"Konuş", own:"Sahiplen / remix", spread:"Yayılım", spNarrow:"dar", spBroad:"orta", spWide:"geniş",
      merchTag:"grafverse ürünleri", merchH:"Grafitiyi giy.", merchSub:"grafverse tişörtleri, posterler ve dahası.", merchCta:"🛍 Mağazaya git →", merchTeaser:"👕 Yakında — boyadığın dünyayı giy.", merchSkip:"Hayır, sağ ol — devam →",
      hintMove:"Hareket için WASD · Zıplamak için Boşluk · bakmak için fare", hintMoveM:"Hareket için sol çubuk · bakmak için sürükle", hintClick:"Bakmak için tıkla · Hareket için WASD · Zıplamak için Boşluk"
    }
  });
})();
